import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "CEO Demo | NEFE",
  description: "A guided executive walkthrough of the NEFE Business Network.",
};

const tourCards = [
  { title:"Platform", href:"/platform", number:"01", detail:"See the operating system for connected business growth.", tone:"purple" },
  { title:"Commerce Graph", href:"/commerce-graph", number:"02", detail:"Watch customers, referrals, rewards and revenue move.", tone:"dark" },
  { title:"Experience Builder", href:"/experience-builder", number:"03", detail:"Create a premium multi-partner customer journey.", tone:"gold" },
  { title:"ROI Calculator", href:"/roi-calculator", number:"04", detail:"Model the commercial value for an individual business.", tone:"mint" },
  { title:"Executive Insights", href:"/executive-insights", number:"05", detail:"Understand ecosystem growth at leadership level.", tone:"blue" },
  { title:"Opportunity Engine", href:"/opportunity-engine", number:"07", detail:"Build an ecosystem and simulate its commercial impact live.", tone:"purple" },
  { title:"Business Model", href:"/business-model", number:"08", detail:"Explore pricing, revenue streams, unit economics and financial scale.", tone:"gold" },
  { title:"Merchant Pricing", href:"/pricing", number:"09", detail:"See the simple commercial entry point for pilot businesses.", tone:"mint" },
  { title:"Financial Model", href:"/financial-model", number:"10", detail:"Review assumptions, projections, scenarios and unit economics.", tone:"blue" },
  { title:"Token Utility", href:"/token-utility-economics", number:"11", detail:"Understand utility as a quiet access, rewards and incentive layer.", tone:"gold" },
  { title:"Why Botchain", href:"/why-botchain", number:"06", detail:"Connect real merchant activity to future infrastructure.", tone:"rose" },
];

const chapters = [
  ["01","Opening","0:00"],
  ["02","The problem","0:35"],
  ["03","The solution","1:05"],
  ["04","Product tour","1:40"],
  ["05","Utility layer","3:20"],
  ["06","Pilot plan","4:10"],
  ["07","The ask","4:45"],
];

export default function CeoDemoPage() {
  return (
    <main className="ceo-demo-page overflow-hidden bg-[#FAF9FB] text-[#19152A]">
      <div className="fixed bottom-5 left-5 z-40 hidden rounded-[18px] border border-[#E3DDE8] bg-white/88 p-3 shadow-[0_16px_45px_rgba(42,28,72,.12)] backdrop-blur-xl 2xl:block">
        <p className="px-2 text-[7px] font-bold uppercase tracking-[.16em] text-[#8D8693]">5-minute walkthrough</p>
        <nav className="mt-2 space-y-0.5">{chapters.map(([number,label,time])=><a key={number} href={`#chapter-${number}`} className="flex w-48 items-center gap-2 rounded-lg px-2 py-2 text-[8px] text-[#77707E] transition hover:bg-[#F2EEFF] hover:text-[#5E3BEE]"><span className="font-bold text-[#A69EAC]">{number}</span><span>{label}</span><span className="ml-auto text-[6px] text-[#B1AAB5]">{time}</span></a>)}</nav>
      </div>

      <section id="chapter-01" className="ceo-demo-hero relative grid min-h-[82vh] place-items-center px-5 py-28 text-center">
        <div className="founder-grid absolute inset-0"/><div className="founder-glow one"/><div className="founder-glow two"/>
        <div className="relative z-10 mx-auto max-w-[1050px]"><div className="mx-auto flex w-fit items-center gap-2 rounded-full border border-[#DED4F9] bg-white/70 px-3 py-2 text-[8px] font-bold uppercase tracking-[.17em] text-[#5E3BEE] shadow-sm backdrop-blur"><span className="text-[#C39840]">✦</span>Executive walkthrough · 5 minutes</div><h1 className="mt-8 text-[48px] font-semibold leading-[1.03] tracking-[-.06em] sm:text-[72px] lg:text-[88px]">The business network where <span className="gradient-text">growth becomes connected.</span></h1><p className="mx-auto mt-8 max-w-[720px] text-base leading-8 text-[#6F6876] sm:text-lg">NEFE helps businesses discover partners, share customers, build experiences and create measurable revenue together.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><a href="#chapter-02" className="button-primary">Begin the walkthrough ↓</a><Link href="/platform" className="button-secondary">Skip to the product</Link></div></div>
      </section>

      <section id="chapter-02" className="mx-auto max-w-[1240px] px-5 py-24 sm:px-8 sm:py-32">
        <div className="grid items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><div className="eyebrow">01:05 · The Problem</div><h2 className="mt-6 text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Businesses serve the same customers.<br/><span className="text-[#9B94A1]">But operate separately.</span></h2><p className="mt-6 max-w-lg text-[12px] leading-6 text-[#7D7683]">Every business optimizes its own transaction, database and loyalty program. The commercial opportunity between businesses remains invisible and unmanaged.</p></div><div className="relative grid gap-3 sm:grid-cols-2">{[["Customer journey","Ends after one purchase"],["Partner opportunity","Managed manually"],["Customer value","Trapped in one business"],["Loyalty","Fragmented across brands"]].map(([title,detail],i)=><article key={title} className="rounded-[22px] border border-[#E8E3EB] bg-white p-5 shadow-[0_8px_25px_rgba(43,30,67,.035)]"><span className="text-[8px] font-bold text-[#B1AAB5]">0{i+1}</span><h3 className="mt-8 text-[14px] font-semibold">{title}</h3><p className="mt-2 text-[9px] text-[#8A838F]">{detail}</p><div className="mt-5 h-1 rounded-full bg-[#EEEAF1]"><div className="h-full w-[22%] rounded-full bg-[#B7AFBC]"/></div></article>)}</div></div>
      </section>

      <section id="chapter-03" className="relative overflow-hidden bg-[#171122] px-5 py-24 text-white sm:px-8 sm:py-32">
        <div className="founder-dark-grid absolute inset-0"/><div className="relative z-10 mx-auto grid max-w-[1240px] items-center gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><div className="eyebrow eyebrow-dark">01:40 · The Solution</div><h2 className="mt-6 text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">One connected commercial ecosystem.</h2><p className="mt-6 max-w-lg text-[12px] leading-6 text-white/45">NEFE creates the software layer between businesses—coordinating partnership discovery, campaigns, referrals, experiences, intelligence and rewards.</p><div className="mt-8 grid grid-cols-3 gap-3">{[["1,247","Businesses"],["48.3K","Referrals"],["AED 12.8M","Revenue"]].map(([value,label])=><div key={label} className="rounded-xl border border-white/10 bg-white/[.05] p-3"><p className="text-lg font-semibold">{value}</p><p className="mt-1 text-[7px] text-white/30">{label}</p></div>)}</div></div><div className="relative mx-auto h-[420px] w-full max-w-[570px]"><svg viewBox="0 0 570 420" className="absolute inset-0 h-full w-full">{[[285,210,90,80],[285,210,480,80],[285,210,505,300],[285,210,285,370],[285,210,65,300]].map((p,i)=><g key={i}><path d={`M${p[0]} ${p[1]} Q285 210 ${p[2]} ${p[3]}`} fill="none" stroke="rgba(165,138,239,.28)" strokeDasharray="5 7" className="commerce-dash"/><circle r="3" fill={i%2?"#E0BD67":"#5BD0A2"}><animateMotion dur={`${4+i*.4}s`} repeatCount="indefinite" path={`M${p[0]} ${p[1]} Q285 210 ${p[2]} ${p[3]}`}/></circle></g>)}</svg><div className="absolute left-1/2 top-1/2 grid h-28 w-28 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-gradient-to-br from-[#6845DF] to-[#2C1A5A] text-center shadow-[0_0_80px_rgba(103,65,223,.4)]"><div><b className="text-lg">NEFE</b><small className="mt-1 block text-[6px] uppercase tracking-wider text-[#C7B5FA]">Commerce core</small></div></div>{[["Hotel","left-[7%] top-[10%]"],["Restaurant","right-[5%] top-[10%]"],["Mobility","right-0 bottom-[12%]"],["Experience","left-1/2 bottom-0 -translate-x-1/2"],["Wellness","left-0 bottom-[12%]"]].map(([name,pos])=><div key={name} className={`absolute ${pos} w-24 rounded-[14px] border border-white/10 bg-white/[.07] p-3 text-center text-[8px] font-semibold backdrop-blur`}>{name}</div>)}</div></div>
      </section>

      <section id="chapter-04" className="mx-auto max-w-[1240px] px-5 py-24 sm:px-8 sm:py-32"><div className="text-center"><div className="eyebrow mx-auto">01:40 — 03:20 · Live Product Tour</div><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Eleven views. One connected thesis.</h2><p className="mx-auto mt-5 max-w-xl text-[11px] leading-6 text-[#7D7683]">Open any experience in a new part of the prototype and return here to continue the walkthrough.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tourCards.map(card=><Link key={card.href} href={card.href} className={`ceo-tour-card ${card.tone} group relative min-h-56 overflow-hidden rounded-[24px] border p-6 transition hover:-translate-y-2 hover:shadow-[0_22px_50px_rgba(48,32,88,.12)]`}><div className="flex items-center justify-between"><span className="text-[9px] font-bold opacity-50">{card.number}</span><span className="grid h-8 w-8 place-items-center rounded-full border border-current/10 bg-white/10 transition group-hover:translate-x-1">↗</span></div><h3 className="mt-14 text-xl font-semibold tracking-[-.03em]">{card.title}</h3><p className="mt-3 max-w-xs text-[9px] leading-5 opacity-60">{card.detail}</p></Link>)}</div></section>

      <section id="chapter-05" className="bg-[#F1EEF4] px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-[1240px]"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="eyebrow">03:20 · NEFE Utility Layer</div><h2 className="mt-6 text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Useful first.<br/><span className="gradient-text">Infrastructure-ready.</span></h2><p className="mt-5 text-[11px] leading-6 text-[#7A7380]">Customers and merchants receive immediate value. The infrastructure underneath can become more capable without making participation more complex.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["Rewards","Recognize valuable actions across businesses."],["Access","Unlock priority moments and experiences."],["Membership","Create status that travels across the network."],["Incentives","Align businesses and customers around growth."],["Future payments","Embed transaction infrastructure when value is proven."]].map(([title,detail],i)=><article key={title} className={`rounded-[20px] border p-5 ${i===4?"border-[#6D4BE0] bg-gradient-to-br from-[#22163D] to-[#5030B7] text-white sm:col-span-2":"border-[#E2DDE6] bg-white"}`}><span className={`grid h-9 w-9 place-items-center rounded-xl text-[9px] font-bold ${i===4?"bg-white/10 text-[#E2C26D]":"bg-[#F0ECFF] text-[#5E3BEE]"}`}>0{i+1}</span><h3 className="mt-5 text-[14px] font-semibold">{title}</h3><p className={`mt-2 text-[9px] leading-5 ${i===4?"text-white/45":"text-[#817A86]"}`}>{detail}</p></article>)}</div></div></div></section>

      <section id="chapter-06" className="mx-auto max-w-[1240px] px-5 py-24 sm:px-8 sm:py-32"><div className="eyebrow">04:10 · Pilot Plan</div><h2 className="mt-6 max-w-3xl text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Start focused. Prove revenue.<br/>Expand city by city.</h2><div className="relative mt-14 grid gap-4 md:grid-cols-3"><div className="absolute left-[16%] right-[16%] top-9 hidden h-px bg-gradient-to-r from-[#BFAFF1] via-[#D2A64A] to-[#61AB91] md:block"/>{[["01","Start with UAE businesses","Recruit a curated group of premium hospitality, dining, mobility, wellness and lifestyle partners."],["02","Validate commercial impact","Measure partner revenue, referral acceptance, customer value and repeat behavior."],["03","Expand city by city","Use proven playbooks to grow across the UAE, GCC and connected global markets."]].map(([number,title,detail],i)=><article key={number} className="relative text-center"><span className={`relative z-10 mx-auto grid h-18 w-18 place-items-center rounded-[22px] border bg-white text-sm font-bold shadow-[0_12px_30px_rgba(52,35,95,.08)] ${i===0?"border-[#BCAAF4] text-[#5E3BEE]":i===1?"border-[#E2CB93] text-[#A97B21]":"border-[#A7D2C1] text-[#28856A]"}`}>{number}</span><h3 className="mt-6 text-[16px] font-semibold">{title}</h3><p className="mx-auto mt-3 max-w-xs text-[9px] leading-5 text-[#817A86]">{detail}</p></article>)}</div></section>

      <section id="chapter-07" className="ceo-demo-close relative overflow-hidden bg-[#0B0811] px-5 py-32 text-center text-white sm:px-8 sm:py-40"><div className="founder-dark-grid absolute inset-0"/><div className="founder-vision-orb"/><div className="relative z-10 mx-auto max-w-4xl"><span className="text-2xl text-[#E1C16B]">✦</span><p className="mt-6 text-[9px] font-bold uppercase tracking-[.2em] text-[#A98FF1]">04:45 · Explore the prototype</p><h2 className="mt-7 text-[40px] font-semibold leading-tight tracking-[-.05em] sm:text-[62px]">The network is ready to be experienced.</h2><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-white/45">See the business platform, move through the consumer experience, or model the opportunity for a pilot partner.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/platform" className="inline-flex h-13 items-center justify-center rounded-xl bg-white px-6 text-[10px] font-semibold text-[#4F30C9] shadow-xl transition hover:-translate-y-1">Explore the prototype →</Link><Link href="/business-portal" className="inline-flex h-13 items-center justify-center rounded-xl border border-white/15 bg-white/[.06] px-6 text-[10px] font-semibold text-white transition hover:-translate-y-1">Open Business Portal</Link><Link href="/pilot-plan" className="inline-flex h-13 items-center justify-center rounded-xl border border-[#D1AA50]/30 bg-[#D1AA50]/10 px-6 text-[10px] font-semibold text-[#E4C675] transition hover:-translate-y-1">View Pilot Plan</Link></div></div></section>
    </main>
  );
}
