import Link from "next/link";
import {notFound} from "next/navigation";
import {getBusinessDetail} from "@/app/lib/data/business-repository";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {can} from "@/app/lib/auth/permissions";
import NextActions from "../../_components/next-actions";
import EntityCollaboration from "../../_components/entity-collaboration";
import EntityDecisions from "../../_components/entity-decisions";
import WorkspaceBreadcrumbs from "../../_components/workspace-breadcrumbs";
import {FavoriteButton,ViewTracker} from "../../_components/entity-actions";
import {AppCard,DataTable,EmptyState,PageHeader,SectionHeader,StatBadge,StatusBadge} from "../../_components/ui";
import BusinessProfileEditor from "./business-profile-editor";
import BusinessNetworkManager from "./business-network-manager";

const active=(status:string)=>!['COMPLETED','PAUSED','CANCELLED'].includes(status),aed=(value:string|null)=>`AED ${Number(value??0).toLocaleString()}`;
export default async function BusinessProfilePage({params}:{params:Promise<{businessId:string}>}){const {businessId}=await params,context=await requireWorkspaceContext(),detail=await getBusinessDetail(context,businessId);if(!detail)notFound();const {business}=detail,canManage=can(context.membership.role,"business.manage"),activeOpportunities=detail.opportunities.filter(item=>active(item.status)).length,activeCampaigns=detail.campaigns.filter(item=>active(item.status)).length,activePilots=detail.pilots.filter(item=>active(item.status)).length,decisionAttention=detail.decisions.filter(item=>['pending_review','pending_approval','changes_requested','expired'].includes(item.status)).length,collaborationCount=detail.activity.filter(item=>item.eventType.startsWith("comment.")||item.eventType.startsWith("assignment.")||item.eventType.startsWith("entity.")).length;return <><ViewTracker type="business" id={business.id} title={business.name} href={`/workspace/businesses/${business.id}`}/><WorkspaceBreadcrumbs section="Businesses" href="/workspace/businesses" current={business.name}/><PageHeader eyebrow="Business workspace" title={business.name} description={business.description} action={<div className="ws-action-bar"><FavoriteButton type="business" id={business.id}/><BusinessProfileEditor business={business} industries={detail.industries} regions={detail.regions} allowed={canManage}/></div>}/>
<section aria-labelledby="business-overview"><SectionHeader title="Overview" description="Company profile, ownership, geography, and current network standing."/><div className="ws-profile-summary"><AppCard><div className="ws-business-hero"><span className="ws-avatar">{business.initials}</span><div><StatusBadge tone={business.status}>{business.status}</StatusBadge><h2>{business.name}</h2><p>{business.category} · {business.industry??"Unclassified"}</p><small>{business.country??"Country not recorded"} · {business.region??"Region not recorded"} · {business.location}</small></div></div><div className="ws-detail-grid ws-profile-stats"><StatBadge label="Verification" value={business.verification}/><StatBadge label="Owner" value={detail.assignment?.assigneeName??"Unassigned"}/><StatBadge label="Last updated" value={business.updatedAt.toLocaleDateString()}/><StatBadge label="Relationships" value={String(detail.relationships.length)}/></div></AppCard><NextActions actions={[{label:"Create opportunity",href:`/workspace/opportunities?business=${business.id}`,description:"Start a commercial opportunity with this business preselected.",primary:true,disabledReason:can(context.membership.role,"opportunity.update")?undefined:"Your role cannot create opportunities."},{label:"Create journey",href:`/workspace/journeys?business=${business.id}`,description:"Map a customer journey beginning with this business.",disabledReason:canManage?undefined:"Your role cannot create journeys."},{label:"Start discussion",href:"#collaboration",description:"Open the persisted collaboration panel."},{label:"Create executive decision",href:"#executive-decisions",description:"Propose a formal decision for this business.",disabledReason:can(context.membership.role,"decision.create")?undefined:"Your role cannot create decisions."}]}/></div></section>
<EntityCollaboration entityType="business" entityId={business.id}/>
<section className="ws-section-gap" aria-labelledby="business-health"><SectionHeader title="Commercial Health" description="Derived participation signals from current persisted records; these are not recorded performance facts."/><AppCard><div className="ws-business-health-grid"><StatBadge label="Opportunity activity" value={String(activeOpportunities)}/><StatBadge label="Campaign activity" value={String(activeCampaigns)}/><StatBadge label="Pilot activity" value={String(activePilots)}/><StatBadge label="Journey coverage" value={`${detail.journeys.length} journeys`}/><StatBadge label="Decision attention" value={String(decisionAttention)}/><StatBadge label="Collaboration activity" value={String(collaborationCount)}/></div>{detail.recommendations.length>0&&<div className="ws-health-notes"><strong>Persisted recommendations</strong>{detail.recommendations.map(item=><Link href="/workspace/recommendations" key={item.id}>{item.title} · {item.status}</Link>)}</div>}</AppCard></section>
<RecordSection id="business-opportunities" title="Opportunities" description="Commercial opportunities involving this business." empty="No opportunities involve this business yet." count={detail.opportunities.length}><DataTable label="Business opportunities" headers={["Opportunity","Stage","Status","Modeled value"]}>{detail.opportunities.map(item=><tr key={item.id}><td><Link href={`/workspace/opportunities/${item.id}`}><strong>{item.title}</strong></Link></td><td>{item.stage.replaceAll("_"," ")}</td><td><StatusBadge tone={item.status}>{item.status}</StatusBadge></td><td>{aed(item.modeledValue)}</td></tr>)}</DataTable></RecordSection>
<RecordSection id="business-campaigns" title="Campaigns" description="Campaign participation and stated objectives." empty="No campaigns currently include this business." count={detail.campaigns.length}><div className="ws-list">{detail.campaigns.map(item=><Link className="ws-list-item" href={`/workspace/campaigns/${item.id}`} key={item.id}><span>C</span><div><strong>{item.title}</strong><p>{item.objective}</p></div><StatusBadge tone={item.status}>{item.status}</StatusBadge></Link>)}</div></RecordSection>
<RecordSection id="business-journeys" title="Journeys" description="Customer journeys in which this business participates." empty="No customer journeys currently include this business." count={detail.journeys.length}><div className="ws-list">{detail.journeys.map(item=><Link className="ws-list-item" href={`/workspace/journeys/${item.id}`} key={item.id}><span>J</span><div><strong>{item.name}</strong><p>{item.coverage}% coverage · {item.completion}% complete</p></div></Link>)}</div></RecordSection>
<RecordSection id="business-pilots" title="Pilots" description="Execution pilots involving this business." empty="No pilots currently include this business." count={detail.pilots.length}><div className="ws-list">{detail.pilots.map(item=><Link className="ws-list-item" href={`/workspace/pilots/${item.id}`} key={item.id}><span>P</span><div><strong>{item.name}</strong><p>{aed(item.modeledValue)} modeled value</p></div><StatusBadge tone={item.status}>{item.status}</StatusBadge></Link>)}</div></RecordSection>
<EntityDecisions entityType="business" entityId={business.id}/>
<section className="ws-section-gap" aria-labelledby="business-network-records"><SectionHeader title="Relationships, Contacts and Services" description="Persisted network records supporting commercial work with this business."/><AppCard><BusinessNetworkManager businessId={business.id} contacts={detail.contacts} services={detail.services} tags={detail.tags} relationships={detail.relationships} businesses={detail.businessOptions} allowed={canManage}/></AppCard></section>
<RecordSection id="business-activity" title="Activity" description="Latest meaningful business, collaboration, and governance events." empty="No activity has been recorded for this business." count={detail.activity.length}><div className="ws-timeline">{detail.activity.map(item=><article className="ws-timeline-item" key={item.id}><h3>{item.summary}</h3><p>{item.actorName??"System"} · {item.createdAt.toLocaleString()}</p></article>)}</div></RecordSection></>}

function RecordSection({id,title,description,empty,count,children}:{id:string;title:string;description:string;empty:string;count:number;children:React.ReactNode}){return <section className="ws-section-gap" aria-labelledby={id}><SectionHeader title={title} description={description}/><AppCard>{count?children:<EmptyState title={`No ${title.toLowerCase()}`} description={empty}/>}</AppCard></section>}
