import type { Activity, AnalyticsSnapshot, Business, Campaign, Industry, Invitation, Journey, Notification, Opportunity, Organization, Partner, Recommendation, Region, Task, User } from "./models";

export const regions: Region[] = [{ id: "rak", name: "Ras Al Khaimah", country: "United Arab Emirates", code: "RAK" }];
export const industries: Industry[] = [
  { id: "hospitality", name: "Hospitality", category: "Destination" }, { id: "mobility", name: "Mobility", category: "Transport" },
  { id: "dining", name: "Dining", category: "Experience" }, { id: "wellness", name: "Wellness", category: "Experience" },
  { id: "retail", name: "Retail", category: "Commerce" }, { id: "development", name: "Destination Development", category: "Anchor" },
];
export const organization: Organization = { id: "nefe-rak", name: "RAK Connected Destination Pilot", regionId: "rak", plan: "Pilot", status: "active" };
export const currentUser: User = { id: "user-am", name: "Amira Mansour", email: "amira@nefe.example", role: "Workspace Administrator", initials: "AM", organizationId: organization.id };
export const users: User[] = [currentUser, { id: "user-yk", name: "Yousef Khalid", email: "yousef@nefe.example", role: "Commercial Lead", initials: "YK", organizationId: organization.id }, { id: "user-ln", name: "Leila Nasser", email: "leila@nefe.example", role: "Experience Lead", initials: "LN", organizationId: organization.id }];
export const businesses: Business[] = [
  { id:"resort",name:"RAK Resort Development",initials:"RR",industryId:"development",regionId:"rak",location:"Al Marjan Island",category:"Destination anchor",description:"Destination development anchor coordinating hospitality, mobility and experience participation across the RAK pilot.",services:["Destination planning","Partner coordination","Visitor experience design"],products:["RAK Connected Escape","Destination Welcome"],status:"active",verification:"Verified",partnerCount:7,partnerScore:96,opportunityScore:98,tags:["Pilot anchor","Real estate"],contacts:[{name:"Omar Rahman",role:"Commercial Director",email:"omar@rakresort.example"}] },
  { id:"hotel",name:"RAK Hotel Partner",initials:"RH",industryId:"hospitality",regionId:"rak",location:"Al Marjan Island",category:"Hospitality",description:"Premium hotel participant connecting guest stays with mobility, dining and destination experiences.",services:["Accommodation","Guest services","Concierge"],products:["Connected Stay","Stay + Dining"],status:"active",verification:"Verified",partnerCount:6,partnerScore:94,opportunityScore:96,tags:["Hotel","Premium"],contacts:[{name:"Sara Malik",role:"General Manager",email:"sara@rakhotel.example"}] },
  { id:"f10",name:"F10 Car Rental",initials:"F10",industryId:"mobility",regionId:"rak",location:"Al Hamra",category:"Mobility",description:"Premium mobility partner supporting airport arrival, resort transfer and destination movement.",services:["Airport transfer","Vehicle rental","Executive transport"],products:["Executive Arrival","Resort Mobility Pass"],status:"active",verification:"Verified",partnerCount:6,partnerScore:93,opportunityScore:97,tags:["Arrival","Transport"],contacts:[{name:"Faris Haddad",role:"Partnerships Lead",email:"faris@f10.example"}] },
  { id:"waldorf",name:"Waldorf Astoria RAK",initials:"WA",industryId:"hospitality",regionId:"rak",location:"Al Hamra Village",category:"Hospitality",description:"Luxury hospitality anchor contributing premium stay, wellness and member-return touchpoints.",services:["Luxury accommodation","Concierge","Wellness access"],products:["Member Return Stay","Wellness Weekend"],status:"active",verification:"Verified",partnerCount:5,partnerScore:91,opportunityScore:89,tags:["Hotel","Luxury"],contacts:[{name:"Nadia Kareem",role:"Experience Director",email:"nadia@waldorf.example"}] },
  { id:"beach",name:"Beach Club Partner",initials:"BC",industryId:"hospitality",regionId:"rak",location:"Al Marjan Island",category:"Beach experience",description:"Candidate leisure partner extending hotel journeys into coastal experiences and evening dwell time.",services:["Beach access","Private cabanas","Guest events"],products:["Sunset Access","Hotel + Beach"],status:"pending",verification:"In review",partnerCount:4,partnerScore:86,opportunityScore:92,tags:["Leisure","Experience"],contacts:[{name:"Maya Saleh",role:"Operations Lead",email:"maya@beachclub.example"}] },
  { id:"restaurant",name:"Premium Restaurant Partner",initials:"PR",industryId:"dining",regionId:"rak",location:"Mina Al Arab",category:"Dining",description:"Destination dining participant designed to complete the guest journey from stay to evening experience.",services:["Fine dining","Private events","Hotel reservations"],products:["Sunset Dining","Chef + Chauffeur"],status:"active",verification:"Verified",partnerCount:5,partnerScore:88,opportunityScore:90,tags:["Dining","Evening"],contacts:[{name:"Karim Aziz",role:"Commercial Manager",email:"karim@restaurant.example"}] },
  { id:"wellness",name:"Wellness Partner",initials:"WP",industryId:"wellness",regionId:"rak",location:"Al Hamra",category:"Wellness",description:"Candidate wellness operator supporting recovery, retention and repeat-visit journeys.",services:["Spa treatment","Recovery programs","Member wellness"],products:["Recovery Stay","Wellness Weekend"],status:"pending",verification:"In review",partnerCount:3,partnerScore:82,opportunityScore:87,tags:["Wellness","Retention"],contacts:[{name:"Lina Saad",role:"Partnership Manager",email:"lina@wellness.example"}] },
  { id:"retail",name:"Retail Partner",initials:"RP",industryId:"retail",regionId:"rak",location:"RAK City",category:"Retail",description:"Invited retail participant providing accessible redemption and destination-shopping moments.",services:["Destination retail","Member redemption","Gift fulfillment"],products:["Destination Welcome","Member Rewards"],status:"pending",verification:"Invited",partnerCount:3,partnerScore:76,opportunityScore:80,tags:["Rewards","Retail"],contacts:[{name:"Tariq Noor",role:"Retail Director",email:"tariq@retail.example"}] },
];
export const partners: Partner[] = businesses.slice(1).map((business,index)=>({ id:`partner-${index+1}`,businessId:business.id,relationship:index<4?"Pilot participant":"Candidate participant",status:index<4?"active":"pending",since:`2026-0${Math.min(index+1,7)}-12` }));
export const opportunities: Opportunity[] = [
  { id:"opp-1",title:"Connected RAK Weekend Escape",status:"active",priority:"high",businessIds:["resort","hotel","f10","waldorf"],estimatedValue:1035000,stage:"Pilot",ownerId:"user-yk",createdAt:"2026-07-18",summary:"Connect arrival, accommodation, mobility and resort experiences in one measurable destination journey.",commercialReasoning:"The businesses share premium destination customers at complementary moments and can coordinate one governed offer without duplicating core services.",compatibility:96,journeyImpact:"Closes arrival, transfer, check-in and member-return touchpoints.",notes:["Confirm weekly KPI owner before launch."],statusHistory:[{label:"Pilot",date:"2026-07-24",detail:"Approved for controlled pilot planning."},{label:"Qualified",date:"2026-07-20",detail:"Commercial fit and ownership confirmed."}] },
  { id:"opp-2",title:"Stay, Dine and Sunset Experience",status:"pending",priority:"high",businessIds:["hotel","restaurant","beach"],estimatedValue:462000,stage:"Negotiating",ownerId:"user-ln",createdAt:"2026-07-20",summary:"Extend guest dwell time with a coordinated hospitality, dining and beach offer.",commercialReasoning:"Hotel guests have a clear evening need that the dining and beach partners can serve through one coordinated reservation path.",compatibility:91,journeyImpact:"Extends the journey from check-in through dining and sunset leisure.",notes:["Beach Club verification remains in review."],statusHistory:[{label:"Negotiating",date:"2026-07-25",detail:"Commercial terms shared with participants."},{label:"Identified",date:"2026-07-20",detail:"Opportunity surfaced from journey gap."}] },
  { id:"opp-3",title:"Wellness Return Journey",status:"draft",priority:"medium",businessIds:["waldorf","wellness","retail"],estimatedValue:218000,stage:"Qualified",ownerId:"user-am",createdAt:"2026-07-23",summary:"Model a post-stay wellness and rewards path intended to improve repeat-visit potential.",commercialReasoning:"Wellness and retail provide lower-friction reasons to re-engage premium hotel guests after departure.",compatibility:84,journeyImpact:"Adds post-stay recovery, redemption and return prompts.",notes:["Validate consent and retention assumptions."],statusHistory:[{label:"Qualified",date:"2026-07-25",detail:"Initial partner fit confirmed."}] },
  { id:"opp-4",title:"Destination Welcome Rewards",status:"pending",priority:"medium",businessIds:["resort","retail"],estimatedValue:132000,stage:"Identified",ownerId:"user-am",createdAt:"2026-07-24",summary:"Create a simple arrival redemption that introduces the connected destination.",commercialReasoning:"An accessible welcome benefit can orient visitors to the network without adding booking complexity.",compatibility:78,journeyImpact:"Adds a low-friction destination discovery touchpoint.",notes:["Retail Partner invitation is pending."],statusHistory:[{label:"Identified",date:"2026-07-24",detail:"Created from arrival journey review."}] },
  { id:"opp-5",title:"Executive Arrival Partnership",status:"active",priority:"high",businessIds:["f10","waldorf"],estimatedValue:286000,stage:"Active",ownerId:"user-yk",createdAt:"2026-07-10",summary:"Coordinate premium transfers with luxury hotel arrival and concierge handoff.",commercialReasoning:"Both participants serve the same premium traveler in directly adjacent journey moments.",compatibility:95,journeyImpact:"Connects booking, airport arrival, transfer and hotel welcome.",notes:["Monitor handoff completion weekly."],statusHistory:[{label:"Active",date:"2026-07-22",detail:"Controlled campaign activated."}] },
  { id:"opp-6",title:"Hospitality Partner Alignment",status:"completed",priority:"low",businessIds:["hotel","waldorf"],estimatedValue:164000,stage:"Completed",ownerId:"user-ln",createdAt:"2026-06-30",summary:"Establish shared overflow and guest-experience operating rules.",commercialReasoning:"Clear coordination protects guest experience during high-demand periods.",compatibility:88,journeyImpact:"Protects continuity when capacity changes.",notes:["Operating playbook approved."],statusHistory:[{label:"Completed",date:"2026-07-16",detail:"Partner operating rules accepted."}] },
  { id:"opp-7",title:"Coastal Experience Bundle",status:"pending",priority:"medium",businessIds:["beach","restaurant"],estimatedValue:194000,stage:"Approved",ownerId:"user-ln",createdAt:"2026-07-19",summary:"Package sunset beach access with a premium dining reservation.",commercialReasoning:"The combined offer creates a complete evening proposition with shared booking intent.",compatibility:89,journeyImpact:"Fills the transition between daytime leisure and dining.",notes:["Launch waits on verification completion."],statusHistory:[{label:"Approved",date:"2026-07-25",detail:"Commercial design approved conditionally."}] },
];
export const campaigns: Campaign[] = [
  { id:"camp-1",title:"RAK Weekend Escape",objective:"Increase qualified destination bookings",status:"active",businessIds:["resort","hotel","f10"],budget:180000,startDate:"2026-08-15",endDate:"2026-11-15",modeledValue:721000,conversion:18.4,progress:68,milestones:[{title:"Commercial approval",date:"2026-07-22",status:"complete"},{title:"Partner readiness",date:"2026-08-05",status:"current"},{title:"Controlled launch",date:"2026-08-15",status:"upcoming"}],kpis:[{label:"Modeled referrals",value:"920"},{label:"Conversion",value:"18.4%"},{label:"Journey coverage",value:"92%"}] },
  { id:"camp-2",title:"Executive Resort Transfer",objective:"Connect premium arrivals to hospitality",status:"pending",businessIds:["f10","waldorf"],budget:75000,startDate:"2026-09-01",endDate:"2026-10-31",modeledValue:286000,conversion:14.2,progress:42,milestones:[{title:"Commercial design",date:"2026-07-24",status:"complete"},{title:"Measurement owner",date:"2026-08-04",status:"current"},{title:"Pilot launch",date:"2026-09-01",status:"upcoming"}],kpis:[{label:"Modeled referrals",value:"340"},{label:"Conversion",value:"14.2%"},{label:"Handoff completion",value:"88%"}] },
  { id:"camp-3",title:"Sunset Dining Journey",objective:"Extend guest dwell and evening spend",status:"draft",businessIds:["hotel","restaurant","beach"],budget:62000,startDate:"2026-09-15",endDate:"2026-12-15",modeledValue:194000,conversion:11.8,progress:24,milestones:[{title:"Opportunity review",date:"2026-07-23",status:"complete"},{title:"Partner approval",date:"2026-08-10",status:"current"},{title:"Asset readiness",date:"2026-09-05",status:"upcoming"}],kpis:[{label:"Modeled referrals",value:"260"},{label:"Conversion",value:"11.8%"},{label:"Evening coverage",value:"76%"}] },
];
export const journeys: Journey[] = [
  { id:"journey-1",name:"Connected Destination Arrival",businessIds:["f10","resort","hotel","waldorf"],coverage:92,completion:78,touchpoints:7,stages:[{id:"j1-1",title:"Airport arrival",businessId:"f10",touchpoint:"Transfer booking",status:"covered"},{id:"j1-2",title:"Resort check-in",businessId:"resort",touchpoint:"Welcome offer",status:"covered"},{id:"j1-3",title:"Hotel stay",businessId:"hotel",touchpoint:"Guest experience",status:"covered"},{id:"j1-4",title:"Return invitation",businessId:"waldorf",touchpoint:"Member follow-up",status:"gap"}] },
  { id:"journey-2",name:"Stay to Sunset",businessIds:["hotel","restaurant","beach"],coverage:76,completion:61,touchpoints:5,stages:[{id:"j2-1",title:"Stay discovery",businessId:"hotel",touchpoint:"In-stay prompt",status:"covered"},{id:"j2-2",title:"Dining reservation",businessId:"restaurant",touchpoint:"Partner booking",status:"covered"},{id:"j2-3",title:"Beach experience",businessId:"beach",touchpoint:"Sunset admission",status:"gap"}] },
];
export const analyticsSnapshots: AnalyticsSnapshot[] = [{ id:"analytics-jul",period:"July 2026",modeledValue:1443000,referrals:1730,conversion:17.6,partnerGrowth:12.5,journeyCoverage:84,series:[42,48,51,58,64,69,74,81,86,92,101,108] }];
export const invitations: Invitation[] = [{id:"inv-1",email:"operations@beachclub.example",role:"Business operator",status:"accepted",sentAt:"2026-07-23"},{id:"inv-2",email:"partnerships@wellness.example",role:"Commercial owner",status:"pending",sentAt:"2026-07-24"}];
export const recommendations: Recommendation[] = [{id:"rec-1",title:"Complete the evening journey",description:"Approve the Beach Club Partner to close the stay-to-sunset coverage gap.",priority:"high",recommendedBusinessId:"beach",opportunityId:"opp-2",estimatedImpact:194000,journeyImprovement:"Raises evening journey coverage from 76% to a modeled 91%.",commercialRationale:"Beach access complements hotel and dining demand without competing for the same transaction.",confidence:91},{id:"rec-2",title:"Add wellness to the return journey",description:"Review Wellness Partner as the next participant for post-stay retention.",priority:"medium",recommendedBusinessId:"wellness",opportunityId:"opp-3",estimatedImpact:218000,journeyImprovement:"Adds recovery and return touchpoints after departure.",commercialRationale:"Wellness creates a relevant reason to re-engage premium hospitality guests.",confidence:84}];
export const notifications: Notification[] = [{id:"note-1",title:"Partner accepted invitation",detail:"Beach Club Partner accepted the workspace invitation.",type:"partner",read:false,createdAt:"12 minutes ago"},{id:"note-2",title:"Opportunity updated",detail:"Connected RAK Weekend Escape moved to pilot design.",type:"opportunity",read:false,createdAt:"1 hour ago"},{id:"note-3",title:"Campaign approved",detail:"RAK Weekend Escape passed commercial review.",type:"campaign",read:true,createdAt:"Yesterday"},{id:"note-4",title:"Journey modified",detail:"A return-invitation gap was added to Connected Destination Arrival.",type:"journey",read:true,createdAt:"2 days ago"},{id:"note-5",title:"Pilot scheduled",detail:"Executive pilot review is scheduled for 30 July.",type:"pilot",read:false,createdAt:"3 days ago"}];
export const activities: Activity[] = [{id:"act-1",title:"Partner joined",detail:"Beach Club Partner accepted the pilot workspace invitation.",actorId:"user-am",createdAt:"12 minutes ago",type:"partner"},{id:"act-2",title:"Campaign launched",detail:"RAK Weekend Escape moved into controlled activation.",actorId:"user-yk",createdAt:"18 minutes ago",type:"campaign"},{id:"act-3",title:"Journey updated",detail:"Connected Destination Arrival now covers 92% of planned touchpoints.",actorId:"user-ln",createdAt:"2 hours ago",type:"journey"},{id:"act-4",title:"Recommendation accepted",detail:"The team moved Beach Club Partner into commercial review.",actorId:"user-ln",createdAt:"4 hours ago",type:"recommendation"},{id:"act-5",title:"Pilot started",detail:"Executive Arrival Partnership entered active pilot monitoring.",actorId:"user-yk",createdAt:"Yesterday",type:"pilot"},{id:"act-6",title:"Opportunity created",detail:"Destination Welcome Rewards was added to the pipeline.",actorId:"user-am",createdAt:"Yesterday",type:"opportunity"}];
export const tasks: Task[] = [{id:"task-1",title:"Approve Beach Club verification",due:"Today",ownerId:"user-am",status:"open"},{id:"task-2",title:"Confirm Executive Transfer measurement owner",due:"Tomorrow",ownerId:"user-yk",status:"open"},{id:"task-3",title:"Review return-journey coverage gap",due:"31 Jul",ownerId:"user-ln",status:"open"}];

export const getBusiness = (id: string) => businesses.find((business) => business.id === id);
export const getUser = (id: string) => users.find((user) => user.id === id);
export const formatAed = (value: number) => `AED ${value.toLocaleString("en-US")}`;
