import {describe,expect,it,vi} from "vitest";
import {GENERIC_REGISTRATION_ERROR,INTERNAL_REGISTRATION_ROLE,registerInternalAccount,RegistrationDiagnosticError,RegistrationUnavailableError,type AtomicRegistration,type RegistrationAvailabilityDiagnostic,type RegistrationDiagnostic} from "../app/lib/auth/internal-registration";

const configuration={invitationCode:"a-secure-internal-code",organizationSlug:"nefe-internal-testing"};
const valid={fullName:"Amina Rahman",email:" Amina@Example.com ",password:"correct-horse-battery",confirmPassword:"correct-horse-battery",invitationCode:configuration.invitationCode,termsAccepted:true};
const attemptId="11111111-1111-4111-8111-111111111111";
function dependencies(createAccount=vi.fn(async (input:AtomicRegistration)=>{void input})){return {hashPassword:vi.fn(async()=>"secure-hash"),createAccount,reportFailure:vi.fn<(diagnostic:RegistrationDiagnostic)=>void>(),reportAvailability:vi.fn<(diagnostic:RegistrationAvailabilityDiagnostic)=>void>()}}

describe("internal registration",()=>{
  it("normalizes a successful registration and creates the tenant membership with the least-privileged role",async()=>{const deps=dependencies();expect(await registerInternalAccount(valid,configuration,deps,attemptId)).toEqual({ok:true});expect(deps.createAccount).toHaveBeenCalledWith(expect.objectContaining({name:"Amina Rahman",email:"amina@example.com",organizationSlug:"nefe-internal-testing",role:INTERNAL_REGISTRATION_ROLE,passwordHash:"secure-hash"}))});
  it("classifies an invalid invitation and returns its attempt reference",async()=>{const deps=dependencies();const result=await registerInternalAccount({...valid,invitationCode:"incorrect-invitation"},configuration,deps,attemptId);expect(result).toEqual({ok:false,error:`${GENERIC_REGISTRATION_ERROR} Reference: ${attemptId}`});expect(deps.reportFailure).toHaveBeenCalledWith(expect.objectContaining({attemptId,stage:"invitation_validation",reason:"invalid_invitation",postgresCode:null,constraint:null}));expect(deps.createAccount).not.toHaveBeenCalled()});
  it("classifies a duplicate email without enumerating the account",async()=>{const deps=dependencies(vi.fn(async()=>{throw new RegistrationDiagnosticError("duplicate_check","duplicate_email","23505","users_email_uq")}));expect(await registerInternalAccount(valid,configuration,deps,attemptId)).toEqual({ok:false,error:`${GENERIC_REGISTRATION_ERROR} Reference: ${attemptId}`});expect(deps.reportFailure).toHaveBeenCalledWith(expect.objectContaining({stage:"duplicate_check",reason:"duplicate_email",postgresCode:"23505",constraint:"users_email_uq"}))});
  it("classifies a database transaction failure",async()=>{const deps=dependencies(vi.fn(async()=>{throw new RegistrationDiagnosticError("transaction_commit","database_error","40001")}));await registerInternalAccount(valid,configuration,deps,attemptId);expect(deps.reportFailure).toHaveBeenCalledWith(expect.objectContaining({stage:"transaction_commit",reason:"database_error",postgresCode:"40001"}))});
  it("never includes sensitive submitted values in serialized diagnostics",async()=>{const diagnostics:RegistrationDiagnostic[]=[];const deps={...dependencies(),reportFailure:(value:RegistrationDiagnostic)=>diagnostics.push(value)};await registerInternalAccount({...valid,invitationCode:"incorrect-invitation"},configuration,deps,attemptId);const logged=JSON.stringify(diagnostics);for(const sensitive of [valid.fullName,valid.email.trim(),valid.password,"incorrect-invitation",configuration.invitationCode])expect(logged).not.toContain(sensitive)});
  it("reports a password mismatch at the field",async()=>{const result=await registerInternalAccount({...valid,confirmPassword:"different-password"},configuration,dependencies(),attemptId);expect(result.ok).toBe(false);if(!result.ok)expect(result.fieldErrors?.confirmPassword).toBe("Passwords do not match.")});
  it("rejects a weak password before hashing",async()=>{const deps=dependencies();const result=await registerInternalAccount({...valid,password:"weak",confirmPassword:"weak"},configuration,deps,attemptId);expect(result.ok).toBe(false);expect(deps.hashPassword).not.toHaveBeenCalled()});
  it("cannot accept a client-selected organization or role",async()=>{const deps=dependencies();await registerInternalAccount({...valid,organizationSlug:"attacker-org",organizationId:"attacker-id",role:"OWNER"},configuration,deps,attemptId);expect(deps.createAccount).toHaveBeenCalledWith(expect.objectContaining({organizationSlug:configuration.organizationSlug,role:"VIEWER"}))});
  it("reports a missing organization safely before returning unavailable",async()=>{const deps=dependencies(vi.fn(async()=>{throw new RegistrationUnavailableError()}));expect(await registerInternalAccount(valid,configuration,deps,attemptId)).toEqual({ok:false,error:"Registration is currently unavailable."});expect(deps.reportFailure).toHaveBeenCalledWith(expect.objectContaining({stage:"organization_lookup",reason:"configuration_error"}));expect(deps.reportAvailability).toHaveBeenCalledWith({attemptId,reason:"organization_not_found",signupCodeConfigured:true,organizationSlugConfigured:true,organizationFound:false})});
  it("reports which registration configuration is absent without logging values",async()=>{const deps=dependencies();expect(await registerInternalAccount(valid,{organizationSlug:configuration.organizationSlug},deps,attemptId)).toEqual({ok:false,error:"Registration is currently unavailable."});expect(deps.reportAvailability).toHaveBeenCalledWith({attemptId,reason:"registration_configuration_missing",signupCodeConfigured:false,organizationSlugConfigured:true,organizationFound:false})});
  it("does not report success when the atomic persistence operation rolls back",async()=>{const committed:AtomicRegistration[]=[];const deps=dependencies(vi.fn(async input=>{const staged=[input];expect(staged).toHaveLength(1);throw new RegistrationDiagnosticError("audit_insert","database_error","42501")}));expect(await registerInternalAccount(valid,configuration,deps,attemptId)).toEqual({ok:false,error:`${GENERIC_REGISTRATION_ERROR} Reference: ${attemptId}`});expect(committed).toEqual([])});
});
