import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {deriveOpportunityHealth,opportunityStageLabel} from "../app/lib/opportunity/opportunity-policy";
import {activityEvent} from "../app/lib/collaboration/domain-events";

const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("opportunity commercial presentation policy",()=>{
  it("labels deterministic health without presenting it as stored history",()=>{expect(deriveOpportunityHealth({confidence:88,stage:"APPROVED",recommendationCount:1})).toBe("Strong");expect(deriveOpportunityHealth({confidence:72,stage:"QUALIFIED",recommendationCount:1})).toBe("Developing");expect(deriveOpportunityHealth({confidence:55,stage:"ACTIVE",recommendationCount:3})).toBe("Needs attention");expect(opportunityStageLabel("PENDING_APPROVAL")).toBe("Pending Approval")});
  it("supports deterministic opportunity update activity",()=>{expect(activityEvent("opportunity.updated","opportunity","00000000-0000-4000-8000-000000000001",{component:"profile"})).toEqual({eventType:"opportunity.updated",entityType:"opportunity",entityId:"00000000-0000-4000-8000-000000000001",summary:"Opportunity updated",metadata:{component:"profile"}})});
});

describe("opportunities workspace product maturity",()=>{const list=read("app/(workspace)/workspace/opportunities/opportunities-workspace.tsx"),page=read("app/(workspace)/workspace/opportunities/page.tsx"),detail=read("app/(workspace)/workspace/opportunities/[id]/page.tsx"),editor=read("app/(workspace)/workspace/opportunities/[id]/opportunity-profile-editor.tsx"),repository=read("app/lib/data/opportunity-repository.ts"),actions=read("app/lib/actions/opportunity-actions.ts"),styles=read("app/(workspace)/workspace/workspace.css");
  it("renders a searchable, filterable, sortable opportunity pipeline with commercial context",()=>{for(const value of ["recommendationSummary","commercialHealth","lastActivity","participants","modeledValue","owner","Open Workspace"])expect(list).toContain(value);expect(list).toContain('aria-label="Sort opportunities"');expect(list).toContain("ws-card-link")});
  it("shows pipeline counts, totals, movement feedback, and empty stages",()=>{expect(list).toContain("PipelineSummary");expect(list).toContain("reduce((sum,item)=>sum+item.modeledValue,0)");expect(list).toContain("Saving stage…");expect(list).toContain("Stage saved");expect(list).toContain("No opportunities at this stage")});
  it("uses opportunity-specific bounded server reads instead of the workspace graph",()=>{expect(page).toContain("listOpportunitySummaries");expect(detail).toContain("getOpportunityDetail");expect(page).not.toContain("getWorkspaceData");expect(detail).not.toContain("getWorkspaceData");expect(repository).toContain(".limit(50)");expect(repository).toContain(".limit(100)")});
  it("tenant scopes opportunity, participant, recommendation, pilot, decision, and activity reads",()=>{expect(repository.match(/eq\([^,]+\.organizationId,organizationId\)/g)?.length).toBeGreaterThan(15);expect(repository).toContain('eq(collaborationActivityEvents.entityType,"opportunity")');expect(repository).toContain('eq(executiveDecisions.entityType,"opportunity")')});
  it("enforces editing permission, tenant ownership, and optimistic concurrency",()=>{expect(actions).toContain('requirePermission(context.membership.role,"opportunity.update")');expect(actions).toContain("expectedUpdatedAt");expect(actions).toContain("STALE_OPPORTUNITY");expect(actions).toContain("eq(opportunities.organizationId,context.organization.id)");expect(actions).toContain("eq(organizationMembers.status,\"ACTIVE\")")});
  it("persists profile, participants, stage history, audit, and activity atomically",()=>{const creates=read("app/lib/actions/workspace-create-actions.ts");expect(actions).toContain("database().transaction");expect(actions).toContain("tx.delete(opportunityParticipants)");expect(actions).toContain("tx.insert(opportunityParticipants)");expect(actions).toContain("tx.insert(opportunityStatusHistory)");expect(actions).toContain("tx.insert(auditLogs)");expect(actions).toContain("tx.insert(collaborationActivityEvents)");const opportunityCreate=creates.slice(creates.indexOf("export async function createOpportunityV2"),creates.indexOf("export async function createCampaignV2"));expect(opportunityCreate).toContain("db.transaction");expect(opportunityCreate).toContain("tx.insert(auditLogs)");expect(opportunityCreate).toContain("tx.insert(collaborationActivityEvents)")});
  it("keeps the requested detail hierarchy and explicit empty states",()=>{const markers=['title="Executive Summary"','title="Pipeline Status"','title="Business Context"','title="Commercial Value"','title="Participants"','title="Recommendations"','<EntityCollaboration','title="Related Campaigns"','title="Related Journeys"','title="Related Pilots"','<EntityDecisions','title="Activity Timeline"'];let cursor=-1;for(const marker of markers){const next=detail.indexOf(marker,cursor+1);expect(next).toBeGreaterThan(cursor);cursor=next}expect(detail).toContain("EmptyState")});
  it("distinguishes recorded data from deterministic derived insight",()=>{expect(detail).toContain('title="Recorded Data"');expect(detail).toContain('title="Derived Insight"');for(const value of ["Compatibility","Readiness","Opportunity score","Confidence","Key reasons","Limitations"])expect(detail).toContain(value)});
  it("uses persisted relationship routes for businesses, campaigns, journeys, pilots, and decisions",()=>{for(const route of ["/workspace/businesses/","/workspace/campaigns/","/workspace/journeys/","/workspace/pilots/"])expect(detail).toContain(route);expect(repository).toContain("eq(pilots.opportunityId,id)");expect(repository).toContain("campaignId:pilots.campaignId");expect(repository).toContain("journeyId:pilots.journeyId")});
  it("does not expose unsupported expected-date fields",()=>{for(const field of ["expectedCloseDate","expectedDecisionDate","closeDate"])expect(editor).not.toContain(`name=\"${field}\"`)});
  it("provides compact mobile pipeline, editor, intelligence, and participant layouts",()=>{expect(styles).toContain(".ws-opportunity-stage-summary{grid-template-columns:repeat(2");expect(styles).toContain(".ws-opportunity-intelligence{grid-template-columns:1fr}");expect(styles).toContain(".ws-opportunity-edit-form{position:fixed");expect(styles).toContain(".ws-opportunity-participants{display:grid}")});
});
