import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {can} from "../app/lib/auth/permissions";

const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8"),dialog=read("app/(workspace)/workspace/_components/entity-create-dialog.tsx"),styles=read("app/(workspace)/workspace/workspace.css"),creates=read("app/lib/actions/workspace-create-actions.ts"),shell=read("app/(workspace)/workspace/_components/app-shell.tsx"),report=read("app/(workspace)/workspace/analytics/export/route.ts");

describe("permission-aware creation",()=>{it("keeps journey presentation aligned with server authorization",()=>{expect(can("VIEWER","business.manage")).toBe(false);expect(can("CONTRIBUTOR","business.manage")).toBe(true);expect(creates).toContain('requirePermission(context.membership.role,"business.manage")');expect(read("app/(workspace)/workspace/journeys/page.tsx")).toContain('allowed={can(context.membership.role,"business.manage")}')});it("passes authenticated server permissions directly to every shared creation control",()=>{expect(dialog).toContain("allowed:boolean");expect(dialog).not.toContain("useCreationPermissions");expect(read("app/(workspace)/workspace/businesses/page.tsx")).toContain('can(context.membership.role,"business.manage")');expect(read("app/(workspace)/workspace/opportunities/page.tsx")).toContain('can(context.membership.role,"opportunity.update")');expect(read("app/(workspace)/workspace/campaigns/page.tsx")).toContain('allowed={can(context.membership.role,"business.manage")}');expect(read("app/(workspace)/workspace/pilots/page.tsx")).toContain('can(context.membership.role,"pilot.create")')});it("keeps pilot route protected server-side",()=>{expect(read("app/(workspace)/workspace/pilots/new/page.tsx")).toContain('can(context.membership.role,"pilot.create")')})});
describe("creation form behavior",()=>{it("renders authorized shared actions as purple buttons wired to the native dialog",()=>{expect(dialog).toContain('<button className="ws-button primary" type="button" onClick={open}>');expect(dialog).toContain("dialog.current?.showModal()")});it("keeps decision creation directly server-authorized",()=>{const decisions=read("app/(workspace)/workspace/_components/entity-decisions.tsx"),form=read("app/(workspace)/workspace/_components/decision-draft-form.tsx");expect(decisions).toContain('can(context.membership.role,"decision.create")');expect(form).toContain('className="ws-button primary" type="button"')});it("uses dependent UAE geography options and bounded descriptions",()=>{expect(dialog).toContain("Ras Al Khaimah");expect(dialog).toContain('country==="United Arab Emirates"');expect(dialog).toContain("maxLength={600}")});it("implements campaign step navigation and duplicate submission guards",()=>{expect(dialog).toContain("setCampaignStep");expect(dialog).toContain('disabled={pending}');expect(dialog).toContain('pending?"Creating…"')});it("validates tenant-owned connected records and duplicate business names",()=>{expect(creates).toContain("validateBusinesses");expect(creates).toContain("DUPLICATE_BUSINESS")})});
describe("workspace navigation",()=>{it("uses an authorized server-side workspace switch",()=>{expect(shell).toContain("switchWorkspace(item.id)");expect(shell).toContain("aria-current");expect(read("app/lib/actions/workspace-switch.ts")).toContain("available.some")})});
describe("analytics export",()=>{it("requires analytics permission and scopes every decision query to the active tenant",()=>{expect(report).toContain('requirePermission(context.membership.role,"analytics.view")');expect(report).toContain("eq(executiveDecisions.organizationId,context.organization.id)");expect(report).toContain('Content-Type":"text/csv')})});
describe("RC3.2 rendering stability",()=>{it("keeps primary page actions above card overlays",()=>{expect(styles).toContain(".ws-page-action{position:relative;z-index:4");expect(styles).toContain(".ws-page-action .ws-button{pointer-events:auto}")});it("keeps route recovery without replacing the current page with a short loading subtree",()=>{expect(read("app/(workspace)/workspace/error.tsx")).toContain("reset")});it("uses a Safari-compatible attached download link",()=>{expect(read("app/(workspace)/workspace/analytics/export-report-button.tsx")).toContain("document.body.append(anchor)");expect(read("app/(workspace)/workspace/analytics/export-report-button.tsx")).toContain("setTimeout(()=>URL.revokeObjectURL")})});
