import {readFileSync} from "node:fs";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import {can} from "../app/lib/auth/permissions";

const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8"),dialog=read("app/(workspace)/workspace/_components/entity-create-dialog.tsx"),styles=read("app/(workspace)/workspace/workspace.css"),creates=read("app/lib/actions/workspace-create-actions.ts"),shell=read("app/(workspace)/workspace/_components/app-shell.tsx"),report=read("app/(workspace)/workspace/analytics/export/route.ts");
const scrollLock=read("app/(workspace)/workspace/_components/use-body-scroll-lock.ts");

describe("permission-aware creation",()=>{it("keeps journey presentation aligned with server authorization",()=>{expect(can("VIEWER","business.manage")).toBe(false);expect(can("CONTRIBUTOR","business.manage")).toBe(true);expect(creates).toContain('requirePermission(context.membership.role,"business.manage")');expect(dialog).toContain("permissions[kind]")});it("keeps pilot route protected server-side",()=>{expect(read("app/(workspace)/workspace/pilots/new/page.tsx")).toContain('can(context.membership.role,"pilot.create")')})});
describe("creation form behavior",()=>{it("uses dependent UAE geography options and bounded descriptions",()=>{expect(dialog).toContain("Ras Al Khaimah");expect(dialog).toContain('country==="United Arab Emirates"');expect(dialog).toContain("maxLength={600}")});it("implements campaign step navigation and duplicate submission guards",()=>{expect(dialog).toContain("setCampaignStep");expect(dialog).toContain('disabled={pending}');expect(dialog).toContain('pending?"Creating…"')});it("validates tenant-owned connected records and duplicate business names",()=>{expect(creates).toContain("validateBusinesses");expect(creates).toContain("DUPLICATE_BUSINESS")})});
describe("modal and mobile navigation",()=>{it("locks background scroll explicitly and contains modal scrolling",()=>{expect(dialog).toContain("useBodyScrollLock(isOpen)");expect(dialog).not.toContain("MutationObserver");expect(styles).toContain("overscroll-behavior:contain");expect(styles).toContain("body.ws-scroll-locked{position:fixed")});it("keeps the sidebar independently scrollable with safe areas",()=>{expect(styles).toContain("height:100dvh");expect(styles).toContain("env(safe-area-inset-bottom)");expect(styles).toContain("overflow-y:auto")});it("uses an authorized server-side workspace switch",()=>{expect(shell).toContain("switchWorkspace(item.id)");expect(shell).toContain("aria-current");expect(read("app/lib/actions/workspace-switch.ts")).toContain("available.some")})});
describe("analytics export",()=>{it("requires analytics permission and scopes every decision query to the active tenant",()=>{expect(report).toContain('requirePermission(context.membership.role,"analytics.view")');expect(report).toContain("eq(executiveDecisions.organizationId,context.organization.id)");expect(report).toContain('Content-Type":"text/csv')})});
describe("RC3.2 rendering stability",()=>{it("reference-counts scroll locks and always restores the page position",()=>{expect(scrollLock).toContain("if(locks++>0)return");expect(scrollLock).toContain("if(locks===0||--locks>0)return");expect(scrollLock).toContain("window.scrollTo")});it("keeps primary page actions above card overlays",()=>{expect(styles).toContain(".ws-page-action{position:relative;z-index:4");expect(styles).toContain(".ws-page-action .ws-button{pointer-events:auto}")});it("provides route-level loading and recovery boundaries",()=>{expect(read("app/(workspace)/workspace/loading.tsx")).toContain('role="status"');expect(read("app/(workspace)/workspace/error.tsx")).toContain("reset")});it("uses stable dynamic viewport and isolated drawer scrolling",()=>{expect(styles).toContain("height:100svh;height:100dvh");expect(styles).toContain("-webkit-overflow-scrolling:touch");expect(shell).toContain("useBodyScrollLock(open)")});it("uses a Safari-compatible attached download link",()=>{expect(read("app/(workspace)/workspace/analytics/export-report-button.tsx")).toContain("document.body.append(anchor)");expect(read("app/(workspace)/workspace/analytics/export-report-button.tsx")).toContain("setTimeout(()=>URL.revokeObjectURL")})});
