"use client";

import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { merchantSlug } from "../merchants/merchant-data";
import UAEFlag from "../components/uae-flag";

type Priority="Very High"|"High"|"Medium";
export type Business={name:string;category:string;city:string;location:string;fit:number;nearby:number;bundle:string;referrals:number;priority:Priority;opportunity:string;value:number;x:number;y:number;lat:number;lng:number;initials:string;outreach:string;meeting:string;ceo:boolean};
export type MapFocus={center:[number,number];zoom:number;key:number;home?:boolean};
const LeafletMap=dynamic(()=>import("./leaflet-map"),{ssr:false,loading:()=> <div className="grid h-[680px] place-items-center bg-[#DDE8E5]"><span className="text-[9px] font-semibold text-[#5E3BEE]">Loading live UAE map…</span></div>});

const bundles:Record<string,string>={
  Hotels:"Premium Stay + Curated City Access",Restaurants:"Dining + Event Access","Luxury Dining":"Chef's Table + Chauffeured Arrival","Beach Clubs":"Beach Day + Wellness Ritual","Car Rentals":"Luxury Drive + Hotel Stay",Spas:"Spa Ritual + Premium Stay",Retail:"Private Shopping + Member Rewards",Healthcare:"Executive Health + Recovery Stay",Events:"Premium Event + Dining", "Real Estate":"Resident Welcome Collection","Luxury Experiences":"Bespoke UAE Weekend"
};
const opportunityType:Record<string,string>={
  Hotels:"Premium bundle",Restaurants:"Customer referral","Luxury Dining":"Premium bundle","Beach Clubs":"Lifestyle package","Car Rentals":"Premium bundle",Spas:"Wellness package",Retail:"Member reward",Healthcare:"Customer referral",Events:"Event package","Real Estate":"Resident benefit","Luxury Experiences":"Premium bundle"
};
const raw:[string,string,string,string,number,number,number,number,boolean?][]=[
  ["One&Only One Za'abeel","Hotels","Dubai","One Za'abeel",48,43,97,285],["The Lana","Hotels","Dubai","Business Bay",53,55,95,264],["Atlantis The Royal","Hotels","Dubai","Palm Jumeirah",25,58,96,306],["Bulgari Resort Dubai","Hotels","Dubai","Jumeirah Bay",36,46,94,238],["Address Beach Resort","Hotels","Dubai","Dubai Marina",31,66,92,214],["Emirates Palace Mandarin Oriental","Hotels","Abu Dhabi","West Corniche",18,30,94,210],["W Abu Dhabi","Hotels","Abu Dhabi","Yas Island",29,27,89,164],["The Chedi Al Bait","Hotels","Sharjah","Heart of Sharjah",69,35,84,92],["Waldorf Astoria RAK","Hotels","Ras Al Khaimah","Al Hamra",84,16,88,146],
  ["Trèsind Studio","Luxury Dining","Dubai","Palm Jumeirah",27,61,96,242],["Ossiano","Luxury Dining","Dubai","Palm Jumeirah",22,56,95,226],["Il Ristorante - Niko Romito","Luxury Dining","Dubai","Jumeirah Bay",37,45,93,194],["Zuma Dubai","Restaurants","Dubai","DIFC",49,47,92,218],["Orfali Bros Bistro","Restaurants","Dubai","Jumeirah",41,53,90,178],["Hakkasan Abu Dhabi","Luxury Dining","Abu Dhabi","Emirates Palace",18,33,91,186],
  ["Nammos Dubai","Beach Clubs","Dubai","Jumeirah",36,50,93,198],["Azure Beach","Beach Clubs","Dubai","JBR",29,68,91,184],["WHITE Beach","Beach Clubs","Dubai","Palm Jumeirah",23,57,92,206],["Saadiyat Beach Club","Beach Clubs","Abu Dhabi","Saadiyat Island",25,34,89,158],
  ["VIP Rent A Car","Car Rentals","Dubai","Business Bay",54,58,94,316],["Uptown Rent A Car","Car Rentals","Dubai","Dubai Marina",32,64,90,232],["Paddock Luxury","Car Rentals","Dubai","Al Quoz",48,62,88,196],["Superior Car Rental","Car Rentals","Abu Dhabi","Al Bateen",17,36,86,142],
  ["Talise Ottoman Spa","Spas","Dubai","Palm Jumeirah",24,63,91,174],["Dior Spa The Lana","Spas","Dubai","Business Bay",52,54,94,208],["Armani/SPA","Spas","Dubai","Downtown Dubai",55,49,92,186],["Anantara Spa","Spas","Abu Dhabi","Eastern Mangroves",23,28,87,138],
  ["Level Shoes Private","Retail","Dubai","Dubai Mall",56,51,89,156],["Lumé Joaillerie","Retail","Dubai","DIFC",50,46,91,172],["The Edit Dubai","Retail","Dubai","Dubai Marina",33,62,86,126],["Tryano","Retail","Abu Dhabi","Yas Mall",30,29,85,118],
  ["King's College Hospital","Healthcare","Dubai","Dubai Hills",61,66,86,118],["American Hospital Dubai","Healthcare","Dubai","Oud Metha",59,42,88,136],["Healthpoint","Healthcare","Abu Dhabi","Zayed Sports City",21,39,84,104],
  ["Coca-Cola Arena","Events","Dubai","City Walk",47,50,92,228],["The Foundry","Events","Dubai","Al Quoz",45,61,88,164],["Yas Marina Circuit","Events","Abu Dhabi","Yas Island",31,26,90,186],["Aljada Events District","Events","Sharjah","Aljada",72,33,83,96],
  ["OMNIYAT Residences","Real Estate","Dubai","Downtown Dubai",57,48,88,132],["Muraba Residences","Real Estate","Dubai","Palm Jumeirah",26,60,87,126],["Aldar Experience Centre","Real Estate","Abu Dhabi","Yas Island",29,31,89,148],
  ["The Lana Concierge","Luxury Experiences","Dubai","Business Bay",54,56,95,264],["Hero Balloon Flights","Luxury Experiences","Dubai","Dubai Desert",70,72,89,172],["Platinum Heritage","Luxury Experiences","Dubai","Dubai Desert",74,68,91,188],["Xclusive Yachts","Luxury Experiences","Dubai","Dubai Marina",30,65,93,216],
  ["RAK Resort Development","Real Estate","Ras Al Khaimah","Al Marjan Island",85,18,99,338,true],["F10 Car Rental","Car Rentals","Ras Al Khaimah","Al Hamra",82,22,98,294,true],["RAK Hotel Partner","Hotels","Ras Al Khaimah","Al Marjan Island",87,20,99,326,true],
];
const initials=(name:string)=>name.split(/[\s&-]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const areaCoordinates:Record<string,[number,number]>={
  "One Za'abeel":[25.2282,55.2896],"Business Bay":[25.1850,55.2710],"Palm Jumeirah":[25.1124,55.1390],"Jumeirah Bay":[25.2157,55.2370],"Dubai Marina":[25.0805,55.1403],"West Corniche":[24.4615,54.3175],"Yas Island":[24.4955,54.6075],"Heart of Sharjah":[25.3575,55.3820],"Al Hamra":[25.6965,55.7770],"DIFC":[25.2116,55.2796],"Jumeirah":[25.2048,55.2400],"JBR":[25.0780,55.1330],"Al Quoz":[25.1440,55.2240],"Downtown Dubai":[25.1972,55.2744],"Dubai Mall":[25.1985,55.2796],"Dubai Hills":[25.1135,55.2520],"Oud Metha":[25.2334,55.3135],"City Walk":[25.2075,55.2623],"Al Marjan Island":[25.7038,55.7942],"Al Bateen":[24.4539,54.3406],"Saadiyat Island":[24.5430,54.4350],"Emirates Palace":[24.4612,54.3170],"Eastern Mangroves":[24.4480,54.4370],"Yas Mall":[24.4889,54.6087],"Zayed Sports City":[24.4150,54.4530],"Aljada":[25.3163,55.4950],"Dubai Desert":[24.9480,55.6050],
};
const businesses:Business[]=raw.map(([name,category,city,location,x,y,fit,referrals,ceo=false],i)=>({
  name,category,city,location,x,y,fit,referrals,ceo,initials:initials(name),lat:(areaCoordinates[location]??[city==="Dubai"?25.2048:city==="Abu Dhabi"?24.4539:city==="Sharjah"?25.3463:25.7038,city==="Dubai"?55.2708:city==="Abu Dhabi"?54.3773:city==="Sharjah"?55.4209:55.7942])[0]+(i%3-.8)*.0015,lng:(areaCoordinates[location]??[25,55])[1]+(i%4-1.5)*.0015,nearby:ceo?8:6+(i*7)%18,bundle:ceo?"RAK Stay + Car Rental + Resort Experience":bundles[category],opportunity:opportunityType[category],priority:ceo?"Very High":fit>=89?"High":"Medium",value:ceo?Math.round((referrals*920)/1000)*1000:Math.round((referrals*(540+(i%5)*85))/1000)*1000,
  outreach:ceo?"Use the CEO network connection for a private pilot-cluster introduction and commercial workshop.":fit>=93?"Founder-led introduction with a tailored commercial opportunity brief.":"Invite the commercial lead to a focused 30-minute partnership discovery session.",
  meeting:ceo?"CEO + Development Director + Commercial Lead":fit>=92?"Commercial Director + Guest Experience Lead":"Partnerships or Marketing Director"
}));
const sectors=["All industries",...Object.keys(bundles)];
const cities=["All cities","Dubai","Abu Dhabi","Sharjah","Ras Al Khaimah"];
const opportunities=["All opportunities",...Array.from(new Set(Object.values(opportunityType)))];
const clusters=[
  {name:"Dubai Marina",x:31,y:65,zoom:1.75},{name:"Downtown Dubai",x:55,y:49,zoom:1.8},{name:"Palm Jumeirah",x:25,y:59,zoom:1.85},{name:"Business Bay",x:53,y:56,zoom:1.9},{name:"Jumeirah Beach",x:37,y:51,zoom:1.75},{name:"Abu Dhabi",x:23,y:31,zoom:1.55},{name:"Sharjah",x:70,y:34,zoom:1.65},{name:"Ras Al Khaimah",x:85,y:19,zoom:2.05},
];
const clusterCoordinates:Record<string,{center:[number,number];zoom:number}>={"Dubai Marina":{center:[25.0805,55.1403],zoom:13},"Downtown Dubai":{center:[25.1972,55.2744],zoom:14},"Palm Jumeirah":{center:[25.1124,55.1390],zoom:13},"Business Bay":{center:[25.1850,55.2710],zoom:14},"Jumeirah Beach":{center:[25.2048,55.2400],zoom:13},"Abu Dhabi":{center:[24.4539,54.3773],zoom:11},"Sharjah":{center:[25.3463,55.4209],zoom:12},"Ras Al Khaimah":{center:[25.7000,55.7900],zoom:13}};
const feedTemplates=["New high-fit hotel opportunity detected","Referral corridor identified in Business Bay","Premium bundle recommendation generated","Three compatible partners found near Dubai Marina","New luxury experience added to scan"];

export default function OpportunityMap(){
  const [sector,setSector]=useState("All industries"),[city,setCity]=useState("All cities"),[minFit,setMinFit]=useState(80),[priority,setPriority]=useState("All priorities"),[opportunity,setOpportunity]=useState("All opportunities"),[ceoOnly,setCeoOnly]=useState(false);
  const [selected,setSelected]=useState<Business>(businesses[0]),[,setHovered]=useState<Business|null>(null),[pipeline,setPipeline]=useState<Business[]>(businesses.filter(x=>x.priority==="High").slice(0,5));
  const [mapFocus,setMapFocus]=useState<MapFocus>({center:[24.55,54.9],zoom:7,key:0,home:true}),[currentZoom,setCurrentZoom]=useState(7),[toast,setToast]=useState(""),[scan,setScan]=useState(68),[feed,setFeed]=useState<string[]>(feedTemplates.slice(0,3));
  const filtered=useMemo(()=>businesses.filter(b=>(!ceoOnly||b.ceo)&&(sector==="All industries"||b.category===sector)&&(city==="All cities"||b.city===city)&&b.fit>=minFit&&(priority==="All priorities"||b.priority===priority)&&(opportunity==="All opportunities"||b.opportunity===opportunity)),[sector,city,minFit,priority,opportunity,ceoOnly]);
  const matches=useMemo(()=>businesses.filter(b=>b.name!==selected.name&&(b.city===selected.city||b.category===selected.category)).sort((a,b)=>b.fit-a.fit).slice(0,4),[selected]);
  useEffect(()=>{const kickoff=window.setTimeout(()=>setScan(Math.min(22,filtered.length)),0);const a=window.setInterval(()=>setScan(v=>Math.min(filtered.length,v+2)),55);const b=window.setInterval(()=>setFeed(items=>[feedTemplates[Math.floor(Math.random()*feedTemplates.length)],...items.slice(0,3)]),4200);return()=>{clearTimeout(kickoff);clearInterval(a);clearInterval(b)}},[filtered.length]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const focusCluster=(c:typeof clusters[number])=>{const target=clusterCoordinates[c.name];setMapFocus({center:target.center,zoom:target.zoom,key:Date.now()});if(c.name==="Ras Al Khaimah")setCity("Ras Al Khaimah");notify(`${c.name} cluster focused`)};
  const addLead=(b:Business)=>{if(!pipeline.some(x=>x.name===b.name))setPipeline(x=>[b,...x]);notify(`${b.name} added to Partner Pipeline`)};
  const reset=()=>{setSector("All industries");setCity("All cities");setPriority("All priorities");setOpportunity("All opportunities");setMinFit(80);setCeoOnly(false);setMapFocus({center:[24.55,54.9],zoom:7,key:Date.now(),home:true})};

  return <main className="opportunity-map-page min-h-screen bg-[#F5F3F7] text-[#19152A]"><div className="mx-auto max-w-[1780px] px-4 py-7 sm:px-7 lg:px-9">
    <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex w-fit items-center gap-2 rounded-full border border-[#DDD3F8] bg-white px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#5E3BEE]"><span className="relative flex h-2 w-2"><i className="absolute h-full w-full animate-ping rounded-full bg-[#4EBE91] opacity-40"/><i className="relative h-2 w-2 rounded-full bg-[#4EBE91]"/></span>Live scan active</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] sm:text-[40px]">UAE Opportunity Map</h1><p className="mt-2 inline-flex items-center gap-2 text-[10px] text-[#817A87]"><UAEFlag className="h-4 w-auto" title="United Arab Emirates flag"/>Verified UAE Commercial Opportunities</p></div><div className="flex flex-wrap justify-end gap-2"><Link href="/opportunity-engine" className="flex items-center rounded-xl bg-[#5E3BEE] px-4 py-3 text-[7px] font-bold text-white shadow-[0_8px_22px_rgba(94,59,238,.2)]">Open Opportunity Engine →</Link>{[["Scanned",`${scan}/${filtered.length}`],["Opportunities",filtered.length.toString()],["Monthly value",`AED ${(filtered.reduce((s,b)=>s+b.value,0)/1e6).toFixed(1)}M`]].map(([l,v])=><div key={l} className="rounded-xl border border-[#E3DEE7] bg-white px-4 py-3"><p className="text-[6px] uppercase text-[#9D96A2]">{l}</p><p className="mt-1 text-sm font-bold">{v}</p></div>)}</div></div>

    <section className="mt-5 rounded-[20px] border border-[#E4DFE8] bg-white p-3"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_1fr_1.2fr_auto]">{[[sector,setSector,sectors,"Industry"],[city,setCity,cities,"City"],[priority,setPriority,["All priorities","Very High","High","Medium"],"Priority"],[opportunity,setOpportunity,opportunities,"Opportunity"]].map(([value,setter,items,label])=><label key={label as string} className="opportunity-filter"><span>{label as string}</span><select value={value as string} onChange={e=>(setter as React.Dispatch<React.SetStateAction<string>>)(e.target.value)}>{(items as string[]).map(x=><option key={x}>{x}</option>)}</select></label>)}<label className="px-3 py-2"><span className="flex justify-between text-[7px] font-bold uppercase text-[#8F8895]">Minimum fit <b className="text-[#5E3BEE]">{minFit}%</b></span><input type="range" min="80" max="99" value={minFit} onChange={e=>setMinFit(Number(e.target.value))} className="roi-slider mt-3 w-full"/></label><button onClick={reset} className="rounded-xl bg-[#F1EDFF] px-4 text-[8px] font-semibold text-[#5E3BEE]">Reset</button></div></section>

    <div className="no-scrollbar mt-3 flex gap-2 overflow-x-auto"><button onClick={()=>{if(ceoOnly){setCeoOnly(false);setCity("All cities");setMapFocus({center:[24.55,54.9],zoom:7,key:Date.now(),home:true})}else{setCeoOnly(true);focusCluster(clusters.find(x=>x.name==="Ras Al Khaimah")!)}}} className={`shrink-0 rounded-full border px-3 py-2 text-[7px] font-bold transition ${ceoOnly?"border-[#C6983E] bg-[#FFF4D9] text-[#946B1C]":"border-[#D8C58F] bg-white text-[#9B7428]"}`}>★ CEO Network</button>{clusters.map(c=><button key={c.name} onClick={()=>focusCluster(c)} className="shrink-0 rounded-full border border-[#E0DAE5] bg-white px-3 py-2 text-[7px] font-semibold text-[#625B69] transition hover:border-[#BFAFF2] hover:text-[#5E3BEE]">◎ {c.name}</button>)}</div>

    <div className="mt-3 grid gap-4 xl:grid-cols-[1fr_380px]"><div className="min-w-0">
      <section className="relative overflow-hidden rounded-[25px] border border-[#DCD6E3] shadow-[0_20px_55px_rgba(42,31,64,.1)]">
        <div className="pointer-events-none absolute left-4 top-4 z-[1000] rounded-xl border border-white/60 bg-white/85 px-3 py-2 text-[7px] font-semibold text-[#5E3BEE] shadow-sm backdrop-blur">
          Live UAE intelligence · Zoom {currentZoom}
        </div>
        <LeafletMap businesses={filtered} selected={selected} focus={mapFocus} onSelect={setSelected} onHover={setHovered} onZoom={setCurrentZoom}/>
      </section>
      <p className="mt-2 px-1 text-[6px] text-[#99929F]">Live map prototype using sample business intelligence data. Map data © OpenStreetMap contributors.</p>
      <div className="mt-3 rounded-[16px] border border-[#E0C982] bg-gradient-to-r from-[#FFF9E9] to-[#F5F0FF] p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-[#C2963E] to-[#6A47DC] text-white">★</span><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#8D6821]">CEO Network insight</p><p className="mt-1 text-[9px] font-semibold">CEO Network detected in Ras Al Khaimah: resort development, car rental, and hotel partnership can form NEFE’s first regional pilot cluster.</p></div><button onClick={()=>focusCluster(clusters.find(x=>x.name==="Ras Al Khaimah")!)} className="ml-auto shrink-0 rounded-lg bg-white px-3 py-2 text-[7px] font-semibold text-[#5E3BEE]">Focus cluster →</button></div></div>
      <div className="mt-3 grid gap-3 md:grid-cols-3">{feed.map((item,i)=><div key={`${item}-${i}`} className="admin-activity-new flex items-center gap-3 rounded-[15px] border border-[#E2DDE6] bg-white p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#F0ECFF] text-[#5E3BEE]">✦</span><div><p className="text-[7px] font-semibold">{item}</p><p className="mt-1 text-[6px] text-[#99929F]">{i===0?"Just now":`${i*2+1} min ago`}</p></div></div>)}</div>
    </div>

    <aside className="h-fit rounded-[24px] border border-[#E0DAE5] bg-[#171221] p-5 text-white shadow-[0_18px_50px_rgba(32,23,47,.18)] xl:sticky xl:top-24"><div className="flex items-start gap-3"><span className={`grid h-12 w-12 place-items-center rounded-[14px] bg-gradient-to-br text-[9px] font-bold ${selected.ceo?"from-[#C89A3E] to-[#6542DA] shadow-[0_0_22px_rgba(207,164,69,.25)]":"from-[#6542DC] to-[#B084D0]"}`}>{selected.initials}</span><div className="min-w-0 flex-1"><p className="text-[7px] font-bold uppercase tracking-[.14em] text-[#B49EF3]">Full Business Profile</p><h2 className="mt-1 truncate text-[15px] font-semibold">{selected.name}</h2><p className="mt-1 flex items-center gap-1.5 text-[7px] text-white/35"><UAEFlag className="h-3 w-auto"/>{selected.city} · {selected.location}</p><p className="mt-1 text-[7px] text-white/30">{selected.category}</p>{selected.ceo&&<span className="mt-2 inline-flex rounded-full bg-[#D1A344]/15 px-2 py-1 text-[6px] font-bold text-[#E2BD65]">★ CEO Network</span>}</div><span className="rounded-full bg-[#4BB88C]/15 px-2 py-1 text-[7px] font-bold text-[#5ACDA1]">{selected.fit}% fit</span></div>
      <div className="mt-5 grid grid-cols-2 gap-2">{[["Commercial score",`${selected.fit}/100`],["Monthly revenue",`AED ${selected.value.toLocaleString()}`],["Referrals",selected.referrals.toString()],["Nearby matches",selected.nearby.toString()]].map(([l,v])=><div key={l} className="rounded-xl bg-white/[.055] p-3"><p className="text-[6px] text-white/25">{l}</p><p className="mt-1 text-[11px] font-semibold">{v}</p></div>)}</div>
      <div className="mt-4 rounded-[14px] border border-[#7254CE]/25 bg-[#5E3BEE]/10 p-3"><p className="text-[6px] uppercase text-[#A992EA]">Suggested bundle</p><p className="mt-1 text-[9px] font-semibold">{selected.bundle}</p></div>
      <div className="mt-4"><p className="text-[7px] font-bold uppercase tracking-wider text-white/30">Nearby Partner Matches</p><div className="mt-2 space-y-2">{matches.map(m=><button key={m.name} onClick={()=>setSelected(m)} className="flex w-full items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.035] p-2.5 text-left"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#6745D8]/20 text-[6px] text-[#B7A3F2]">{m.initials}</span><span className="min-w-0 flex-1 truncate text-[7px]">{m.name}</span><b className="text-[7px] text-[#59C99D]">{m.fit}%</b></button>)}</div></div>
      <div className="mt-4 space-y-3 border-t border-white/[.08] pt-4">{selected.ceo&&<div className="rounded-xl border border-[#C99A3F]/20 bg-[#C99A3F]/10 p-3"><p className="text-[6px] uppercase text-[#D7B35D]">Suggested pilot use</p><p className="mt-1 text-[7px] leading-4 text-white/65">Anchor NEFE’s first Ras Al Khaimah regional pilot with a connected resort, hotel and mobility journey.</p><p className="mt-2 text-[6px] uppercase text-[#D7B35D]">Recommended next action</p><p className="mt-1 text-[7px] font-semibold">Schedule a CEO-sponsored pilot design workshop.</p></div>}<div><p className="text-[6px] uppercase text-white/25">Suggested outreach strategy</p><p className="mt-1 text-[7px] leading-4 text-white/55">{selected.outreach}</p></div><div><p className="text-[6px] uppercase text-white/25">Recommended first meeting</p><p className="mt-1 text-[8px] font-semibold text-[#D5B45F]">{selected.meeting}</p></div></div>
      <div className="mt-5 grid grid-cols-2 gap-2">{["Generate Outreach Plan","Create Partnership Bundle","Compare Nearby Businesses","View Commercial Analysis"].map(action=><button key={action} onClick={()=>notify(`${action} prepared for ${selected.name}`)} className="rounded-xl border border-white/10 bg-white/[.045] px-2 py-3 text-[7px] font-semibold text-white/65 transition hover:border-[#7658D1] hover:text-white">{action}</button>)}</div><button onClick={()=>addLead(selected)} className="mt-2 w-full rounded-xl bg-gradient-to-r from-[#6542DA] to-[#8562E8] py-3 text-[8px] font-semibold">Add to Partner Pipeline · {pipeline.length} leads</button>
      <Link href={`/merchants/${merchantSlug(selected.name)}`} className="mt-2 flex w-full items-center justify-center rounded-xl border border-[#D7B45D]/30 bg-[#D7B45D]/10 py-3 text-[8px] font-semibold text-[#E0BF6B] transition hover:bg-[#D7B45D]/20">View Full Profile →</Link>
    </aside></div></div>
    {toast&&<div className="prototype-toast fixed bottom-6 left-1/2 z-[100] -translate-x-1/2 rounded-xl bg-[#211A32]/95 px-4 py-3 text-[8px] font-semibold text-white shadow-2xl">✓ {toast}</div>}
  </main>;
}
