"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Priority="Very High"|"High"|"Medium";
type Business={name:string;category:string;city:string;location:string;fit:number;nearby:number;bundle:string;referrals:number;priority:Priority;opportunity:string;value:number;x:number;y:number;initials:string;outreach:string;meeting:string;ceo:boolean};

const bundles:Record<string,string>={
  Hotels:"Premium Stay + Curated City Access",Restaurants:"Dining + Event Access","Luxury Dining":"Chef's Table + Chauffeured Arrival","Beach Clubs":"Beach Day + Wellness Ritual","Car Rentals":"Luxury Drive + Hotel Stay",Spas:"Spa Ritual + Premium Stay",Retail:"Private Shopping + Member Rewards",Healthcare:"Executive Health + Recovery Stay",Events:"Premium Event + Dining", "Real Estate":"Resident Welcome Collection","Luxury Experiences":"Bespoke UAE Weekend"
};
const opportunityType:Record<string,string>={
  Hotels:"Premium bundle",Restaurants:"Customer referral","Luxury Dining":"Premium bundle","Beach Clubs":"Lifestyle package","Car Rentals":"Premium bundle",Spas:"Wellness package",Retail:"Member reward",Healthcare:"Customer referral",Events:"Event package","Real Estate":"Resident benefit","Luxury Experiences":"Premium bundle"
};
const raw:[string,string,string,string,number,number,number,number,boolean?][]=[
  ["One&Only One Za'abeel","Hotels","Dubai","One Za'abeel",48,43,97,285],["The Lana","Hotels","Dubai","Business Bay",53,55,95,264],["Atlantis The Royal","Hotels","Dubai","Palm Jumeirah",25,58,96,306],["Bulgari Resort Dubai","Hotels","Dubai","Jumeirah Bay",36,46,94,238],["Address Beach Resort","Hotels","Dubai","Dubai Marina",31,66,92,214],["Emirates Palace Mandarin Oriental","Hotels","Abu Dhabi","West Corniche",18,30,94,210],["W Abu Dhabi","Hotels","Abu Dhabi","Yas Island",29,27,89,164],["The Chedi Al Bait","Hotels","Sharjah","Heart of Sharjah",69,35,84,92],["Waldorf Astoria RAK","Hotels","Ras Al Khaimah","Al Hamra",84,16,88,146],
  ["Trèsind Studio","Luxury Dining","Dubai","Palm Jumeirah",27,61,96,242],["Ossiano","Luxury Dining","Dubai","Palm Jumeirah",22,56,95,226],["Il Ristorante - Niko Romito","Luxury Dining","Dubai","Jumeirah Bay",37,45,93,194],["Zuma Dubai","Restaurants","Dubai","DIFC",49,47,92,218],["Orfali Bros Bistro","Restaurants","Dubai","Jumeirah",41,53,90,178],["Hakkasan Abu Dhabi","Luxury Dining","Abu Dhabi","Emirates Palace",18,33,91,186],
  ["Nammos Dubai","Beach Clubs","Dubai","Jumeirah",36,50,93,198],["Azure Beach","Beach Clubs","Dubai","JBR",29,68,91,184],["WHITE Beach","Beach Clubs","Dubai","Palm Jumeirah",23,57,92,206],["Saadiyat Beach Club","Beach Clubs","Abu Dhabi","Saadiyat Island",25,34,89,158],
  ["VIP Rent A Car","Car Rentals","Dubai","Business Bay",54,58,94,316],["Uptown Rent A Car","Car Rentals","Dubai","Dubai Marina",32,64,90,232],["Paddock Luxury","Car Rentals","Dubai","Al Quoz",48,62,88,196],["Superior Car Rental","Car Rentals","Abu Dhabi","Al Bateen",17,36,86,142],
  ["Talise Ottoman Spa","Spas","Dubai","Palm Jumeirah",24,63,91,174],["Dior Spa The Lana","Spas","Dubai","Business Bay",52,54,94,208],["Armani/SPA","Spas","Dubai","Downtown Dubai",55,49,92,186],["Anantara Spa","Spas","Abu Dhabi","Eastern Mangroves",23,28,87,138],
  ["Level Shoes Private","Retail","Dubai","Dubai Mall",56,51,89,156],["Lumé Joaillerie","Retail","Dubai","DIFC",50,46,91,172],["The Edit Dubai","Retail","Dubai","Dubai Marina",33,62,86,126],["Tryano","Retail","Abu Dhabi","Yas Mall",30,29,85,118],
  ["King's College Hospital","Healthcare","Dubai","Dubai Hills",61,66,86,118],["American Hospital Dubai","Healthcare","Dubai","Oud Metha",59,42,88,136],["Healthpoint","Healthcare","Abu Dhabi","Zayed Sports City",21,39,84,104],
  ["Coca-Cola Arena","Events","Dubai","City Walk",47,50,92,228],["The Foundry","Events","Dubai","Al Quoz",45,61,88,164],["Yas Marina Circuit","Events","Abu Dhabi","Yas Island",31,26,90,186],["Aljada Events District","Events","Sharjah","Aljada",72,33,83,96],
  ["OMNIYAT Residences","Real Estate","Dubai","Downtown Dubai",57,48,88,132],["Muraba Residences","Real Estate","Dubai","Palm Jumeirah",26,60,87,126],["Aldar Experience Centre","Real Estate","Abu Dhabi","Yas Island",29,31,89,148],
  ["The Lana Concierge","Luxury Experiences","Dubai","Business Bay",54,56,95,264],["Hero Balloon Flights","Luxury Experiences","Dubai","Dubai Desert",70,72,89,172],["Platinum Heritage","Luxury Experiences","Dubai","Dubai Desert",74,68,91,188],["Xclusive Yachts","Luxury Experiences","Dubai","Dubai Marina",30,65,93,216],
  ["RAK Resort Development","Real Estate","Ras Al Khaimah","Al Marjan Island",85,18,99,338,true],["F10 Car Rental","Car Rentals","Ras Al Khaimah","Al Hamra",82,22,98,294,true],["RAK Hotel Partner","Hotels","Ras Al Khaimah","Al Marjan Island",87,20,99,326,true],
];
const initials=(name:string)=>name.split(/[\s&-]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const businesses:Business[]=raw.map(([name,category,city,location,x,y,fit,referrals,ceo=false],i)=>({
  name,category,city,location,x,y,fit,referrals,ceo,initials:initials(name),nearby:ceo?8:6+(i*7)%18,bundle:ceo?"RAK Stay + Car Rental + Resort Experience":bundles[category],opportunity:opportunityType[category],priority:ceo?"Very High":fit>=89?"High":"Medium",value:ceo?Math.round((referrals*920)/1000)*1000:Math.round((referrals*(540+(i%5)*85))/1000)*1000,
  outreach:ceo?"Use the CEO network connection for a private pilot-cluster introduction and commercial workshop.":fit>=93?"Founder-led introduction with a tailored commercial opportunity brief.":"Invite the commercial lead to a focused 30-minute partnership discovery session.",
  meeting:ceo?"CEO + Development Director + Commercial Lead":fit>=92?"Commercial Director + Guest Experience Lead":"Partnerships or Marketing Director"
}));
const sectors=["All industries",...Object.keys(bundles)];
const cities=["All cities","Dubai","Abu Dhabi","Sharjah","Ras Al Khaimah"];
const opportunities=["All opportunities",...Array.from(new Set(Object.values(opportunityType)))];
const clusters=[
  {name:"Dubai Marina",x:31,y:65,zoom:1.75},{name:"Downtown Dubai",x:55,y:49,zoom:1.8},{name:"Palm Jumeirah",x:25,y:59,zoom:1.85},{name:"Business Bay",x:53,y:56,zoom:1.9},{name:"Jumeirah Beach",x:37,y:51,zoom:1.75},{name:"Abu Dhabi",x:23,y:31,zoom:1.55},{name:"Sharjah",x:70,y:34,zoom:1.65},{name:"Ras Al Khaimah",x:85,y:19,zoom:2.05},
];
const feedTemplates=["New high-fit hotel opportunity detected","Referral corridor identified in Business Bay","Premium bundle recommendation generated","Three compatible partners found near Dubai Marina","New luxury experience added to scan"];

export default function OpportunityMap(){
  const [sector,setSector]=useState("All industries"),[city,setCity]=useState("All cities"),[minFit,setMinFit]=useState(80),[priority,setPriority]=useState("All priorities"),[opportunity,setOpportunity]=useState("All opportunities"),[ceoOnly,setCeoOnly]=useState(false);
  const [selected,setSelected]=useState<Business>(businesses[0]),[hovered,setHovered]=useState<Business|null>(null),[pipeline,setPipeline]=useState<Business[]>(businesses.filter(x=>x.priority==="High").slice(0,5));
  const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[dragging,setDragging]=useState(false),[toast,setToast]=useState(""),[scan,setScan]=useState(68),[feed,setFeed]=useState<string[]>(feedTemplates.slice(0,3));
  const drag=useRef({x:0,y:0,px:0,py:0}),mapRef=useRef<HTMLElement|null>(null);
  const filtered=useMemo(()=>businesses.filter(b=>(!ceoOnly||b.ceo)&&(sector==="All industries"||b.category===sector)&&(city==="All cities"||b.city===city)&&b.fit>=minFit&&(priority==="All priorities"||b.priority===priority)&&(opportunity==="All opportunities"||b.opportunity===opportunity)),[sector,city,minFit,priority,opportunity,ceoOnly]);
  const matches=useMemo(()=>businesses.filter(b=>b.name!==selected.name&&(b.city===selected.city||b.category===selected.category)).sort((a,b)=>b.fit-a.fit).slice(0,4),[selected]);
  useEffect(()=>{const kickoff=window.setTimeout(()=>setScan(Math.min(22,filtered.length)),0);const a=window.setInterval(()=>setScan(v=>Math.min(filtered.length,v+2)),55);const b=window.setInterval(()=>setFeed(items=>[feedTemplates[Math.floor(Math.random()*feedTemplates.length)],...items.slice(0,3)]),4200);return()=>{clearTimeout(kickoff);clearInterval(a);clearInterval(b)}},[filtered.length]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const clampPan=(next:{x:number;y:number},z=zoom)=>{const el=mapRef.current;if(!el)return next;const maxX=Math.max(0,(el.clientWidth*(z-1))/2),maxY=Math.max(0,(el.clientHeight*(z-1))/2);return{x:Math.max(-maxX,Math.min(maxX,next.x)),y:Math.max(-maxY,Math.min(maxY,next.y))}};
  const focusCluster=(c:typeof clusters[number])=>{const el=mapRef.current;const nextZoom=c.zoom;const next=el?{x:-(c.x-50)*el.clientWidth*nextZoom/100,y:-(c.y-50)*el.clientHeight*nextZoom/100}:{x:0,y:0};setZoom(nextZoom);setPan(clampPan(next,nextZoom));if(c.name==="Ras Al Khaimah")setCity("Ras Al Khaimah");notify(`${c.name} cluster focused`)};
  const changeZoom=(delta:number)=>{const next=Math.max(.8,Math.min(2.4,Number((zoom+delta).toFixed(2))));setZoom(next);setPan(current=>clampPan(current,next))};
  const addLead=(b:Business)=>{if(!pipeline.some(x=>x.name===b.name))setPipeline(x=>[b,...x]);notify(`${b.name} added to Partner Pipeline`)};
  const reset=()=>{setSector("All industries");setCity("All cities");setPriority("All priorities");setOpportunity("All opportunities");setMinFit(80);setCeoOnly(false);setZoom(1);setPan({x:0,y:0})};
  const startDrag=(e:React.PointerEvent)=>{setDragging(true);drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)};
  const moveDrag=(e:React.PointerEvent)=>{if(dragging)setPan(clampPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y}))};

  return <main className="min-h-screen bg-[#F5F3F7] text-[#19152A]"><div className="mx-auto max-w-[1780px] px-4 py-7 sm:px-7 lg:px-9">
    <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex w-fit items-center gap-2 rounded-full border border-[#DDD3F8] bg-white px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#5E3BEE]"><span className="relative flex h-2 w-2"><i className="absolute h-full w-full animate-ping rounded-full bg-[#4EBE91] opacity-40"/><i className="relative h-2 w-2 rounded-full bg-[#4EBE91]"/></span>Live scan active</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] sm:text-[40px]">UAE Opportunity Map</h1><p className="mt-2 text-[10px] text-[#817A87]">Commercial intelligence for deciding which UAE businesses NEFE should connect first.</p></div><div className="flex gap-2">{[["Scanned",`${scan}/${filtered.length}`],["Opportunities",filtered.length.toString()],["Monthly value",`AED ${(filtered.reduce((s,b)=>s+b.value,0)/1e6).toFixed(1)}M`]].map(([l,v])=><div key={l} className="rounded-xl border border-[#E3DEE7] bg-white px-4 py-3"><p className="text-[6px] uppercase text-[#9D96A2]">{l}</p><p className="mt-1 text-sm font-bold">{v}</p></div>)}</div></div>

    <section className="mt-5 rounded-[20px] border border-[#E4DFE8] bg-white p-3"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_1fr_1.2fr_auto]">{[[sector,setSector,sectors,"Industry"],[city,setCity,cities,"City"],[priority,setPriority,["All priorities","Very High","High","Medium"],"Priority"],[opportunity,setOpportunity,opportunities,"Opportunity"]].map(([value,setter,items,label])=><label key={label as string} className="opportunity-filter"><span>{label as string}</span><select value={value as string} onChange={e=>(setter as React.Dispatch<React.SetStateAction<string>>)(e.target.value)}>{(items as string[]).map(x=><option key={x}>{x}</option>)}</select></label>)}<label className="px-3 py-2"><span className="flex justify-between text-[7px] font-bold uppercase text-[#8F8895]">Minimum fit <b className="text-[#5E3BEE]">{minFit}%</b></span><input type="range" min="80" max="99" value={minFit} onChange={e=>setMinFit(Number(e.target.value))} className="roi-slider mt-3 w-full"/></label><button onClick={reset} className="rounded-xl bg-[#F1EDFF] px-4 text-[8px] font-semibold text-[#5E3BEE]">Reset</button></div></section>

    <div className="no-scrollbar mt-3 flex gap-2 overflow-x-auto"><button onClick={()=>{if(ceoOnly){setCeoOnly(false);setCity("All cities");setZoom(1);setPan({x:0,y:0})}else{setCeoOnly(true);focusCluster(clusters.find(x=>x.name==="Ras Al Khaimah")!)}}} className={`shrink-0 rounded-full border px-3 py-2 text-[7px] font-bold transition ${ceoOnly?"border-[#C6983E] bg-[#FFF4D9] text-[#946B1C]":"border-[#D8C58F] bg-white text-[#9B7428]"}`}>★ CEO Network</button>{clusters.map(c=><button key={c.name} onClick={()=>focusCluster(c)} className="shrink-0 rounded-full border border-[#E0DAE5] bg-white px-3 py-2 text-[7px] font-semibold text-[#625B69] transition hover:border-[#BFAFF2] hover:text-[#5E3BEE]">◎ {c.name}</button>)}</div>

    <div className="mt-3 grid gap-4 xl:grid-cols-[1fr_380px]"><div className="min-w-0">
      <section ref={mapRef} className={`uae-map relative min-h-[680px] overflow-hidden rounded-[25px] border border-[#DCD6E3] shadow-[0_20px_55px_rgba(42,31,64,.1)] ${dragging?"cursor-grabbing":"cursor-grab"}`} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={()=>setDragging(false)} onPointerCancel={()=>setDragging(false)}>
        <div onPointerDown={e=>e.stopPropagation()} className="absolute right-4 top-4 z-40 grid gap-1"><button onClick={()=>changeZoom(.2)} className="map-control">+</button><button onClick={()=>changeZoom(-.2)} className="map-control">−</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0});setCity("All cities");setCeoOnly(false)}} className="map-control text-[7px]">⌂</button></div>
        <div className="absolute left-4 top-4 z-40 rounded-xl border border-white/60 bg-white/80 px-3 py-2 text-[7px] font-semibold text-[#5E3BEE] shadow-sm backdrop-blur">Scan density · {Math.round(zoom*100)}%</div>
        <div className={`absolute inset-0 ease-out ${dragging?"transition-none":"transition-transform duration-500"}`} style={{transform:`translate3d(${pan.x}px,${pan.y}px,0) scale(${zoom})`,transformOrigin:"50% 50%"}}>
          <div className="uae-map-grid absolute inset-0"/><div className="uae-coast"/>{clusters.map(c=><button key={c.name} onClick={e=>{e.stopPropagation();focusCluster(c)}} className="cluster-ring absolute z-[4] -translate-x-1/2 -translate-y-1/2" style={{left:`${c.x}%`,top:`${c.y}%`}}><span>{businesses.filter(b=>Math.hypot(b.x-c.x,b.y-c.y)<10).length}</span><i>{c.name}</i></button>)}
          <svg viewBox="0 0 1000 680" className="pointer-events-none absolute inset-0 h-full w-full">{filtered.slice(0,24).map((b,i)=>{const t=filtered[(i+3)%filtered.length];return t?<path key={b.name} d={`M${b.x*10} ${b.y*6.8} Q500 340 ${t.x*10} ${t.y*6.8}`} fill="none" stroke="rgba(94,59,238,.18)" strokeWidth="1" strokeDasharray="5 7" className="commerce-dash"/>:null})}</svg>
          {filtered.map((b,i)=><button key={b.name} onPointerDown={e=>e.stopPropagation()} onMouseEnter={()=>setHovered(b)} onMouseLeave={()=>setHovered(null)} onClick={()=>setSelected(b)} className={`map-pin map-pin-pulse absolute z-10 -translate-x-1/2 -translate-y-1/2 transition-all duration-500 ${b.ceo?"ceo-marker":""} ${selected.name===b.name?"active":""}`} style={{left:`${b.x}%`,top:`${b.y}%`,animationDelay:`${i*35}ms`}}><span>{b.initials}</span><i>{b.ceo?"CEO Network":`${b.fit}%`}</i></button>)}
          {hovered&&<div className={`map-intel-card absolute z-50 w-64 -translate-x-1/2 -translate-y-[112%] rounded-[16px] border bg-white/95 p-3 shadow-2xl backdrop-blur ${hovered.ceo?"border-[#D2A447]":"border-white/70"}`} style={{left:`${hovered.x}%`,top:`${hovered.y}%`}}><div className="flex justify-between"><div><p className="text-[9px] font-semibold">{hovered.name}</p><p className="mt-1 text-[6px] text-[#918A96]">{hovered.category} · {hovered.ceo?"Ras Al Khaimah":hovered.location}</p></div><b className={`text-[8px] ${hovered.ceo?"text-[#9A7020]":"text-[#5E3BEE]"}`}>{hovered.ceo?"CEO Network":`${hovered.fit}% fit`}</b></div><div className="mt-3 grid grid-cols-3 gap-2"><small>{hovered.ceo?"Very High":hovered.priority}<em>Priority</em></small><small>{hovered.nearby}<em>Nearby</em></small><small>AED {(hovered.value/1000).toFixed(0)}K<em>Monthly</em></small></div><p className={`mt-3 rounded-lg p-2 text-[7px] font-semibold ${hovered.ceo?"bg-[#FFF4D9] text-[#926A1C]":"bg-[#F2EEFF] text-[#5E3BEE]"}`}>{hovered.bundle}</p></div>}
        </div>
      </section>
      <div className="mt-3 rounded-[16px] border border-[#E0C982] bg-gradient-to-r from-[#FFF9E9] to-[#F5F0FF] p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-[#C2963E] to-[#6A47DC] text-white">★</span><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#8D6821]">CEO Network insight</p><p className="mt-1 text-[9px] font-semibold">CEO Network detected in Ras Al Khaimah: resort development, car rental, and hotel partnership can form NEFE’s first regional pilot cluster.</p></div><button onClick={()=>focusCluster(clusters.find(x=>x.name==="Ras Al Khaimah")!)} className="ml-auto shrink-0 rounded-lg bg-white px-3 py-2 text-[7px] font-semibold text-[#5E3BEE]">Focus cluster →</button></div></div>
      <div className="mt-3 grid gap-3 md:grid-cols-3">{feed.map((item,i)=><div key={`${item}-${i}`} className="admin-activity-new flex items-center gap-3 rounded-[15px] border border-[#E2DDE6] bg-white p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#F0ECFF] text-[#5E3BEE]">✦</span><div><p className="text-[7px] font-semibold">{item}</p><p className="mt-1 text-[6px] text-[#99929F]">{i===0?"Just now":`${i*2+1} min ago`}</p></div></div>)}</div>
    </div>

    <aside className="h-fit rounded-[24px] border border-[#E0DAE5] bg-[#171221] p-5 text-white shadow-[0_18px_50px_rgba(32,23,47,.18)] xl:sticky xl:top-24"><div className="flex items-start gap-3"><span className={`grid h-12 w-12 place-items-center rounded-[14px] bg-gradient-to-br text-[9px] font-bold ${selected.ceo?"from-[#C89A3E] to-[#6542DA] shadow-[0_0_22px_rgba(207,164,69,.25)]":"from-[#6542DC] to-[#B084D0]"}`}>{selected.initials}</span><div className="min-w-0 flex-1"><p className="text-[7px] font-bold uppercase tracking-[.14em] text-[#B49EF3]">Full Business Profile</p><h2 className="mt-1 truncate text-[15px] font-semibold">{selected.name}</h2><p className="mt-1 text-[7px] text-white/30">{selected.category} · {selected.location}</p>{selected.ceo&&<span className="mt-2 inline-flex rounded-full bg-[#D1A344]/15 px-2 py-1 text-[6px] font-bold text-[#E2BD65]">★ CEO Network</span>}</div><span className="rounded-full bg-[#4BB88C]/15 px-2 py-1 text-[7px] font-bold text-[#5ACDA1]">{selected.fit}% fit</span></div>
      <div className="mt-5 grid grid-cols-2 gap-2">{[["Commercial score",`${selected.fit}/100`],["Monthly revenue",`AED ${selected.value.toLocaleString()}`],["Referrals",selected.referrals.toString()],["Nearby matches",selected.nearby.toString()]].map(([l,v])=><div key={l} className="rounded-xl bg-white/[.055] p-3"><p className="text-[6px] text-white/25">{l}</p><p className="mt-1 text-[11px] font-semibold">{v}</p></div>)}</div>
      <div className="mt-4 rounded-[14px] border border-[#7254CE]/25 bg-[#5E3BEE]/10 p-3"><p className="text-[6px] uppercase text-[#A992EA]">Suggested bundle</p><p className="mt-1 text-[9px] font-semibold">{selected.bundle}</p></div>
      <div className="mt-4"><p className="text-[7px] font-bold uppercase tracking-wider text-white/30">Nearby Partner Matches</p><div className="mt-2 space-y-2">{matches.map(m=><button key={m.name} onClick={()=>setSelected(m)} className="flex w-full items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.035] p-2.5 text-left"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#6745D8]/20 text-[6px] text-[#B7A3F2]">{m.initials}</span><span className="min-w-0 flex-1 truncate text-[7px]">{m.name}</span><b className="text-[7px] text-[#59C99D]">{m.fit}%</b></button>)}</div></div>
      <div className="mt-4 space-y-3 border-t border-white/[.08] pt-4">{selected.ceo&&<div className="rounded-xl border border-[#C99A3F]/20 bg-[#C99A3F]/10 p-3"><p className="text-[6px] uppercase text-[#D7B35D]">Suggested pilot use</p><p className="mt-1 text-[7px] leading-4 text-white/65">Anchor NEFE’s first Ras Al Khaimah regional pilot with a connected resort, hotel and mobility journey.</p><p className="mt-2 text-[6px] uppercase text-[#D7B35D]">Recommended next action</p><p className="mt-1 text-[7px] font-semibold">Schedule a CEO-sponsored pilot design workshop.</p></div>}<div><p className="text-[6px] uppercase text-white/25">Suggested outreach strategy</p><p className="mt-1 text-[7px] leading-4 text-white/55">{selected.outreach}</p></div><div><p className="text-[6px] uppercase text-white/25">Recommended first meeting</p><p className="mt-1 text-[8px] font-semibold text-[#D5B45F]">{selected.meeting}</p></div></div>
      <div className="mt-5 grid grid-cols-2 gap-2">{["Generate Outreach Plan","Create Partnership Bundle","Compare Nearby Businesses","View Commercial Analysis"].map(action=><button key={action} onClick={()=>notify(`${action} prepared for ${selected.name}`)} className="rounded-xl border border-white/10 bg-white/[.045] px-2 py-3 text-[7px] font-semibold text-white/65 transition hover:border-[#7658D1] hover:text-white">{action}</button>)}</div><button onClick={()=>addLead(selected)} className="mt-2 w-full rounded-xl bg-gradient-to-r from-[#6542DA] to-[#8562E8] py-3 text-[8px] font-semibold">Add to Partner Pipeline · {pipeline.length} leads</button>
    </aside></div></div>
    {toast&&<div className="prototype-toast fixed bottom-6 left-1/2 z-[100] -translate-x-1/2 rounded-xl bg-[#211A32]/95 px-4 py-3 text-[8px] font-semibold text-white shadow-2xl">✓ {toast}</div>}
  </main>;
}
