import Link from "next/link";
import {notFound} from "next/navigation";
import {getOpportunityDetail} from "@/app/lib/data/opportunity-repository";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {can} from "@/app/lib/auth/permissions";
import {deriveOpportunityHealth,OPPORTUNITY_STAGES,opportunityStageLabel} from "@/app/lib/opportunity/opportunity-policy";
import {formatAed} from "../../../_lib/format";
import NextActions from "../../_components/next-actions";
import EntityCollaboration from "../../_components/entity-collaboration";
import EntityDecisions from "../../_components/entity-decisions";
import WorkspaceBreadcrumbs from "../../_components/workspace-breadcrumbs";
import {FavoriteButton,ViewTracker} from "../../_components/entity-actions";
import {AppCard,EmptyState,MetricCard,PageHeader,ProgressBar,SectionHeader,StatBadge,StatusBadge} from "../../_components/ui";
import OpportunityProfileEditor from "./opportunity-profile-editor";

export default async function OpportunityDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params,context=await requireWorkspaceContext(),detail=await getOpportunityDetail(context,id);if(!detail)notFound();const {opportunity,intelligence}=detail,canUpdate=can(context.membership.role,"opportunity.update"),health=deriveOpportunityHealth({confidence:intelligence.confidence,stage:opportunity.stage,recommendationCount:detail.recommendations.length}),currentStage=Math.max(0,OPPORTUNITY_STAGES.indexOf(opportunity.stage as (typeof OPPORTUNITY_STAGES)[number]));return <><ViewTracker type="opportunity" id={opportunity.id} title={opportunity.title} href={`/workspace/opportunities/${opportunity.id}`}/><WorkspaceBreadcrumbs section="Opportunities" href="/workspace/opportunities" current={opportunity.title}/><PageHeader eyebrow="Opportunity workspace" title={opportunity.title} description={opportunity.summary} action={<div className="ws-action-bar"><FavoriteButton type="opportunity" id={opportunity.id}/><OpportunityProfileEditor opportunity={opportunity} participantIds={detail.participants.map(item=>item.id)} businesses={detail.references.businesses} members={detail.references.members} allowed={canUpdate}/><Link className="ws-button" href="/workspace/opportunities/compare">Compare</Link></div>}/>
<section aria-labelledby="opportunity-executive-summary"><SectionHeader title="Executive Summary" description="Recorded ownership, priority, current status, and the latest governed commercial position."/><div className="ws-metric-grid"><MetricCard label="Pipeline stage" value={<StatusBadge tone={opportunity.stage}>{opportunityStageLabel(opportunity.stage)}</StatusBadge>} detail="Recorded data"/><MetricCard label="Estimated value" value={formatAed(opportunity.modeledValue)} detail="Recorded modeled value" tone="gold"/><MetricCard label="Commercial health" value={health} detail="Derived insight" tone="green"/><MetricCard label="Owner" value={opportunity.owner??"Unassigned"} detail="Recorded accountable member" tone="blue"/></div><NextActions actions={[{label:"Request executive approval",href:"#executive-decisions",description:"Create or review a formal decision for this opportunity.",primary:true,disabledReason:can(context.membership.role,"decision.create")?undefined:"Your role cannot create decisions."},{label:"Create pilot",href:`/workspace/pilots/new?opportunity=${opportunity.id}`,description:"Move an approved opportunity into execution.",disabledReason:!["APPROVED","PILOT"].includes(opportunity.stage)?"Approve the opportunity before creating a pilot.":can(context.membership.role,"pilot.create")?undefined:"Your role cannot create pilots."},{label:"Open discussion",href:"#collaboration",description:"Coordinate participants and commercial next steps."}]}/></section>
<section className="ws-section-gap" aria-labelledby="opportunity-pipeline"><SectionHeader title="Pipeline Status" description="Recorded stage progression and accountable history."/><AppCard><div className="ws-opportunity-stage-track">{OPPORTUNITY_STAGES.map((stage,index)=><div className={index<currentStage?"complete":index===currentStage?"current":""} key={stage}><span>{index<currentStage?"✓":index+1}</span><strong>{opportunityStageLabel(stage)}</strong></div>)}</div><div className="ws-timeline ws-opportunity-history">{detail.history.map(item=><article className="ws-timeline-item" key={item.id}><h3>{opportunityStageLabel(item.label)}</h3><p>{item.detail} · {item.occurredAt.toLocaleString()}</p></article>)}{!detail.history.length&&<EmptyState title="No stage history" description="Pipeline movement will appear here after the first recorded transition."/>}</div></AppCard></section>
<RecordSection id="opportunity-business-context" title="Business Context" description="Businesses connected through persisted opportunity participation." empty="No participating businesses are recorded." count={detail.participants.length}><div className="ws-list">{detail.participants.map(item=><Link className="ws-list-item" href={`/workspace/businesses/${item.id}`} key={item.id}><span>{item.initials}</span><div><strong>{item.name}</strong><p>{item.category} · {item.location}</p></div><StatusBadge tone={item.status}>{item.status}</StatusBadge></Link>)}</div></RecordSection>
<section className="ws-section-gap" aria-labelledby="opportunity-commercial-value"><SectionHeader title="Commercial Value" description="Recorded commercial inputs and deterministic derived intelligence are separated below."/><div className="ws-layout-2"><AppCard><SectionHeader title="Recorded Data" description="Values and rationale stored on this opportunity."/><div className="ws-detail-grid"><StatBadge label="Estimated modeled value" value={formatAed(opportunity.modeledValue)}/><StatBadge label="Priority" value={opportunity.priority}/><StatBadge label="Status" value={opportunity.status}/><StatBadge label="Participants" value={String(detail.participants.length)}/></div><p className="ws-body-copy"><strong>Strategic rationale</strong><br/>{opportunity.commercialReasoning}</p><p className="ws-body-copy"><strong>Expected journey outcome</strong><br/>{opportunity.journeyImpact}</p></AppCard><AppCard><SectionHeader title="Derived Insight" description="Deterministic scores recalculated from current persisted records."/><div className="ws-opportunity-intelligence">{[["Compatibility",intelligence.compatibility],["Readiness",intelligence.partnershipReadiness],["Opportunity score",intelligence.commercialOpportunity],["Confidence",intelligence.confidence]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}%</strong><ProgressBar value={Number(value)} label={`${label}: ${value}%`}/></div>)}</div><div className="ws-factor-grid"><div><b>Key reasons</b>{intelligence.positiveFactors.length?intelligence.positiveFactors.map(item=><span key={item}>+ {item}</span>):<span>No positive factor has crossed the deterministic threshold.</span>}</div><div><b>Limitations</b>{intelligence.limitingFactors.length?intelligence.limitingFactors.map(item=><span key={item}>− {item}</span>):<span>No limiting factor has crossed the deterministic threshold.</span>}</div></div></AppCard></div></section>
<section className="ws-section-gap" aria-labelledby="opportunity-participants"><SectionHeader title="Participants" description="Current business participants and accountable opportunity owner."/><AppCard><div className="ws-opportunity-participants"><StatBadge label="Owner" value={opportunity.owner??"Unassigned"}/>{detail.participants.map(item=><Link href={`/workspace/businesses/${item.id}`} key={item.id}><span className="ws-avatar">{item.initials}</span><span><strong>{item.name}</strong><small>{item.category}</small></span></Link>)}</div></AppCard></section>
<RecordSection id="opportunity-recommendations" title="Recommendations" description="Persisted recommendations and their recorded confidence; derived intelligence appears above." empty="No recommendation is recorded for this opportunity." count={detail.recommendations.length}><div className="ws-recommendations">{detail.recommendations.map(item=><article key={item.id}><div className="ws-recommendation-head"><div><StatusBadge tone={item.priority}>{item.priority}</StatusBadge><h3>{item.title}</h3></div><strong>{item.confidence}%</strong></div><p>{item.description}</p><div className="ws-detail-grid"><StatBadge label="Modeled impact" value={formatAed(item.modeledImpact)}/><StatBadge label="Recorded state" value={item.status}/></div><ProgressBar value={item.confidence} label={`${item.title}: ${item.confidence}% recorded recommendation confidence`}/></article>)}</div></RecordSection>
<EntityCollaboration entityType="opportunity" entityId={opportunity.id}/>
<RecordSection id="opportunity-campaigns" title="Related Campaigns" description="Campaigns connected through persisted pilot relationships." empty="No campaign is linked through an opportunity pilot." count={detail.relatedCampaigns.length}><div className="ws-list">{detail.relatedCampaigns.map(item=><Link className="ws-list-item" href={`/workspace/campaigns/${item.id}`} key={item.id}><span>C</span><div><strong>{item.title}</strong><p>{item.objective}</p></div><StatusBadge tone={item.status}>{item.status}</StatusBadge></Link>)}</div></RecordSection>
<RecordSection id="opportunity-journeys" title="Related Journeys" description="Journeys connected through persisted pilot relationships." empty="No journey is linked through an opportunity pilot." count={detail.relatedJourneys.length}><div className="ws-list">{detail.relatedJourneys.map(item=><Link className="ws-list-item" href={`/workspace/journeys/${item.id}`} key={item.id}><span>J</span><div><strong>{item.name}</strong><p>{item.coverage}% coverage · {item.completion}% complete</p></div></Link>)}</div></RecordSection>
<RecordSection id="opportunity-pilots" title="Related Pilots" description="Execution pilots created directly from this opportunity." empty="No pilot has been created from this opportunity." count={detail.pilots.length}><div className="ws-list">{detail.pilots.map(item=><Link className="ws-list-item" href={`/workspace/pilots/${item.id}`} key={item.id}><span>P</span><div><strong>{item.name}</strong><p>{formatAed(item.modeledValue)} modeled value</p></div><StatusBadge tone={item.status}>{item.status}</StatusBadge></Link>)}</div></RecordSection>
<EntityDecisions entityType="opportunity" entityId={opportunity.id}/>
<RecordSection id="opportunity-activity" title="Activity Timeline" description="Latest meaningful opportunity, collaboration, and governance activity." empty="No activity has been recorded for this opportunity." count={detail.activity.length}><div className="ws-timeline">{detail.activity.map(item=><article className="ws-timeline-item" key={item.id}><h3>{item.summary}</h3><p>{item.actorName??"System"} · {item.createdAt.toLocaleString()}</p></article>)}</div></RecordSection></>}

function RecordSection({id,title,description,empty,count,children}:{id:string;title:string;description:string;empty:string;count:number;children:React.ReactNode}){return <section className="ws-section-gap" aria-labelledby={id}><SectionHeader title={title} description={description}/><AppCard>{count?children:<EmptyState title={`No ${title.toLowerCase()}`} description={empty}/>}</AppCard></section>}
