"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {addDecisionParticipant,addDecisionReviewComment,cancelDecision,expireDecision,finalizeDecision,removeDecisionParticipant,reopenDecision,reorderDecisionApprovers,respondToDecision,submitDecision,updateDecisionDraft} from "@/app/lib/actions/decision-actions";
import {AppCard,SectionHeader} from "./ui";

type Decision={id:string;entityType:string;entityId:string;title:string;statement:string;rationale:string;requestedOutcome:string;priority:string;approvalMode:string;ownerId:string;status:string;versionNumber:number;dueAt:string|null;createdAt:string;updatedAt:string;submittedAt:string|null;finalizedAt:string|null};
type Participant={id:string;userId:string;role:string;order:number|null;name:string};
type Response={id:string;userId:string;state:string;comment:string|null;createdAt:string;name:string};
type Member={id:string;name:string|null;role:string};
type Result={ok:boolean;error?:string};

export default function DecisionDetailClient({decision,participants,responses,members,permissions,currentUserId}:{decision:Decision;participants:Participant[];responses:Response[];members:Member[];permissions:{create:boolean;submit:boolean;approve:boolean;admin:boolean};currentUserId:string}){
  const [error,setError]=useState(""),[pending,start]=useTransition(),[confirm,setConfirm]=useState(false),router=useRouter();
  const approvers=participants.filter(item=>item.role==="approver"),reviewers=participants.filter(item=>item.role==="reviewer"),actorApprover=approvers.some(item=>item.userId===currentUserId),actorReviewer=reviewers.some(item=>item.userId===currentUserId),responded=responses.some(item=>item.userId===currentUserId);
  const run=(operation:()=>Promise<Result>)=>start(async()=>{setError("");const result=await operation();if(!result.ok)setError(result.error??"The decision change could not be saved.");else{setConfirm(false);router.refresh()}});
  return <AppCard className="ws-decision-controls"><SectionHeader title="Approval progress" description={`${decision.approvalMode} approval · ${approvers.length} required approver${approvers.length===1?"":"s"}`}/>
    <div className="ws-approval-list">{approvers.map((participant,index)=>{const response=responses.find(item=>item.userId===participant.userId);return <article key={participant.id}><span>{decision.approvalMode==="sequential"?participant.order??index+1:"•"}</span><div><strong>{participant.name}</strong><small>{response?response.state.replaceAll("_"," "):"pending"}</small>{response?.comment&&<p>{response.comment}</p>}</div>{decision.status==="draft"&&permissions.submit&&<button type="button" onClick={()=>run(()=>removeDecisionParticipant({decisionId:decision.id,userId:participant.userId,role:"approver"}))}>Remove</button>}</article>})}{reviewers.map(participant=><article key={participant.id}><span>R</span><div><strong>{participant.name}</strong><small>reviewer</small></div>{decision.status==="draft"&&permissions.submit&&<button type="button" onClick={()=>run(()=>removeDecisionParticipant({decisionId:decision.id,userId:participant.userId,role:"reviewer"}))}>Remove</button>}</article>)}</div>
    {decision.status==="draft"&&decision.approvalMode==="sequential"&&permissions.submit&&approvers.length>1&&<ReorderControls decisionId={decision.id} approvers={approvers} pending={pending} run={run}/>} 
    {decision.status==="draft"&&permissions.submit&&<ParticipantForm decisionId={decision.id} members={members} participants={participants} pending={pending} run={run}/>}<div className="ws-decision-actions">
      {decision.status==="draft"&&permissions.create&&<DraftEditor decision={decision} members={members} pending={pending} run={run}/>} 
      {decision.status==="draft"&&permissions.submit&&<><button className="ws-button" disabled={pending} onClick={()=>run(()=>submitDecision({decisionId:decision.id,target:"pending_review",expectedVersion:decision.versionNumber}))}>Submit for review</button><button className="ws-button primary" disabled={pending||!approvers.length} onClick={()=>run(()=>submitDecision({decisionId:decision.id,target:"pending_approval",expectedVersion:decision.versionNumber}))}>Submit for approval</button></>}
      {decision.status==="pending_review"&&permissions.submit&&<button className="ws-button primary" disabled={pending||!approvers.length} onClick={()=>run(()=>submitDecision({decisionId:decision.id,target:"pending_approval",expectedVersion:decision.versionNumber}))}>Advance to approval</button>}
      {["pending_review","pending_approval"].includes(decision.status)&&actorReviewer&&<ReviewCommentForm pending={pending} onComment={comment=>run(()=>addDecisionReviewComment({decisionId:decision.id,comment}))}/>} 
      {decision.status==="pending_approval"&&permissions.approve&&actorApprover&&!responded&&<ResponseForm pending={pending} onRespond={(state,comment)=>run(()=>respondToDecision({decisionId:decision.id,state,comment,idempotencyKey:crypto.randomUUID(),expectedVersion:decision.versionNumber}))}/>} 
      {permissions.admin&&["draft","pending_review","pending_approval"].includes(decision.status)&&(confirm?<div className="ws-inline-confirm" role="group" aria-label="Confirm cancellation"><span>Confirm this governance action?</span><button className="ws-button danger" disabled={pending} onClick={()=>run(()=>cancelDecision({decisionId:decision.id,expectedVersion:decision.versionNumber}))}>Confirm</button><button className="ws-button" onClick={()=>setConfirm(false)}>Keep decision</button></div>:<button className="ws-button danger" onClick={()=>setConfirm(true)}>Cancel decision</button>)}
      {permissions.admin&&["rejected","changes_requested","cancelled","expired"].includes(decision.status)&&<button className="ws-button" disabled={pending} onClick={()=>run(()=>reopenDecision({decisionId:decision.id,expectedVersion:decision.versionNumber}))}>Reopen as new version</button>}
      {permissions.admin&&["pending_review","pending_approval"].includes(decision.status)&&decision.dueAt&&new Date(decision.dueAt)<new Date()&&<button className="ws-button" disabled={pending} onClick={()=>run(()=>expireDecision({decisionId:decision.id,expectedVersion:decision.versionNumber}))}>Mark expired</button>}
      {permissions.admin&&decision.status==="approved"&&!decision.finalizedAt&&<FinalizeForm pending={pending} onFinalize={summary=>run(()=>finalizeDecision({decisionId:decision.id,expectedVersion:decision.versionNumber,summary}))}/>} 
    </div>{error&&<p className="ws-collaboration-error" role="alert">{error}</p>}
  </AppCard>
}

function DraftEditor({decision,members,pending,run}:{decision:Decision;members:Member[];pending:boolean;run:(operation:()=>Promise<Result>)=>void}){return <details><summary className="ws-button">Edit draft</summary><form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);run(()=>updateDecisionDraft({decisionId:decision.id,expectedVersion:decision.versionNumber,title:data.get("title"),statement:data.get("statement"),rationale:data.get("rationale"),requestedOutcome:data.get("outcome"),priority:data.get("priority"),approvalMode:data.get("mode"),ownerId:data.get("owner"),dueAt:data.get("dueAt")||null}))}}><label className="ws-field"><span>Title</span><input name="title" defaultValue={decision.title} required/></label><label className="ws-field"><span>Statement</span><textarea name="statement" defaultValue={decision.statement} required/></label><label className="ws-field"><span>Rationale</span><textarea name="rationale" defaultValue={decision.rationale} required/></label><label className="ws-field"><span>Requested outcome</span><textarea name="outcome" defaultValue={decision.requestedOutcome} required/></label><div className="ws-form-grid"><label className="ws-field"><span>Owner</span><select name="owner" defaultValue={decision.ownerId}>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="ws-field"><span>Priority</span><select name="priority" defaultValue={decision.priority}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="ws-field"><span>Mode</span><select name="mode" defaultValue={decision.approvalMode}><option>parallel</option><option>sequential</option></select></label><label className="ws-field"><span>Due</span><input name="dueAt" type="datetime-local" defaultValue={decision.dueAt?.slice(0,16)??""}/></label></div><button className="ws-button primary" disabled={pending}>Save draft</button></form></details>}
function ParticipantForm({decisionId,members,participants,pending,run}:{decisionId:string;members:Member[];participants:Participant[];pending:boolean;run:(operation:()=>Promise<Result>)=>void}){return <form className="ws-inline-create" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),role=String(data.get("role")) as "approver"|"reviewer",count=participants.filter(item=>item.role==="approver").length;run(()=>addDecisionParticipant({decisionId,userId:data.get("userId"),role,order:role==="approver"?count+1:null}))}}><label className="ws-field"><span>Add participant</span><select name="userId" required><option value="">Select active member</option>{members.map(member=><option value={member.id} key={member.id}>{member.name} · {member.role}</option>)}</select></label><label className="ws-field"><span>Role</span><select name="role"><option value="approver">Required approver</option><option value="reviewer">Reviewer</option></select></label><button className="ws-button" disabled={pending}>Add</button></form>}
function ReorderControls({decisionId,approvers,pending,run}:{decisionId:string;approvers:Participant[];pending:boolean;run:(operation:()=>Promise<Result>)=>void}){const ordered=[...approvers].sort((a,b)=>(a.order??0)-(b.order??0));const move=(index:number,direction:-1|1)=>{const next=[...ordered],target=index+direction;[next[index],next[target]]=[next[target],next[index]];run(()=>reorderDecisionApprovers({decisionId,userIds:next.map(item=>item.userId)}))};return <div className="ws-reorder-list" aria-label="Sequential approver order">{ordered.map((participant,index)=><div key={participant.id}><span>{index+1}. {participant.name}</span><button className="ws-button" disabled={pending||index===0} onClick={()=>move(index,-1)} aria-label={`Move ${participant.name} earlier`}>↑</button><button className="ws-button" disabled={pending||index===ordered.length-1} onClick={()=>move(index,1)} aria-label={`Move ${participant.name} later`}>↓</button></div>)}</div>}
function ResponseForm({pending,onRespond}:{pending:boolean;onRespond:(state:"approved"|"rejected"|"changes_requested"|"abstained",comment:string|null)=>void}){const [comment,setComment]=useState("");return <div className="ws-response-form"><label className="ws-field"><span>Approval comment</span><textarea value={comment} onChange={event=>setComment(event.target.value)} maxLength={2000}/></label><div className="ws-action-bar"><button className="ws-button primary" disabled={pending} onClick={()=>onRespond("approved",comment||null)}>Approve</button><button className="ws-button" disabled={pending||!comment.trim()} onClick={()=>onRespond("changes_requested",comment)}>Request changes</button><button className="ws-button danger" disabled={pending||!comment.trim()} onClick={()=>onRespond("rejected",comment)}>Reject</button><button className="ws-button" disabled={pending} onClick={()=>onRespond("abstained",comment||null)}>Abstain</button></div></div>}
function ReviewCommentForm({pending,onComment}:{pending:boolean;onComment:(comment:string)=>void}){const [comment,setComment]=useState("");return <div className="ws-response-form"><label className="ws-field"><span>Reviewer comment</span><textarea value={comment} onChange={event=>setComment(event.target.value)} maxLength={2000}/></label><button className="ws-button" disabled={pending||!comment.trim()} onClick={()=>{onComment(comment);setComment("")}}>Add reviewer comment</button></div>}
function FinalizeForm({pending,onFinalize}:{pending:boolean;onFinalize:(summary:string)=>void}){const [summary,setSummary]=useState("");return <div className="ws-response-form"><label className="ws-field"><span>Final decision summary</span><textarea value={summary} onChange={event=>setSummary(event.target.value)} required/></label><button className="ws-button primary" disabled={pending||summary.trim().length<3} onClick={()=>onFinalize(summary)}>Record final summary</button></div>}
