import Link from "next/link";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {can} from "@/app/lib/auth/permissions";
import type {CollaborationEntityType} from "@/app/lib/collaboration/domain-events";
import {decisionRepository} from "@/app/lib/data/decision-repository";
import DecisionDraftForm from "./decision-draft-form";
import {AppCard,EmptyState,SectionHeader,StatusBadge} from "./ui";

export default async function EntityDecisions({entityType,entityId}:{entityType:CollaborationEntityType;entityId:string}){if(!process.env.DATABASE_URL)return null;const context=await requireWorkspaceContext(),repository=decisionRepository(context),[decisions,members]=await Promise.all([repository.byEntity({entityType,entityId}),repository.members()]),count=(status:string)=>decisions.filter(item=>item.status===status).length;return <section id="executive-decisions" className="ws-first-class-section"><AppCard className="ws-decisions"><SectionHeader title="Executive Decisions" description="Formal, attributable approvals connected to this workspace." action={<div className="ws-action-bar"><Link className="ws-button" href="/workspace/decisions">Decision Center</Link>{can(context.membership.role,"decision.create")&&<DecisionDraftForm entityType={entityType} entityId={entityId} members={members}/>}</div>}/><div className="ws-decision-summary"><span><small>Drafts</small><strong>{count("draft")}</strong></span><span><small>Pending approval</small><strong>{count("pending_approval")}</strong></span><span><small>Approved</small><strong>{count("approved")}</strong></span><span><small>Rejected</small><strong>{count("rejected")}</strong></span></div><div className="ws-decision-list">{decisions.slice(0,4).map(decision=><Link key={decision.id} href={`/workspace/decisions/${decision.id}`} className="ws-decision-card"><div><StatusBadge tone={decision.status}>{decision.status.replaceAll("_"," ")}</StatusBadge><h3>{decision.title}</h3><p>{decision.requestedOutcome}</p></div><span>Version {decision.versionNumber} →</span></Link>)}{!decisions.length&&<EmptyState title="No executive decisions yet" description="Create a decision when this record needs a formal, auditable commercial outcome."/>}</div></AppCard></section>}
