"use client";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createBusinessV2 as createBusiness,createCampaignV2 as createCampaign,createJourneyV2 as createJourney,createOpportunityV2 as createOpportunity} from "@/app/lib/actions/workspace-create-actions";
import {useCollaboration} from "./collaboration-state";
import {useBodyScrollLock} from "./use-body-scroll-lock";

type Member={id:string;name:string};type Business={id:string;name:string;category?:string;location?:string};type Industry={id:string;name:string};type Region={id:string;name:string;country:string};
const categories=["Hospitality","Hotel and Accommodation","Restaurant and Dining","Mobility and Transport","Tourism and Experiences","Retail and Shopping","Entertainment and Events","Wellness","Technology","Financial Services","Real Estate","Government and Public Sector","Other"];
const emirates=["Ras Al Khaimah","Dubai","Abu Dhabi","Sharjah","Ajman","Fujairah","Umm Al Quwain"];
const opportunityTypes=["Partnership","Revenue","Campaign","Tourism experience","Payment acceptance","Membership","Rewards","Mobility","Hospitality","Retail","Technology integration","Other"];
const campaignObjectives=["Awareness","Engagement","Lead generation","Business acquisition","Event promotion","Tourism activation","Customer retention","Partner activation","Other"];
const journeyTypes=["Visitor arrival","Hospitality stay","Dining","Retail","Event","Wellness","Mobility","Multi-destination","Loyalty and rewards","Other"];
const copy={business:"Add the essential details now. You can complete contacts, services, opportunities and relationships from the business workspace.",opportunity:"Capture the commercial opportunity first. Add participants, decisions and execution details after creation.",campaign:"Start with the objective and schedule. Add participants and performance details as the campaign develops.",journey:"Define the experience. Add connected businesses and touchpoints from the journey workspace."};

export default function EntityCreateDialog({kind,members:providedMembers=[],businesses:providedBusinesses=[],industries:providedIndustries=[],regions:providedRegions=[],allowed}:{kind:"business"|"opportunity"|"campaign"|"journey";members?:Member[];businesses?:Business[];industries?:Industry[];regions?:Region[];allowed:boolean}){
 const workspace=useCollaboration().data,members=providedMembers.length?providedMembers:workspace.users.map(item=>({id:item.id,name:item.name})),businesses=providedBusinesses.length?providedBusinesses:workspace.businesses.map(item=>({id:item.id,name:item.name,category:item.category,location:item.location})),industries=providedIndustries.length?providedIndustries:workspace.industries.map(item=>({id:item.id,name:item.name})),regions=providedRegions.length?providedRegions:workspace.regions.map(item=>({id:item.id,name:item.name,country:item.country}));
 const canCreate=allowed;
 const dialog=useRef<HTMLDialogElement>(null),first=useRef<HTMLInputElement>(null),router=useRouter(),[pending,start]=useTransition(),[error,setError]=useState(""),[description,setDescription]=useState(""),[category,setCategory]=useState(""),[country,setCountry]=useState("United Arab Emirates"),[campaignStep,setCampaignStep]=useState(0),[isOpen,setIsOpen]=useState(false);
 const labels={business:"Add business",opportunity:"Create opportunity",campaign:"New campaign",journey:"New journey"},routes={business:"businesses",opportunity:"opportunities",campaign:"campaigns",journey:"journeys"};
 useBodyScrollLock(isOpen);
 const open=()=>{if(!canCreate||dialog.current?.open)return;setIsOpen(true);dialog.current?.showModal();requestAnimationFrame(()=>{const candidate=dialog.current?.querySelector<HTMLElement>(".ws-modal-body [name]:not([type='hidden'])");candidate?.focus()})};
 const close=()=>{if(pending)return;dialog.current?.close();setIsOpen(false);setError("");setCampaignStep(0)};
 const advanceCampaign=()=>{const section=dialog.current?.querySelectorAll<HTMLElement>(".ws-form-section")[campaignStep],invalid=section?.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(":invalid");if(invalid){invalid.reportValidity();invalid.focus();return}setCampaignStep(value=>value+1)};
 if(!canCreate)return <button className="ws-button ws-disabled-action" type="button" disabled title="Your workspace role has read-only access to this feature">{labels[kind]}</button>;
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);start(async()=>{setError("");const result=kind==="business"?await createBusiness({name:form.get("name"),category:category==="Other"?form.get("customCategory"):category,location:[form.get("address"),form.get("city"),form.get("region"),country].filter(Boolean).join(", "),regionId:form.get("regionId")||null,description:form.get("description"),industryId:form.get("industryId")||null}):kind==="opportunity"?await createOpportunity({title:form.get("title"),summary:form.get("summary"),commercialReasoning:form.get("reasoning"),journeyImpact:form.get("journeyImpact"),priority:form.get("priority"),stage:form.get("stage"),ownerId:form.get("ownerId")||null,modeledValue:form.get("modeledValue"),businessIds:form.getAll("businessIds")}):kind==="campaign"?await createCampaign({title:form.get("title"),objective:form.get("objective"),status:form.get("status"),budget:form.get("budget")||0,modeledValue:form.get("modeledValue")||0,startDate:form.get("startDate"),endDate:form.get("endDate"),businessIds:form.getAll("businessIds")}):await createJourney({name:form.get("name"),journeyType:form.get("journeyType"),objective:form.get("objective"),target:form.get("target"),outcome:form.get("outcome"),businessIds:form.getAll("businessIds")});if(!result.ok)setError(result.error);else{dialog.current?.close();setIsOpen(false);router.push(`/workspace/${routes[kind]}/${result.id}`);router.refresh()}})};
 return <><button className="ws-button primary" type="button" onClick={open}>{labels[kind]}</button><dialog ref={dialog} className="ws-modal" aria-labelledby={`${kind}-create-title`} onCancel={event=>{if(pending)event.preventDefault();else close()}}><form className="ws-modal-shell" onSubmit={submit}><header><div><span>Create {kind}</span><h2 id={`${kind}-create-title`}>{labels[kind]}</h2><p>{copy[kind]}</p></div><button type="button" onClick={close} aria-label="Close creation dialog">×</button></header><div className="ws-modal-body">
 {kind==="business"&&<><Field inputRef={first} label="Business name" name="name" minLength={2} maxLength={160}/><div className="ws-form-grid"><label className="ws-field"><span>Category</span><select required value={category} onChange={event=>setCategory(event.target.value)}><option value="" disabled>Select category</option>{[...new Set([...businesses.map(item=>item.category).filter(Boolean) as string[],...categories])].map(item=><option key={item}>{item}</option>)}</select><small className="ws-field-help">What the business does within the ecosystem.</small></label>{category==="Other"&&<Field label="Custom category" name="customCategory" maxLength={120}/>}<label className="ws-field"><span>Industry</span><select name="industryId"><option value="">Not specified</option>{industries.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><small className="ws-field-help">The broader commercial sector used for analysis.</small></label></div><div className="ws-form-grid"><label className="ws-field"><span>Country</span><input name="country" list="country-options" value={country} onChange={event=>setCountry(event.target.value)} required/><datalist id="country-options"><option>United Arab Emirates</option><option>Saudi Arabia</option><option>Oman</option><option>Bahrain</option><option>Qatar</option><option>Kuwait</option></datalist></label><label className="ws-field"><span>Region, emirate, state or province</span>{country==="United Arab Emirates"?<select name="region" required defaultValue="Ras Al Khaimah">{emirates.map(item=><option key={item}>{item}</option>)}</select>:<input name="region" required maxLength={120}/>}</label><label className="ws-field"><span>City or locality</span><input name="city" list="locality-options" required maxLength={120}/><datalist id="locality-options">{[...new Set(businesses.map(item=>item.location).filter(Boolean))].map(item=><option key={item}>{item}</option>)}</datalist></label><Field label="Address or venue description" name="address" required={false} maxLength={180}/><label className="ws-field"><span>Platform region</span><select name="regionId"><option value="">Automatically match where available</option>{regions.filter(item=>!country||item.country===country||item.country==="UAE").map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><label className="ws-field"><span>Description</span><textarea name="description" required minLength={20} maxLength={600} value={description} onChange={event=>setDescription(event.target.value)} placeholder="Briefly describe the business, its customers, and how it may contribute to the ecosystem."/><small className="ws-char-count"><span>80–300 characters recommended</span><span>{description.length}/600</span></small>{description.length>0&&description.length<20&&<small className="ws-form-error">Add at least 20 characters.</small>}</label></>}
 {kind==="opportunity"&&<><section className="ws-form-section"><h3>Basics</h3><Field inputRef={first} label="Opportunity title" name="title" minLength={3} maxLength={180}/><div className="ws-form-grid"><label className="ws-field"><span>Opportunity type</span><select name="opportunityType" defaultValue="Partnership">{opportunityTypes.map(item=><option key={item}>{item}</option>)}</select></label><label className="ws-field"><span>Priority</span><select name="priority" defaultValue="MEDIUM"><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label className="ws-field"><span>Current stage</span><select name="stage" defaultValue="IDENTIFIED"><option value="IDENTIFIED">Identified</option><option value="QUALIFIED">Qualified</option></select></label></div><EntityChecks businesses={businesses} required/></section><section className="ws-form-section"><h3>Strategic context</h3><Field label="Short opportunity statement" name="summary" multiline minLength={10} maxLength={600}/><Field label="Business rationale" name="reasoning" multiline minLength={10} maxLength={1200}/><Field label="Expected outcome" name="journeyImpact" multiline minLength={10} maxLength={800}/><label className="ws-field"><span>Owner</span><select name="ownerId"><option value="">Unassigned</option>{members.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label></section><details className="ws-optional-details"><summary>Additional commercial details</summary><div><Field label="Estimated value (AED)" name="modeledValue" type="number" required={false}/><p className="ws-field-help">Currency, probability and decision-date fields are not yet persisted by the current opportunity model.</p></div></details></>}
 {kind==="campaign"&&<><div className="ws-campaign-steps" aria-label="Campaign creation progress">{["Objective","Details","Participants and value"].map((item,index)=><span className={index===campaignStep?"active":""} aria-current={index===campaignStep?"step":undefined} key={item}>{index+1}. {item}</span>)}</div><section hidden={campaignStep!==0} className="ws-form-section"><h3>Choose an objective</h3><label className="ws-field"><span>Campaign objective</span><select name="objectiveType" defaultValue="Awareness">{campaignObjectives.map(item=><option key={item}>{item}</option>)}</select></label><Field label="Target outcome" name="objective" multiline minLength={10} maxLength={800}/></section><section hidden={campaignStep!==1} className="ws-form-section"><h3>Campaign details</h3><Field inputRef={first} label="Campaign name" name="title" minLength={3} maxLength={180}/><div className="ws-form-grid"><Field label="Start date" name="startDate" type="date"/><Field label="End date" name="endDate" type="date"/><label className="ws-field"><span>Status</span><select name="status" defaultValue="DRAFT"><option value="DRAFT">Draft</option><option value="PENDING">Pending</option></select></label></div><p className="ws-field-help">Campaign ownership is not stored by the current campaign model.</p></section><section hidden={campaignStep!==2} className="ws-form-section"><h3>Participants and value</h3><EntityChecks businesses={businesses} required/><div className="ws-form-grid"><Field label="Budget (AED)" name="budget" type="number" required={false}/><Field label="Modeled value (AED)" name="modeledValue" type="number" required={false}/></div></section></>}
 {kind==="journey"&&<><Field inputRef={first} label="Journey name" name="name" minLength={3} maxLength={180}/><label className="ws-field"><span>Journey type</span><select name="journeyType" defaultValue="Visitor arrival">{journeyTypes.map(item=><option key={item}>{item}</option>)}</select></label><Field label="Journey objective" name="objective" multiline minLength={10} maxLength={600}/><Field label="Target customer or visitor" name="target" maxLength={240}/><Field label="Intended outcome" name="outcome" multiline minLength={10} maxLength={600}/><EntityChecks businesses={businesses}/><p className="ws-form-help">Touchpoints can be added after creation from the journey workspace. The current database stores the journey name initially; supporting context is used to create its first planning stage.</p></>}
 {error&&<p className="ws-collaboration-error" role="alert">{error}</p>}</div><footer><button type="button" className="ws-button" onClick={close} disabled={pending}>Cancel</button>{kind==="campaign"&&campaignStep>0&&<button type="button" className="ws-button" onClick={()=>setCampaignStep(value=>value-1)} disabled={pending}>Back</button>}{kind==="campaign"&&campaignStep<2?<button type="button" className="ws-button primary" onClick={advanceCampaign}>Continue</button>:<button className="ws-button primary" disabled={pending}>{pending?"Creating…":kind==="campaign"?"Save draft":labels[kind]}</button>}</footer></form></dialog></>;
}
function Field({label,name,multiline=false,type="text",required=true,minLength,maxLength,inputRef}:{label:string;name:string;multiline?:boolean;type?:string;required?:boolean;minLength?:number;maxLength?:number;inputRef?:React.Ref<HTMLInputElement>}){const isRequired=type==="date"?false:required;return <label className="ws-field"><span>{label}</span>{multiline?<textarea name={name} required={isRequired} minLength={minLength} maxLength={maxLength}/>:<input ref={inputRef} name={name} type={type} required={isRequired} minLength={minLength} maxLength={maxLength} min={type==="number"?0:undefined}/>}</label>}
function EntityChecks({businesses,required=false}:{businesses:Business[];required?:boolean}){return <fieldset className="ws-check-grid"><legend>Connected businesses{required?" (select at least one)":" (optional)"}</legend>{businesses.map(item=><label key={item.id}><input type="checkbox" name="businessIds" value={item.id}/><span>{item.name}</span></label>)}</fieldset>}
