"use client";
import {createContext,useCallback,useContext,useMemo,useState,useTransition,type ReactNode} from "react";
import {useRouter} from "next/navigation";
import {createPilotRecord,createPilotTask,createPilotUpdate,recordPilotDecision,updatePilotExecution,updatePilotKpi,updatePilotParticipant} from "@/app/lib/actions/workspace-mutations";
import type {Pilot,PilotApproval,PilotDecision,PilotKPI,PilotMilestone,PilotParticipant,PilotRisk,PilotTask,PilotUpdate} from "../../_lib/models";
import {useCollaboration} from "./collaboration-state";
import {useRenderLifecycleDiagnostics} from "@/app/components/render-lifecycle-diagnostics";
type PilotContextValue={pilots:Pilot[];createPilot:(pilot:Pilot)=>void;updateParticipant:(pilotId:string,businessId:string,update:Partial<PilotParticipant>)=>void;updateMilestone:(pilotId:string,id:string,update:Partial<PilotMilestone>)=>void;updateTask:(pilotId:string,id:string,update:Partial<PilotTask>)=>void;addTask:(pilotId:string,task:PilotTask)=>void;updateKPI:(pilotId:string,id:string,update:Pick<PilotKPI,"current"|"status">)=>void;updateApproval:(pilotId:string,id:string,update:Partial<PilotApproval>)=>void;updateRisk:(pilotId:string,id:string,update:Partial<PilotRisk>)=>void;addUpdate:(pilotId:string,update:PilotUpdate)=>void;addDecision:(pilotId:string,decision:PilotDecision)=>void};
const PilotContext=createContext<PilotContextValue|null>(null);
export function PilotProvider({children,initialPilots}:{children:ReactNode;initialPilots:Pilot[]}){
 useRenderLifecycleDiagnostics("PilotProvider");
 const [pilots,setPilots]=useState(initialPilots);
 const [,startTransition]=useTransition();const router=useRouter();
 const {addDecision:addWorkspaceDecision}=useCollaboration();
 const updateCollection=useCallback((pilotId:string,key:"participants"|"milestones"|"tasks"|"kpis"|"approvals"|"risks",idKey:string,id:string,update:object)=>setPilots(current=>current.map(pilot=>pilot.id===pilotId?{...pilot,[key]:(pilot[key] as unknown as Array<Record<string,unknown>>).map(item=>item[idKey]===id?{...item,...update}:item)}:pilot)),[]);
 const persistExecution=(input:{kind:"milestone"|"task"|"approval"|"risk";id:string;status:string;completion?:number;blocked?:boolean})=>startTransition(async()=>{await updatePilotExecution({...input,status:input.status.toUpperCase().replaceAll(" ","_")});router.refresh()});
 // eslint-disable-next-line react-hooks/exhaustive-deps -- persistExecution delegates to a stable transition and router refresh.
 const value=useMemo<PilotContextValue>(()=>({pilots,createPilot:pilot=>{setPilots(current=>[pilot,...current]);startTransition(async()=>{await createPilotRecord({id:pilot.id,name:pilot.name,opportunityId:pilot.opportunityId,ownerId:pilot.ownerId,objective:pilot.objective,startDate:pilot.startDate,endDate:pilot.endDate,reviewDate:pilot.reviewDate,participants:pilot.participants});router.refresh()})},updateParticipant:(pilotId,id,update)=>{updateCollection(pilotId,"participants","businessId",id,update);if(update.status)startTransition(async()=>{await updatePilotParticipant({pilotId,businessId:id,status:update.status!.toUpperCase()});router.refresh()})},updateMilestone:(pilotId,id,update)=>{updateCollection(pilotId,"milestones","id",id,update);if(update.status)persistExecution({kind:"milestone",id,status:update.status,completion:update.completion})},updateTask:(pilotId,id,update)=>{updateCollection(pilotId,"tasks","id",id,update);if(update.status)persistExecution({kind:"task",id,status:update.status,blocked:update.blocked})},addTask:(pilotId,task)=>{setPilots(current=>current.map(pilot=>pilot.id===pilotId?{...pilot,tasks:[...pilot.tasks,task]}:pilot));startTransition(async()=>{await createPilotTask({id:task.id,pilotId,title:task.title,description:task.description,assigneeId:task.assigneeId||null,dueDate:task.dueDate,priority:task.priority.toUpperCase(),status:task.status.toUpperCase().replaceAll(" ","_"),milestoneId:task.milestoneId||null,businessId:task.businessId??null,blocked:task.blocked});router.refresh()})},updateKPI:(pilotId,id,update)=>{updateCollection(pilotId,"kpis","id",id,update);startTransition(async()=>{await updatePilotKpi({id,current:update.current,status:update.status.toUpperCase().replaceAll(" ","_")});router.refresh()})},updateApproval:(pilotId,id,update)=>{updateCollection(pilotId,"approvals","id",id,update);if(update.status)persistExecution({kind:"approval",id,status:update.status})},updateRisk:(pilotId,id,update)=>{updateCollection(pilotId,"risks","id",id,update);if(update.status)persistExecution({kind:"risk",id,status:update.status})},addUpdate:(pilotId,update)=>{setPilots(current=>current.map(pilot=>pilot.id===pilotId?{...pilot,updates:[update,...pilot.updates]}:pilot));startTransition(async()=>{await createPilotUpdate({id:update.id,pilotId,type:update.type,detail:update.detail});router.refresh()})},addDecision:(pilotId,decision)=>{setPilots(current=>current.map(pilot=>pilot.id===pilotId?{...pilot,decisions:[decision,...pilot.decisions]}:pilot));addWorkspaceDecision({action:decision.decision,detail:`${decision.reason} Next: ${decision.nextAction}`,type:"pilot"});startTransition(async()=>{await recordPilotDecision({pilotId,decision:decision.decision,reason:decision.reason,evidence:decision.evidence,impact:decision.impact,nextAction:decision.nextAction});router.refresh()})}}),[pilots,updateCollection,addWorkspaceDecision,router]);
 return <PilotContext.Provider value={value}>{children}</PilotContext.Provider>
}
export function usePilots(){const value=useContext(PilotContext);if(!value)throw new Error("usePilots must be used within PilotProvider");return value}
