"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import FinancialSubnav from "../components/financial-subnav";

const streams=[
  ["Merchant Subscriptions","Recurring Starter, Growth and Enterprise platform access.","28%"],
  ["Referral Commissions","Performance revenue generated when verified referrals convert.","21%"],
  ["Campaign Fees","Commercial fees for building, managing and optimizing joint campaigns.","12%"],
  ["Sponsored Placements","Premium visibility in discovery and partner recommendation surfaces.","8%"],
  ["Merchant Verification","Trusted-network verification and onboarding services.","5%"],
  ["Analytics & Intelligence","Advanced reporting and AI commercial opportunity analysis.","15%"],
  ["API Access","Enterprise access to referral, rewards and merchant infrastructure.","4%"],
  ["White-label Licensing","Branded ecosystem platforms for destinations and operators.","3%"],
  ["Enterprise Integrations","Implementation and systems integration for strategic clients.","3%"],
  ["Future Transaction Infrastructure","Optional future services supporting settlement and connected commerce.","1%"],
];

export default function BusinessModelOverview(){
  return <main className="min-h-screen bg-[#F7F5F9] text-[#1B1725]"><FinancialSubnav/><section className="financial-hero relative overflow-hidden px-5 py-20"><div className="engine-grid absolute inset-0"/><div className="relative mx-auto max-w-[1180px]"><span className="inline-flex rounded-full border border-[#DDD3F8] bg-white/70 px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#5E3BEE]">Leadership brief</span><h1 className="mt-7 max-w-5xl text-5xl font-semibold tracking-[-.06em] sm:text-7xl">How NEFE creates durable commercial revenue.</h1><p className="mt-6 max-w-2xl text-[12px] leading-6 text-[#746D7A]">A strategic view of the recurring, performance and enterprise economics that power the connected-business network.</p><div className="mt-8 flex flex-wrap gap-2"><Link href="/financial-model" className="rounded-xl bg-[#5E3BEE] px-5 py-3 text-[8px] font-bold text-white">Open Financial Model →</Link><Link href="/pricing" className="rounded-xl border border-[#DDD7E3] bg-white px-5 py-3 text-[8px] font-bold">View Merchant Pricing</Link></div></div></section><div className="page-shell py-14">
    <section><p className="engine-eyebrow">Revenue architecture</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Diversified by design.</h2><p className="mt-4 max-w-3xl text-[10px] leading-5 text-[#7C7581]">NEFE combines predictable subscription revenue with aligned performance fees and higher-value enterprise services. No single stream carries the entire model.</p><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{streams.map(([name,description,share])=><motion.article whileHover={{y:-4}} key={name} className="finance-card p-5"><div className="flex items-start justify-end"><b className="rounded-full bg-[#FFF4DA] px-2 py-1 text-[7px] text-[#946B1E]">{share} mix</b></div><h3 className="mt-4 text-[12px] font-semibold">{name}</h3><p className="mt-2 text-[8px] leading-4 text-[#89828E]">{description}</p></motion.article>)}</div></section>
    <section className="mt-20 rounded-[30px] bg-[#171120] p-7 text-white sm:p-10"><p className="text-[8px] font-bold uppercase tracking-[.15em] text-[#BDA8F1]">Clear revenue flow</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.045em]">Activity becomes measurable platform value.</h2><div className="mt-9 grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] lg:items-center">{[["Businesses subscribe","Predictable recurring access revenue"],["Partners collaborate","Campaign and intelligence revenue"],["Customers convert","Referral commission and merchant value"],["Network scales","Enterprise, API and licensing revenue"]].map(([title,detail],index)=><div key={title} className="contents"><motion.div initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} transition={{delay:index*.08}} className="rounded-[18px] border border-white/10 bg-white/[.055] p-5"><span className="text-[7px] font-bold text-[#D8B75F]">0{index+1}</span><h3 className="mt-3 text-[11px] font-semibold">{title}</h3><p className="mt-2 text-[7px] leading-4 text-white/40">{detail}</p></motion.div>{index<3&&<span className="hidden text-[#8A68E8] lg:block">→</span>}</div>)}</div></section>
    <section className="mt-20 grid gap-4 lg:grid-cols-3"><div className="finance-card p-6"><p className="engine-eyebrow">Recurring foundation</p><p className="mt-4 text-4xl font-bold">34%</p><p className="mt-2 text-[8px] leading-4 text-[#8A838F]">Target share from subscriptions and analytics as merchant adoption matures.</p></div><div className="finance-card p-6"><p className="engine-eyebrow">Aligned performance</p><p className="mt-4 text-4xl font-bold">33%</p><p className="mt-2 text-[8px] leading-4 text-[#8A838F]">Referral, campaign and placement revenue rises with measurable merchant outcomes.</p></div><div className="finance-card p-6"><p className="engine-eyebrow">Enterprise expansion</p><p className="mt-4 text-4xl font-bold">33%</p><p className="mt-2 text-[8px] leading-4 text-[#8A838F]">APIs, white-label licensing and integrations unlock larger commercial agreements.</p></div></section>
  </div></main>
}
