"use client";

import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { useMemo, useState } from "react";

type Inputs = { businesses:number; visitors:number; conversion:number; spend:number; referrals:number; subscriptions:number; campaigns:number };
type Scenario = "Conservative"|"Expected"|"Aggressive"|"Enterprise";

const revenueStreams = [
  ["Merchant Subscription Plans","Recurring access to NEFE discovery, campaigns and intelligence.",28,358000,78,34],
  ["Referral Commission","Performance-based commission on verified cross-business referrals.",21,269000,86,41],
  ["Campaign Management Fees","Creation, optimization and reporting for joint merchant campaigns.",12,154000,73,29],
  ["Sponsored Placement","Premium visibility within discovery and partner recommendation surfaces.",8,102000,88,25],
  ["Merchant Verification","Commercial verification and trusted-network onboarding services.",5,64000,81,18],
  ["AI Commercial Intelligence","Premium opportunity scoring, forecasts and commercial recommendations.",9,115000,84,47],
  ["Advanced Analytics","Network, campaign and customer intelligence subscriptions.",6,77000,87,32],
  ["API Access","Enterprise access to merchant, referral and rewards infrastructure.",4,51000,91,38],
  ["White-label Licensing","Branded ecosystem platforms for enterprise operators and destinations.",3,38000,76,54],
  ["Enterprise Integrations","Implementation and systems integration for strategic clients.",3,38000,68,24],
  ["Future Token Utility Services","Utility-based fee benefits, credits and verified ecosystem services.",1,13000,82,16],
] as const;

const pricing = [
  {name:"Starter",price:"AED 299",tone:"light",features:["Business listing","Basic analytics","Referral participation","Merchant dashboard"]},
  {name:"Growth",price:"AED 999",tone:"purple",popular:true,features:["Everything in Starter","AI recommendations","Campaign Builder","Referral Intelligence","Commercial dashboard","Partner discovery"]},
  {name:"Enterprise",price:"Custom Pricing",tone:"dark",features:["Unlimited locations","API access","White-label platform","Dedicated support","Commercial AI","Custom integrations","Priority onboarding"]},
];

const unitEconomics = [["Merchant Acquisition Cost","AED 2,850"],["Merchant Lifetime Value","AED 42,600"],["Average Revenue / Merchant","AED 1,174"],["Customer Lifetime Value","AED 8,940"],["Customer Acquisition Cost","AED 184"],["Gross Margin","82%"],["Referral Margin","86%"],["Monthly Churn","2.1%"],["Retention Rate","92.4%"],["Average Payback Period","3.4 months"]];
const comparison = [
  ["Identity","Siloed merchant accounts","Portable verified merchant identity"],
  ["Payments","Separate processors","Future connected payment utility"],
  ["Settlement","Manual reconciliation","Programmable settlement infrastructure"],
  ["Rewards","Closed loyalty points","Cross-business utility and rewards"],
  ["Loyalty","Single-brand retention","Network-wide customer value"],
  ["Merchant Trust","Manual due diligence","Verified ecosystem credentials"],
  ["Automation","Platform-specific rules","Shared commercial automation"],
  ["Partner Verification","Fragmented documents","Reusable verification layer"],
  ["Commercial Intelligence","Single-business analytics","Ecosystem opportunity intelligence"],
  ["Cross-business Collaboration","Manual partnerships","Native partnership infrastructure"],
];

const scenarioData:Record<Scenario,{revenue:number;profit:number;growth:number;cities:number;countries:number;volume:number;valuation:number}>={
  Conservative:{revenue:8.4,profit:1.7,growth:420,cities:2,countries:1,volume:74,valuation:42},
  Expected:{revenue:18.8,profit:6.2,growth:1247,cities:5,countries:2,volume:168,valuation:96},
  Aggressive:{revenue:41.6,profit:17.9,growth:3200,cities:11,countries:5,volume:385,valuation:225},
  Enterprise:{revenue:82.4,profit:39.8,growth:7800,cities:24,countries:9,volume:910,valuation:510},
};

const markets = [
  {year:"2026",country:"United Arab Emirates",x:58,y:48,merchants:"1,250",opportunity:"AED 3.8B",revenue:"AED 18.8M",readiness:"92%",investment:"AED 6.2M",score:94},
  {year:"2027",country:"Saudi Arabia",x:53,y:47,merchants:"3,800",opportunity:"AED 9.6B",revenue:"AED 46M",readiness:"78%",investment:"AED 12M",score:88},
  {year:"2027",country:"Qatar",x:56,y:46,merchants:"980",opportunity:"AED 2.1B",revenue:"AED 11M",readiness:"81%",investment:"AED 4.8M",score:86},
  {year:"2028",country:"Egypt",x:48,y:44,merchants:"4,200",opportunity:"AED 5.4B",revenue:"AED 34M",readiness:"64%",investment:"AED 10M",score:79},
  {year:"2028",country:"Kuwait",x:55,y:43,merchants:"1,100",opportunity:"AED 2.8B",revenue:"AED 14M",readiness:"73%",investment:"AED 5.5M",score:83},
  {year:"2029",country:"Singapore",x:78,y:62,merchants:"2,400",opportunity:"AED 7.2B",revenue:"AED 39M",readiness:"69%",investment:"AED 14M",score:85},
  {year:"2029",country:"Malaysia",x:76,y:61,merchants:"3,600",opportunity:"AED 6.5B",revenue:"AED 42M",readiness:"62%",investment:"AED 13M",score:80},
  {year:"2030",country:"Europe",x:42,y:30,merchants:"18,000",opportunity:"AED 38B",revenue:"AED 190M",readiness:"48%",investment:"AED 42M",score:76},
  {year:"2030",country:"North America",x:20,y:34,merchants:"24,000",opportunity:"AED 64B",revenue:"AED 310M",readiness:"41%",investment:"AED 68M",score:73},
];

const money = (value:number) => value>=1e6?`AED ${(value/1e6).toFixed(1)}M`:`AED ${Math.round(value/1000)}K`;

export default function BusinessModel(){
  const [inputs,setInputs]=useState<Inputs>({businesses:1247,visitors:48000,conversion:24,spend:620,referrals:38,subscriptions:61,campaigns:310});
  const [scenario,setScenario]=useState<Scenario>("Expected");
  const [market,setMarket]=useState(markets[0]);
  const [toast,setToast]=useState("");
  const model=useMemo(()=>{
    const subscription=inputs.businesses*(299+(inputs.subscriptions/100)*700);
    const referralVolume=inputs.visitors*(inputs.referrals/100)*(inputs.conversion/100)*inputs.spend;
    const referralIncome=referralVolume*.055;
    const campaignIncome=inputs.campaigns*1450;
    const enterprise=inputs.businesses*.045*4800;
    const platform=subscription+referralIncome+campaignIncome+enterprise;
    const merchant=referralVolume*.945;
    const gross=platform*.82;
    return {mrr:platform,arr:platform*12,platform,merchant,gross,margin:(gross-platform*.59)/platform*100,referralIncome,enterprise};
  },[inputs]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2300)};
  const kpis=[
    ["Monthly Recurring Revenue",money(model.mrr),"+18.4%"],
    ["Annual Recurring Revenue",money(model.arr),"+22.1%"],
    ["Total Merchant Revenue",money(model.merchant),"+27.6%"],
    ["Platform Revenue",money(model.platform),"+19.8%"],
    ["Average Revenue / Merchant",`AED ${Math.round(model.platform/inputs.businesses).toLocaleString()}`,"+12.2%"],
    ["Gross Margin","82%","+3.4 pts"],
    ["Commercial Growth","34.8%","+8.2 pts"],
    ["Customer Retention","92.4%","+4.1 pts"],
    ["Active Businesses",inputs.businesses.toLocaleString(),"+184"],
    ["Average Partnership Value","AED 14,850","+16.7%"],
  ];
  const referralStages:[string,number,number,number,number][]=[
    ["Hotel",1450,82,45,42],["Restaurant",380,26,14,38],["Luxury Experience",920,68,37,34],["Car Rental",680,52,29,31],["Airport Transfer",220,18,10,28],
  ];
  const merchantFlow=referralStages.reduce((sum,stage)=>sum+stage[1],0);
  const nefeFlow=referralStages.reduce((sum,stage)=>sum+stage[3],0);

  return <main className="financial-model min-h-screen bg-[#F6F4F8] text-[#1B1725]">
    <section className="financial-hero relative overflow-hidden border-b border-[#E5DFE9] px-4 py-14 sm:px-7 lg:px-9"><div className="engine-grid absolute inset-0"/><div className="relative mx-auto max-w-[1540px]"><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#DDD3F8] bg-white/70 px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#5E3BEE] backdrop-blur"><i className="h-2 w-2 animate-pulse rounded-full bg-[#41AF84]"/>Financial model · Live assumptions</span><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Financial Intelligence &amp; Business Model</h1><p className="mt-4 max-w-3xl text-[12px] leading-6 text-[#746D7A]">A transparent view of how NEFE generates revenue, scales commercially and builds a sustainable connected-business platform.</p></div><div className="flex flex-wrap gap-2"><Link href="/opportunity-engine" className="rounded-xl border border-[#DED8E4] bg-white px-4 py-3 text-[8px] font-semibold">← Opportunity Engine</Link><button onClick={()=>notify("Board report prepared")} className="rounded-xl bg-[#21172F] px-5 py-3 text-[8px] font-semibold text-white shadow-xl">Export Board Report ↗</button></div></div></div></section>

    <div className="mx-auto max-w-[1540px] px-4 py-10 sm:px-7 lg:px-9">
      <SectionHeader number="01" eyebrow="Executive Revenue Overview" title="The commercial model at a glance."/>
      <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{kpis.map(([label,value,trend],index)=><motion.article whileHover={{y:-4}} key={label} className="finance-card p-4"><div className="flex items-center justify-between"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#F0ECFF] text-[7px] font-bold text-[#5E3BEE]">0{index+1}</span><span className="rounded-full bg-[#EAF8F2] px-2 py-1 text-[6px] font-bold text-[#278D69]">{trend}</span></div><p className="mt-5 text-[7px] text-[#908995]">{label}</p><AnimatePresence mode="popLayout"><motion.p key={value} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} className="mt-2 text-lg font-bold tracking-[-.035em]">{value}</motion.p></AnimatePresence><div className="mt-4 flex h-7 items-end gap-1">{[35,48,43,62,58,76,84].map((height,i)=><i key={i} className="chart-bar flex-1 rounded-t bg-gradient-to-t from-[#5E3BEE]/25 to-[#8060E7]" style={{height:`${Math.min(100,height+index)}%`,animationDelay:`${i*45}ms`}}/>)}</div></motion.article>)}</section>

      <section className="mt-20"><SectionHeader number="02" eyebrow="Revenue Streams" title="Diversified recurring and performance-based revenue."/><div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{revenueStreams.map(([name,description,share,monthly,margin,growth],index)=><motion.article whileHover={{y:-4}} key={name} className="finance-card p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#F0ECFF] text-[8px] font-bold text-[#5E3BEE]">0{index+1}</span><b className="rounded-full bg-[#FFF5DD] px-2 py-1 text-[7px] text-[#956D20]">{share}% mix</b></div><h3 className="mt-5 text-[12px] font-semibold">{name}</h3><p className="mt-2 min-h-10 text-[8px] leading-4 text-[#89828F]">{description}</p><div className="mt-5 grid grid-cols-3 border-t border-[#EEEAF1] pt-4">{[[money(monthly),"Monthly"],[money(monthly*12),"Annual"],[`${margin}%`,"Margin"]].map(([value,label])=><div key={label}><p className="text-[9px] font-bold">{value}</p><p className="mt-1 text-[6px] text-[#9B94A0]">{label}</p></div>)}</div><div className="mt-4 flex items-center justify-between text-[7px]"><span className="text-[#9A939F]">Growth trend</span><b className="text-[#29916E]">↗ {growth}%</b></div></motion.article>)}</div></section>

      <section className="mt-20"><SectionHeader number="03" eyebrow="Merchant Pricing" title="Simple entry. Powerful commercial expansion."/><div className="mt-8 grid gap-4 lg:grid-cols-3">{pricing.map(plan=><motion.article whileHover={{y:-7}} key={plan.name} className={`relative overflow-hidden rounded-[27px] border p-7 ${plan.tone==="purple"?"border-[#7758D7] bg-gradient-to-br from-[#5E3BEE] to-[#2D1A60] text-white shadow-[0_25px_65px_rgba(75,43,158,.2)]":plan.tone==="dark"?"border-[#30273B] bg-[#19131F] text-white":"border-[#E3DEE7] bg-white"}`}>{plan.popular&&<span className="absolute right-5 top-5 rounded-full bg-[#D7B45D] px-3 py-1.5 text-[6px] font-bold text-[#3C2B0D]">MOST POPULAR</span>}<p className={`text-[8px] font-bold uppercase tracking-[.13em] ${plan.tone==="light"?"text-[#7055D0]":"text-white/50"}`}>{plan.name}</p><h3 className="mt-5 text-3xl font-semibold tracking-[-.04em]">{plan.price}</h3><p className={`mt-1 text-[7px] ${plan.tone==="light"?"text-[#99929E]":"text-white/35"}`}>{plan.name==="Enterprise"?"Annual commercial agreement":"per merchant, billed monthly"}</p><div className={`my-6 h-px ${plan.tone==="light"?"bg-[#EEEAF1]":"bg-white/10"}`}/><div className="space-y-3">{plan.features.map(feature=><p key={feature} className={`flex gap-3 text-[9px] ${plan.tone==="light"?"text-[#5E5765]":"text-white/65"}`}><span className={plan.tone==="purple"?"text-[#E2C36B]":"text-[#6747D3]"}>✓</span>{feature}</p>)}</div><button onClick={()=>notify(`${plan.name} pricing selected`)} className={`mt-8 w-full rounded-xl py-3 text-[8px] font-bold ${plan.tone==="purple"?"bg-white text-[#5032C4]":plan.tone==="dark"?"bg-[#6A46DD] text-white":"bg-[#F0ECFF] text-[#5E3BEE]"}`}>Select {plan.name}</button></motion.article>)}</div></section>

      <section className="mt-20"><SectionHeader number="04" eyebrow="Referral Economics" title="One customer. Multiple merchants. Shared value."/><div className="mt-8 overflow-x-auto pb-3"><div className="flex min-w-[1050px] items-stretch gap-3"><div className="grid w-32 shrink-0 place-items-center rounded-[22px] bg-[#171120] p-5 text-center text-white"><div><span className="text-xl text-[#D8B65E]">●</span><p className="mt-3 text-[9px] font-bold">Customer</p><p className="mt-1 text-[6px] text-white/35">NEFE member</p></div></div>{referralStages.map(([name,spend,merchantValue,commission,repeat],index)=><div key={name} className="relative flex flex-1 items-center"><motion.article initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} transition={{delay:index*.08}} className="finance-card w-full p-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#F0ECFF] text-[7px] font-bold text-[#5E3BEE]">0{index+1}</span><h3 className="mt-4 text-[10px] font-semibold">{name}</h3><div className="mt-4 space-y-2">{[["Customer spend",`AED ${spend}`],["Merchant revenue",`AED ${spend-commission}`],["Referral value",`AED ${merchantValue}`],["Platform commission",`AED ${commission}`],["Repeat probability",`${repeat}%`]].map(([label,value])=><div key={label} className="flex justify-between text-[6px]"><span className="text-[#9A939F]">{label}</span><b>{value}</b></div>)}</div></motion.article>{index<referralStages.length-1&&<span className="absolute -right-2.5 z-10 text-[#5E3BEE]">→</span>}</div>)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-[20px] bg-[#F0ECFF] p-5"><p className="text-[7px] uppercase text-[#755CCB]">Revenue generated for merchants</p><p className="mt-2 text-2xl font-bold text-[#4D34A4]">AED {(merchantFlow-nefeFlow).toLocaleString()}</p></div><div className="rounded-[20px] bg-[#171120] p-5 text-white"><p className="text-[7px] uppercase text-white/40">Revenue generated for NEFE</p><p className="mt-2 text-2xl font-bold text-[#E1BF68]">AED {nefeFlow.toLocaleString()}</p></div></div></section>

      <section className="mt-20 overflow-hidden rounded-[30px] bg-[#171120] p-6 text-white sm:p-9"><div className="commerce-grid absolute"/><SectionHeader number="05" eyebrow="Token Utility" title="Commercial utility without operational complexity." dark/><p className="mt-4 max-w-3xl text-[10px] leading-5 text-white/45">Merchants can operate entirely in AED. NEFE utility remains an optional commercial layer for fee efficiency, ecosystem participation and partner incentives—not a requirement for using the platform.</p><div className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-[22px] border border-white/10 bg-white/[.055] p-6"><p className="text-[8px] font-bold uppercase tracking-[.13em] text-white/40">Merchant pays in AED</p><h3 className="mt-3 text-2xl font-semibold">Standard platform access</h3><div className="mt-6 space-y-3">{["Transparent monthly billing","Standard campaign pricing","Full merchant platform access","Traditional settlement workflow"].map(item=><p key={item} className="flex gap-3 text-[9px] text-white/55"><span>○</span>{item}</p>)}</div></div><div className="rounded-[22px] border border-[#D0A74D]/30 bg-gradient-to-br from-[#9E7428]/20 to-[#6340D2]/20 p-6"><p className="text-[8px] font-bold uppercase tracking-[.13em] text-[#E0BE68]">Merchant uses NEFE utility</p><h3 className="mt-3 text-2xl font-semibold">Enhanced ecosystem benefits</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Lower platform fees","Campaign credits","Premium placement","Partner rewards","Future governance","Loyalty bonuses","Priority discovery"].map(item=><p key={item} className="flex gap-3 text-[9px] text-white/65"><span className="text-[#E0BE68]">✓</span>{item}</p>)}</div></div></div></section>

      <section className="mt-20"><SectionHeader number="06" eyebrow="Financial Projection Simulator" title="Change assumptions. See the business respond."/><div className="mt-7 grid gap-5 xl:grid-cols-[.78fr_1.22fr]"><div className="finance-card p-6">{([["businesses","Businesses",100,10000,50],["visitors","Monthly Visitors",5000,250000,1000],["conversion","Conversion Rate",5,60,1],["spend","Average Spend",100,2500,25],["referrals","Referral Participation",5,90,1],["subscriptions","Subscription Adoption",10,100,1],["campaigns","Campaign Purchases",20,1500,10]] as const).map(([key,label,min,max,step])=><label key={key} className="mb-5 block last:mb-0"><span className="flex justify-between text-[8px] font-semibold"><i className="not-italic text-[#766F7B]">{label}</i><b className="text-[#5E3BEE]">{key==="spend"?"AED ":""}{inputs[key].toLocaleString()}{["conversion","referrals","subscriptions"].includes(key)?"%":""}</b></span><input className="roi-slider mt-3 w-full" type="range" min={min} max={max} step={step} value={inputs[key]} onChange={event=>setInputs(current=>({...current,[key]:Number(event.target.value)}))}/></label>)}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["MRR",model.mrr],["ARR",model.arr],["Platform Revenue",model.platform],["Merchant Revenue",model.merchant],["Gross Profit",model.gross],["Operating Margin",`${model.margin.toFixed(1)}%`],["Referral Income",model.referralIncome],["Enterprise Revenue",model.enterprise]].map(([label,value],index)=><motion.article layout key={label} className={`rounded-[20px] p-5 ${index===1?"bg-gradient-to-br from-[#5E3BEE] to-[#2C195F] text-white":"border border-[#E4DFE8] bg-white"}`}><span className={`text-[7px] ${index===1?"text-white/45":"text-[#99929E]"}`}>{label}</span><AnimatePresence mode="popLayout"><motion.p key={String(value)} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} className="mt-3 text-lg font-bold tracking-[-.035em]">{typeof value==="number"?money(value):value}</motion.p></AnimatePresence><div className={`mt-4 h-1 overflow-hidden rounded-full ${index===1?"bg-white/10":"bg-[#EEEAF1]"}`}><motion.i animate={{width:`${45+(index*7)%50}%`}} className={`block h-full rounded-full ${index===1?"bg-[#DDBB63]":"bg-[#6B49DB]"}`}/></div></motion.article>)}</div></div></section>

      <section className="mt-20"><SectionHeader number="07" eyebrow="Unit Economics" title="A scalable merchant acquisition model."/><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{unitEconomics.map(([label,value],index)=><motion.article whileHover={{y:-4}} key={label} className="finance-card p-5"><span className="text-[7px] font-bold text-[#7B62D5]">0{index+1}</span><p className="mt-5 text-[7px] text-[#958E9A]">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></motion.article>)}</div></section>

      <section className="mt-20"><SectionHeader number="08" eyebrow="Investor Dashboard" title="Board-level commercial intelligence."/><div className="mt-7 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="finance-card p-6"><div className="flex items-end justify-between"><div><p className="engine-eyebrow">Revenue mix</p><h3 className="mt-2 text-xl font-semibold">Recurring revenue expansion</h3></div><b className="text-[9px] text-[#29916E]">↗ 22.1%</b></div><div className="mt-8 flex h-52 items-end gap-2">{[32,38,45,42,53,61,58,70,74,81,88,96].map((height,index)=><motion.i initial={{height:0}} whileInView={{height:`${height}%`}} transition={{delay:index*.04}} key={index} className="flex-1 rounded-t bg-gradient-to-t from-[#5E3BEE] to-[#B7A3F5]"/>)}</div><div className="mt-3 flex justify-between text-[7px] text-[#9A939F]"><span>Jan</span><span>Q2</span><span>Q3</span><span>Dec</span></div></article><article className="finance-card p-6"><p className="engine-eyebrow">Top industries</p><div className="mt-6 space-y-5">{[["Hotels",82],["Restaurants",71],["Luxury Mobility",64],["Retail",48],["Healthcare",36]].map(([name,share],index)=><div key={name as string}><div className="flex justify-between text-[8px]"><b>{name}</b><span className="text-[#8F8895]">{share}%</span></div><div className="mt-2 h-2 rounded-full bg-[#EEEAF1]"><motion.i initial={{width:0}} whileInView={{width:`${share}%`}} transition={{delay:index*.08}} className="block h-full rounded-full bg-gradient-to-r from-[#5E3BEE] to-[#C69B42]"/></div></div>)}</div></article></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Fastest Growing City","Dubai · +38%"],["Merchant Growth","+184 / month"],["Monthly Transactions","126,480"],["Referral Network Size","48,392"],["Campaign Revenue","AED 3.7M"],["Commercial Activity","94.2 score"],["Merchant Health","88 / 100"],["Expansion Value","AED 46M"],["Active Industries","11 sectors"],["Revenue Quality","84% recurring"]].map(([label,value])=><div key={label} className="finance-card p-4"><p className="text-[7px] text-[#99929E]">{label}</p><p className="mt-2 text-[12px] font-bold">{value}</p></div>)}</div></section>

      <section className="mt-20"><SectionHeader number="09" eyebrow="Why Botchain Creates Commercial Advantage" title="Infrastructure that improves commercial outcomes."/><div className="mt-7 overflow-hidden rounded-[26px] border border-[#E3DEE7] bg-white"><div className="grid grid-cols-[1fr_1fr_1fr] bg-[#171120] px-5 py-4 text-[8px] font-bold text-white"><span>Capability</span><span className="text-white/45">Traditional Platform</span><span className="text-[#DCC069]">NEFE + Botchain</span></div>{comparison.map(([capability,traditional,nefe],index)=><div key={capability} className={`grid grid-cols-[1fr_1fr_1fr] gap-4 px-5 py-4 text-[8px] ${index%2?"bg-[#FAF9FB]":"bg-white"}`}><b>{capability}</b><span className="text-[#908995]">{traditional}</span><span className="font-semibold text-[#5E3BEE]">✓ {nefe}</span></div>)}</div></section>

      <section className="mt-20"><SectionHeader number="10" eyebrow="Business Scenario Simulator" title="Four paths to commercial scale."/><div className="mt-6 flex flex-wrap gap-2">{(Object.keys(scenarioData) as Scenario[]).map(item=><button onClick={()=>setScenario(item)} key={item} className={`rounded-xl px-5 py-3 text-[8px] font-bold ${scenario===item?"bg-[#5E3BEE] text-white":"border border-[#E0DAE5] bg-white text-[#6B6471]"}`}>{item}</button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{[["Annual Revenue",`AED ${scenarioData[scenario].revenue}M`],["Profit",`AED ${scenarioData[scenario].profit}M`],["Merchant Growth",scenarioData[scenario].growth.toLocaleString()],["Cities",scenarioData[scenario].cities],["Countries",scenarioData[scenario].countries],["Commercial Volume",`AED ${scenarioData[scenario].volume}M`],["Valuation Estimate",`AED ${scenarioData[scenario].valuation}M`]].map(([label,value])=><motion.article layout key={label} className="finance-card p-5"><p className="text-[7px] text-[#99929E]">{label}</p><AnimatePresence mode="popLayout"><motion.p key={`${scenario}-${value}`} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-3 text-lg font-bold">{value}</motion.p></AnimatePresence></motion.article>)}</div></section>

      <section className="mt-20"><SectionHeader number="11" eyebrow="Expansion Roadmap" title="Scale city by city. Network by network."/><div className="mt-7 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="world-map relative min-h-[500px] overflow-hidden rounded-[28px] border border-[#322642] bg-[#120D1A]"><div className="commerce-grid absolute inset-0"/><div className="world-land"/>{markets.map(item=><button key={item.country} onClick={()=>setMarket(item)} className={`absolute z-10 -translate-x-1/2 -translate-y-1/2 ${market.country===item.country?"world-pin active":"world-pin"}`} style={{left:`${item.x}%`,top:`${item.y}%`}}><i/><span>{item.country}</span></button>)}</div><aside className="finance-card p-6"><div className="flex items-start justify-between"><div><p className="engine-eyebrow">{market.year} market</p><h3 className="mt-2 text-2xl font-semibold">{market.country}</h3></div><span className="rounded-full bg-[#EAF8F2] px-3 py-2 text-[7px] font-bold text-[#278D69]">{market.score}/100 score</span></div><div className="mt-6 grid grid-cols-2 gap-3">{[["Estimated merchants",market.merchants],["Market opportunity",market.opportunity],["Projected annual revenue",market.revenue],["Launch readiness",market.readiness],["Required investment",market.investment],["Commercial score",`${market.score}/100`]].map(([label,value])=><div key={label} className="rounded-[15px] bg-[#F8F6FA] p-4"><p className="text-[6px] text-[#99929E]">{label}</p><p className="mt-2 text-[11px] font-bold">{value}</p></div>)}</div><div className="mt-6"><p className="text-[7px] font-bold uppercase text-[#918A96]">Expansion timeline</p><div className="mt-4 flex flex-wrap gap-2">{["2026","2027","2028","2029","2030"].map(year=><button key={year} onClick={()=>setMarket(markets.find(item=>item.year===year)??markets[0])} className={`rounded-lg px-3 py-2 text-[7px] font-bold ${market.year===year?"bg-[#5E3BEE] text-white":"bg-[#F0ECFF] text-[#6B4FD1]"}`}>{year}</button>)}</div></div></aside></div></section>

      <section className="investment-summary relative mt-20 overflow-hidden rounded-[34px] bg-[#0E0914] p-7 text-white sm:p-10 lg:p-14"><div className="founder-dark-grid absolute inset-0"/><div className="relative"><SectionHeader number="12" eyebrow="Investment Summary" title="A commercial platform ready for controlled validation." dark/><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Current Prototype Status","Investor-ready interactive platform"],["Market Opportunity","AED 64B addressable commerce"],["Revenue Potential","AED 18.8M expected ARR"],["Commercial Model","Recurring + performance revenue"],["Scalability","City-led international rollout"],["Technology Readiness","Prototype validated for pilot design"],["Next Milestones","Merchant pilot · revenue validation"],["Suggested Pilot","RAK CEO Network cluster"]].map(([label,value])=><div key={label} className="rounded-[17px] border border-white/10 bg-white/[.055] p-5 backdrop-blur"><p className="text-[6px] uppercase text-white/35">{label}</p><p className="mt-2 text-[9px] font-semibold leading-5">{value}</p></div>)}</div><div className="mt-7 flex flex-col gap-5 rounded-[24px] border border-[#D1A849]/25 bg-gradient-to-r from-[#D1A849]/10 to-[#6743D8]/15 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[7px] font-bold uppercase text-[#DDBD68]">Investment Readiness Score</p><p className="mt-2 text-4xl font-bold">88<span className="text-lg text-white/30">/100</span></p></div><div className="flex flex-wrap gap-2">{["Download Investor Deck","Export Financial Model","Compare Growth Scenarios"].map(action=><button key={action} onClick={()=>notify(`${action} prepared`)} className="rounded-xl border border-white/10 bg-white/[.07] px-4 py-3 text-[8px] font-semibold transition hover:bg-white/12">{action}</button>)}<Link href="/ceo-demo" className="rounded-xl bg-white px-4 py-3 text-[8px] font-bold text-[#4F31BE]">View Executive Presentation</Link></div></div></div></section>
    </div>
    {toast&&<div className="prototype-toast fixed bottom-6 left-1/2 z-[150] -translate-x-1/2 rounded-xl bg-[#211A32]/95 px-5 py-3 text-[8px] font-semibold text-white shadow-2xl">✓ {toast}</div>}
  </main>;
}

function SectionHeader({number,eyebrow,title,dark=false}:{number:string;eyebrow:string;title:string;dark?:boolean}){
  return <div><p className={`text-[8px] font-bold uppercase tracking-[.15em] ${dark?"text-[#B79EEC]":"text-[#6E51D2]"}`}>{number} · {eyebrow}</p><h2 className={`mt-2 text-3xl font-semibold tracking-[-.045em] ${dark?"text-white":""}`}>{title}</h2></div>;
}
