"use client";
import Link from "next/link";
import {useMemo,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import type {OpportunitySummary} from "@/app/lib/data/opportunity-repository";
import {moveOpportunityStage} from "@/app/lib/actions/opportunity-actions";
import {OPPORTUNITY_STAGES,opportunityStageLabel,type OpportunityStageValue} from "@/app/lib/opportunity/opportunity-policy";
import {formatAed} from "../../_lib/format";
import {FavoriteButton} from "../_components/entity-actions";
import EntityCreateDialog from "../_components/entity-create-dialog";
import {AppCard,EmptyState,FilterBar,PageHeader,StatusBadge} from "../_components/ui";

const dateLabel=(value:Date|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value)):"No recorded activity";
const healthTone=(value:OpportunitySummary["commercialHealth"])=>value==="Strong"?"active":value==="Developing"?"medium":"high";
type Sort="updated"|"value-high"|"value-low"|"title";

export default function OpportunitiesWorkspace({opportunities:initial,businesses,members,canCreate,defaultBusinessId}:{opportunities:OpportunitySummary[];businesses:Array<{id:string;name:string}>;members:Array<{id:string;name:string}>;canCreate:boolean;defaultBusinessId?:string}){
  const [opportunities,setOpportunities]=useState(initial),[priority,setPriority]=useState("All"),[stageFilter,setStageFilter]=useState("All"),[query,setQuery]=useState(""),[sort,setSort]=useState<Sort>("updated");
  const items=useMemo(()=>opportunities.filter(item=>(priority==="All"||item.priority===priority)&&(stageFilter==="All"||item.stage===stageFilter)&&`${item.title} ${item.summary} ${item.stage} ${item.owner??""} ${item.participants.map(participant=>participant.name).join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="value-high"?b.modeledValue-a.modeledValue:sort==="value-low"?a.modeledValue-b.modeledValue:sort==="title"?a.title.localeCompare(b.title):new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()),[opportunities,priority,stageFilter,query,sort]);
  return <><PageHeader eyebrow="Commercial intelligence" title="Opportunity pipeline" description="Prioritize commercial value, coordinate participants, and move qualified opportunities toward governed execution." action={<EntityCreateDialog kind="opportunity" allowed={canCreate} defaultBusinessId={defaultBusinessId} businesses={businesses} members={members}/>}/><FilterBar><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search opportunities" aria-label="Search opportunities"/><select value={priority} onChange={event=>setPriority(event.target.value)} aria-label="Filter opportunity priority"><option>All</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><select value={stageFilter} onChange={event=>setStageFilter(event.target.value)} aria-label="Filter opportunity stage"><option>All</option>{OPPORTUNITY_STAGES.map(stage=><option value={stage} key={stage}>{opportunityStageLabel(stage)}</option>)}</select><select value={sort} onChange={event=>setSort(event.target.value as Sort)} aria-label="Sort opportunities"><option value="updated">Recently updated</option><option value="value-high">Highest value</option><option value="value-low">Lowest value</option><option value="title">Title</option></select></FilterBar><PipelineSummary opportunities={items}/>{!items.length?<AppCard><EmptyState title="No opportunities match this view" description={opportunities.length?"Adjust the search, stage, priority, or sort controls.":"Create the first opportunity to begin qualifying commercial value."}/></AppCard>:<div className="ws-kanban ws-opportunity-pipeline" aria-label="Opportunity pipeline">{OPPORTUNITY_STAGES.map(stage=>{const stageItems=items.filter(item=>item.stage===stage);return <section className="ws-kanban-column" key={stage}><header><div><h2>{opportunityStageLabel(stage)}</h2><small>{formatAed(stageItems.reduce((sum,item)=>sum+item.modeledValue,0))}</small></div><span>{stageItems.length}</span></header><div>{stageItems.length?stageItems.map(item=><OpportunityCard item={item} canUpdate={canCreate} onChanged={changed=>setOpportunities(current=>current.map(record=>record.id===changed.id?changed:record))} key={item.id}/>):<p className="ws-pipeline-empty">No opportunities at this stage.</p>}</div></section>})}</div>}</>;
}

function PipelineSummary({opportunities}:{opportunities:OpportunitySummary[]}){return <section className="ws-pipeline-summary ws-opportunity-stage-summary" aria-label="Pipeline stage summary">{OPPORTUNITY_STAGES.map(stage=>{const items=opportunities.filter(item=>item.stage===stage);return <div key={stage}><span>{items.length}</span><p>{opportunityStageLabel(stage)}</p><small>{formatAed(items.reduce((sum,item)=>sum+item.modeledValue,0))}</small></div>})}</section>}

function OpportunityCard({item,canUpdate,onChanged}:{item:OpportunitySummary;canUpdate:boolean;onChanged:(item:OpportunitySummary)=>void}){const [pending,start]=useTransition(),[feedback,setFeedback]=useState(""),router=useRouter();const participantLabel=item.participants.length?`${item.participants[0].name}${item.participants.length>1?` +${item.participants.length-1}`:""}`:"No participants";return <article className="ws-kanban-card ws-entity-card ws-opportunity-maturity-card"><Link className="ws-card-link" href={`/workspace/opportunities/${item.id}`} aria-label={`Open ${item.title} workspace`}/><div className="ws-kanban-card-head"><div className="ws-status-stack"><StatusBadge tone={item.priority}>{item.priority}</StatusBadge><StatusBadge tone={healthTone(item.commercialHealth)}>{item.commercialHealth}</StatusBadge></div><FavoriteButton type="opportunity" id={item.id}/></div><h3>{item.title}</h3><p>{item.summary}</p><div className="ws-opportunity-primary"><strong>{formatAed(item.modeledValue)}</strong><small>{item.owner??"Unassigned"}</small></div><div className="ws-opportunity-context">{item.participants[0]?<Link href={`/workspace/businesses/${item.participants[0].id}`}>{participantLabel}</Link>:<span>{participantLabel}</span>}<span>{item.participants.length} participant{item.participants.length===1?"":"s"}</span></div><div className="ws-opportunity-recommendation"><small>Recommendation</small><strong>{item.recommendationSummary??"No recommendation recorded"}</strong>{item.recommendationConfidence!==null&&<span>{item.recommendationConfidence}% recorded confidence</span>}</div><small className="ws-business-activity">Last activity · {dateLabel(item.lastActivity)}</small><strong className="ws-open-workspace">Open Workspace →</strong><label className="ws-card-control"><span>Pipeline stage</span><select value={item.stage} disabled={!canUpdate||pending} aria-label={`Move ${item.title} to another stage`} onChange={event=>{const next=event.target.value as OpportunityStageValue;if(next===item.stage)return;const previous=item;onChanged({...item,stage:next});setFeedback("Saving stage…");start(async()=>{const result=await moveOpportunityStage({id:item.id,stage:next,expectedUpdatedAt:new Date(item.updatedAt).toISOString()});if(result.ok){onChanged({...item,stage:next,updatedAt:new Date(result.updatedAt)});setFeedback("Stage saved");router.refresh()}else{onChanged(previous);setFeedback(result.error)}})}}>{OPPORTUNITY_STAGES.map(stage=><option value={stage} key={stage}>{opportunityStageLabel(stage)}</option>)}</select></label>{!canUpdate&&<small className="ws-permission-note">Your role can view but cannot move opportunities.</small>}{feedback&&<small className={feedback==="Stage saved"?"ws-save-feedback success":"ws-save-feedback"} role="status">{feedback}</small>}</article>}
