"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import type {OpportunityStage} from "../../_lib/models";
import {formatAed} from "../../_lib/format";
import {FavoriteButton} from "../_components/entity-actions";
import EntityCreateDialog from "../_components/entity-create-dialog";
import {useCollaboration} from "../_components/collaboration-state";
import {EmptyState,FilterBar,PageHeader,StatusBadge} from "../_components/ui";
const stages:OpportunityStage[]=["Identified","Qualified","Negotiating","Approved","Pilot","Active","Completed"];
export default function OpportunitiesWorkspace({canCreate}:{canCreate:boolean}){const {opportunityStages,moveOpportunity,data}=useCollaboration(),{opportunities,businesses,users}=data,[priority,setPriority]=useState("All"),[query,setQuery]=useState("");const items=useMemo(()=>opportunities.filter(item=>(priority==="All"||item.priority===priority.toLowerCase())&&`${item.title} ${item.summary} ${item.stage}`.toLowerCase().includes(query.toLowerCase())),[opportunities,priority,query]);return <><PageHeader eyebrow="Commercial intelligence" title="Opportunity pipeline" description="Open an opportunity workspace for intelligence, connected businesses, discussion, and executive decisions." action={<EntityCreateDialog kind="opportunity" allowed={canCreate} businesses={businesses.map(item=>({id:item.id,name:item.name}))} members={users.map(item=>({id:item.id,name:item.name}))}/>}/><FilterBar><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search opportunities" aria-label="Search opportunities"/><select value={priority} onChange={event=>setPriority(event.target.value)} aria-label="Filter opportunity priority"><option>All</option><option>High</option><option>Medium</option><option>Low</option></select></FilterBar>{!items.length?<EmptyState title="No opportunities found" description="Create an opportunity to evaluate a connected commercial outcome."/>:<div className="ws-kanban" aria-label="Opportunity pipeline">{stages.map(stage=>{const stageItems=items.filter(item=>opportunityStages[item.id]===stage);return <section className="ws-kanban-column" key={stage}><header><h2>{stage}</h2><span>{stageItems.length}</span></header><div>{stageItems.map(item=><article className="ws-kanban-card ws-entity-card" key={item.id}><Link className="ws-card-link" href={`/workspace/opportunities/${item.id}`} aria-label={`Open ${item.title} workspace`}/><div className="ws-kanban-card-head"><StatusBadge tone={item.priority}>{item.priority}</StatusBadge><FavoriteButton type="opportunity" id={item.id}/></div><h3>{item.title}</h3><p>{item.summary}</p><strong>{formatAed(item.estimatedValue)}</strong><span className="ws-open-workspace">Open Workspace →</span><label className="ws-card-control"><span>Move to</span><select value={opportunityStages[item.id]} onChange={event=>moveOpportunity(item.id,event.target.value as OpportunityStage)}>{stages.map(option=><option key={option}>{option}</option>)}</select></label></article>)}</div></section>})}</div>}</>}
