import Link from "next/link";
import {getWorkspaceData} from "@/app/lib/data/workspace-repository";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {can} from "@/app/lib/auth/permissions";
import {formatAed} from "../../_lib/format";
import EntityCreateDialog from "../_components/entity-create-dialog";
import {AppCard,EmptyState,PageHeader,ProgressBar,StatusBadge} from "../_components/ui";

export default async function CampaignsPage({searchParams}:{searchParams:Promise<{business?:string}>}){const [context,{campaigns,businesses},query]=await Promise.all([requireWorkspaceContext(),getWorkspaceData(),searchParams]),defaultBusinessId=businesses.some(item=>item.id===query.business)?query.business:undefined;return <><PageHeader eyebrow="Coordinated growth" title="Campaigns" description="Open a campaign workspace to review participants, performance, collaboration, and decisions." action={<EntityCreateDialog kind="campaign" defaultBusinessId={defaultBusinessId} allowed={can(context.membership.role,"business.manage")} businesses={businesses.map(item=>({id:item.id,name:item.name}))}/>}/>{campaigns.length?<div className="ws-card-grid">{campaigns.map(item=><AppCard className="ws-entity-card ws-campaign-summary" key={item.id}><Link className="ws-card-link" href={`/workspace/campaigns/${item.id}`} aria-label={`Open ${item.title} workspace`}/><div className="ws-card-meta"><StatusBadge tone={item.status}>{item.status}</StatusBadge><small>{item.startDate||"Schedule pending"}</small></div><h3>{item.title}</h3><p>{item.objective}</p><div className="ws-detail-grid"><span className="ws-stat-badge"><small>Budget</small><strong>{formatAed(item.budget)}</strong></span><span className="ws-stat-badge"><small>Participants</small><strong>{item.businessIds.length}</strong></span></div><ProgressBar value={item.progress} label={`${item.title} progress`} tone={item.status==="active"?"green":item.status==="pending"?"blue":"purple"}/><strong className="ws-open-workspace">Open Workspace →</strong></AppCard>)}</div>:<AppCard><EmptyState title="No campaigns yet" description="Create a campaign to coordinate businesses around a measurable commercial objective."/></AppCard>}</>}
