"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useMemo, useState } from "react";
import FinancialSubnav from "../components/financial-subnav";

type Scenario="Conservative"|"Expected"|"Aggressive"|"Enterprise";
type Inputs={merchants:number;adoption:number;referrals:number;campaigns:number;arpm:number;margin:number};
const scenarios:Record<Scenario,{merchants:number;revenue:number;profit:number;cities:number;countries:number;valuation:number}>={
  Conservative:{merchants:420,revenue:8.4,profit:1.7,cities:2,countries:1,valuation:42},
  Expected:{merchants:1247,revenue:18.8,profit:6.2,cities:5,countries:2,valuation:96},
  Aggressive:{merchants:3200,revenue:41.6,profit:17.9,cities:11,countries:5,valuation:225},
  Enterprise:{merchants:7800,revenue:82.4,profit:39.8,cities:24,countries:9,valuation:510},
};
const expansion=[["2026","UAE","1,247","AED 18.8M","AED 6.2M"],["2027","Saudi Arabia + Qatar","3,800","AED 46M","AED 12M"],["2028","Egypt + Kuwait","7,200","AED 82M","AED 18M"],["2029","Singapore + Malaysia","13,400","AED 156M","AED 27M"],["2030","Europe + North America","42,000","AED 500M","AED 68M"]];
const unit=[["Merchant CAC","AED 2,850"],["Merchant LTV","AED 42,600"],["LTV : CAC","14.9×"],["Payback Period","3.4 months"],["Monthly Churn","2.1%"],["Retention Rate","92.4%"],["Gross Margin","82%"],["Referral Margin","86%"]];
const money=(value:number)=>value>=1e6?`AED ${(value/1e6).toFixed(1)}M`:`AED ${Math.round(value/1000)}K`;

export default function FinancialModel(){
  const [scenario,setScenario]=useState<Scenario>("Expected");
  const [inputs,setInputs]=useState<Inputs>({merchants:1247,adoption:61,referrals:48392,campaigns:618,arpm:1174,margin:82});
  const [toast,setToast]=useState("");
  const projection=useMemo(()=>{
    const mrr=inputs.merchants*inputs.arpm*(inputs.adoption/100)+inputs.referrals*7.2+inputs.campaigns*720;
    return {mrr,arr:mrr*12,gross:mrr*(inputs.margin/100),cac:2850,ltv:42600,payback:3.4};
  },[inputs]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  return <main className="min-h-screen bg-[#F7F5F9] text-[#1B1725]"><FinancialSubnav/><section className="financial-hero relative overflow-hidden px-5 py-18"><div className="engine-grid absolute inset-0"/><div className="relative mx-auto max-w-[1280px]"><span className="inline-flex rounded-full border border-[#DDD3F8] bg-white/70 px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#5E3BEE]">Board-level review</span><div className="mt-6 flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-5xl font-semibold tracking-[-.06em] sm:text-7xl">Financial Model</h1><p className="mt-5 max-w-2xl text-[12px] leading-6 text-[#746D7A]">Live assumptions, unit economics and expansion scenarios for executive and investor review.</p></div><button onClick={()=>notify("Financial model export prepared")} className="rounded-xl bg-[#21172F] px-5 py-3 text-[8px] font-bold text-white">Export Financial Model ↗</button></div></div></section><div className="page-shell py-14">
    <section><p className="engine-eyebrow">Core financial indicators</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["MRR",money(projection.mrr),"+18.4%"],["ARR",money(projection.arr),"+22.1%"],["Gross Margin",`${inputs.margin}%`,"+3.4 pts"],["Gross Profit",money(projection.gross),"+19.7%"]].map(([label,value,trend],index)=><motion.article whileHover={{y:-4}} key={label} className={`rounded-[22px] p-6 ${index===1?"bg-gradient-to-br from-[#5E3BEE] to-[#2D1A60] text-white":"finance-card"}`}><div className="flex justify-between"><span className={`text-[7px] ${index===1?"text-white/45":"text-[#938C98]"}`}>{label}</span><b className="text-[7px] text-[#42AE85]">{trend}</b></div><AnimatePresence mode="popLayout"><motion.p key={value} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-4 text-3xl font-bold tracking-[-.04em]">{value}</motion.p></AnimatePresence><div className={`mt-6 flex h-10 items-end gap-1 ${index===1?"opacity-70":""}`}>{[32,45,41,58,67,63,81].map((h,i)=><i key={i} className={`chart-bar flex-1 rounded-t ${index===1?"bg-white/30":"bg-[#6A48DA]/35"}`} style={{height:`${h}%`}}/>)}</div></motion.article>)}</div></section>
    <section className="mt-20 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><div><p className="engine-eyebrow">Assumption controls</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Test the operating model.</h2><div className="finance-card mt-6 p-6">{([["merchants","Active merchants",100,10000,50],["adoption","Subscription adoption",10,100,1],["referrals","Monthly referrals",5000,200000,1000],["campaigns","Active campaigns",50,2500,10],["arpm","Average revenue / merchant",299,2500,25],["margin","Gross margin",50,92,1]] as const).map(([key,label,min,max,step])=><label key={key} className="mb-6 block last:mb-0"><span className="flex justify-between text-[8px] font-semibold"><i className="not-italic text-[#766F7B]">{label}</i><b className="text-[#5E3BEE]">{key==="arpm"?"AED ":""}{inputs[key].toLocaleString()}{key==="adoption"||key==="margin"?"%":""}</b></span><input className="roi-slider mt-3 w-full" type="range" min={min} max={max} step={step} value={inputs[key]} onChange={event=>setInputs(current=>({...current,[key]:Number(event.target.value)}))}/></label>)}</div></div><div><p className="engine-eyebrow">Unit economics</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{unit.map(([label,value],index)=><motion.article layout whileHover={{y:-3}} key={label} className="finance-card p-5"><span className="text-[7px] font-bold text-[#7257D2]">0{index+1}</span><p className="mt-5 text-[7px] text-[#96909B]">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></motion.article>)}</div><div className="mt-4 rounded-[22px] bg-[#171120] p-6 text-white"><div className="flex items-end justify-between"><div><p className="text-[7px] uppercase text-white/35">LTV to CAC efficiency</p><p className="mt-2 text-3xl font-bold text-[#E0BF68]">14.9×</p></div><span className="rounded-full bg-[#51B78D]/15 px-3 py-2 text-[7px] font-bold text-[#70D3A9]">Healthy SaaS model</span></div><div className="mt-5 h-2 rounded-full bg-white/10"><motion.i initial={{width:0}} whileInView={{width:"88%"}} className="block h-full rounded-full bg-gradient-to-r from-[#6542D9] to-[#D5AC52]"/></div></div></div></section>
    <section className="mt-20"><p className="engine-eyebrow">Scenario simulator</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Four paths to scale.</h2><div className="mt-6 flex flex-wrap gap-2">{(Object.keys(scenarios) as Scenario[]).map(item=><button key={item} onClick={()=>setScenario(item)} className={`rounded-xl px-5 py-3 text-[8px] font-bold ${scenario===item?"bg-[#5E3BEE] text-white":"border border-[#E1DBE5] bg-white"}`}>{item}</button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Merchants",scenarios[scenario].merchants.toLocaleString()],["Annual Revenue",`AED ${scenarios[scenario].revenue}M`],["Operating Profit",`AED ${scenarios[scenario].profit}M`],["Cities",scenarios[scenario].cities],["Countries",scenarios[scenario].countries],["Valuation Estimate",`AED ${scenarios[scenario].valuation}M`]].map(([label,value])=><motion.article layout key={label} className="finance-card p-5"><p className="text-[7px] text-[#98919D]">{label}</p><AnimatePresence mode="popLayout"><motion.p key={`${scenario}-${value}`} initial={{opacity:0,y:7}} animate={{opacity:1,y:0}} className="mt-3 text-lg font-bold">{value}</motion.p></AnimatePresence></motion.article>)}</div></section>
    <section className="mt-20"><p className="engine-eyebrow">Three-year projection</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Recurring revenue compounds with network density.</h2><div className="finance-card mt-6 p-7"><div className="grid gap-7 lg:grid-cols-[1fr_2fr]"><div className="space-y-4">{[["2026","AED 18.8M","1,247 merchants"],["2027","AED 46.0M","3,800 merchants"],["2028","AED 82.0M","7,200 merchants"]].map(([year,revenue,merchants])=><div key={year} className="rounded-[16px] bg-[#F8F6FA] p-4"><div className="flex justify-between"><b>{year}</b><b className="text-[#5E3BEE]">{revenue}</b></div><p className="mt-1 text-[7px] text-[#96909B]">{merchants}</p></div>)}</div><div className="flex h-64 items-end gap-5">{[28,68,100].map((height,index)=><div key={index} className="flex flex-1 flex-col items-center justify-end gap-3"><b className="text-[8px]">{["AED 18.8M","AED 46M","AED 82M"][index]}</b><motion.i initial={{height:0}} whileInView={{height:`${height}%`}} className="w-full max-w-28 rounded-t-xl bg-gradient-to-t from-[#5E3BEE] to-[#B9A7F4]"/><span className="text-[7px] text-[#99929E]">{2026+index}</span></div>)}</div></div></div></section>
    <section className="mt-20"><p className="engine-eyebrow">Expansion assumptions</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Capital follows commercial validation.</h2><div className="mt-6 overflow-hidden rounded-[24px] border border-[#E3DEE7] bg-white"><div className="grid grid-cols-5 bg-[#171120] px-5 py-4 text-[7px] font-bold text-white"><span>Year</span><span>Markets</span><span>Merchants</span><span>Annual revenue</span><span>Required investment</span></div>{expansion.map((row,index)=><div key={row[0]} className={`grid grid-cols-5 px-5 py-4 text-[8px] ${index%2?"bg-[#FAF9FB]":"bg-white"}`}>{row.map((value,i)=><span key={i} className={i===0||i===3?"font-bold text-[#5E3BEE]":""}>{value}</span>)}</div>)}</div></section>
  </div>{toast&&<div className="prototype-toast fixed bottom-6 left-1/2 z-[100] -translate-x-1/2 rounded-xl bg-[#211A32] px-5 py-3 text-[8px] font-semibold text-white">✓ {toast}</div>}</main>
}
