"use server";
import {revalidatePath} from "next/cache";
import {and,eq,ne,sql} from "drizzle-orm";
import {z} from "zod";
import {database} from "@/db/client";
import {auditLogs,businessContacts,businessRelationships,businessServices,businessTags,businesses,collaborationActivityEvents,industries,regions} from "@/db/schema";
import {activityEvent} from "@/app/lib/collaboration/domain-events";
import {requirePermission} from "@/app/lib/auth/permissions";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {logServerFailure} from "@/app/lib/observability/server-log";

type Result={ok:true}|{ok:false;error:string};const uuid=z.string().uuid();
async function safe(action:()=>Promise<void>):Promise<Result>{try{await action();return {ok:true}}catch(error){if(error instanceof z.ZodError)return {ok:false,error:error.issues[0]?.message??"Review the submitted fields."};if(error instanceof Error&&error.name==="AuthorizationError")return {ok:false,error:error.message};if(error instanceof Error&&error.message==="STALE_BUSINESS")return {ok:false,error:"This business changed after you opened it. Refresh and try again."};if(error instanceof Error&&error.message==="DUPLICATE_BUSINESS")return {ok:false,error:"A business with this name already exists."};logServerFailure({event:"business.mutation_failed",category:error instanceof Error?error.message.slice(0,80):"unknown"});return {ok:false,error:"The business record could not be updated."}}}
type Tx=Parameters<Parameters<ReturnType<typeof database>["transaction"]>[0]>[0];
async function ownedBusiness(tx:Tx,organizationId:string,businessId:string){const [record]=await tx.select({id:businesses.id}).from(businesses).where(and(eq(businesses.id,businessId),eq(businesses.organizationId,organizationId),sql`${businesses.deletedAt} is null`)).limit(1);if(!record)throw new Error("Resource not found");return record}
async function evidence(tx:Tx,input:{organizationId:string;actorId:string;businessId:string;action:string;component:string;recordId?:string}){const metadata={component:input.component,recordId:input.recordId},event=activityEvent("business.updated","business",input.businessId,metadata);await tx.insert(auditLogs).values({organizationId:input.organizationId,actorId:input.actorId,action:input.action,entityType:"business",entityId:input.businessId,metadata});await tx.insert(collaborationActivityEvents).values({organizationId:input.organizationId,actorId:input.actorId,...event})}
const profileSchema=z.object({id:uuid,name:z.string().trim().min(2).max(160),category:z.string().trim().min(2).max(120),industryId:uuid.nullable(),regionId:uuid.nullable(),location:z.string().trim().min(2).max(400),description:z.string().trim().min(20).max(600),status:z.enum(["ACTIVE","PENDING","PAUSED","DRAFT","COMPLETED"]),expectedUpdatedAt:z.iso.datetime()});
export async function updateBusinessProfile(input:unknown){return safe(async()=>{const data=profileSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");const db=database();if(data.industryId&&!await db.select({id:industries.id}).from(industries).where(eq(industries.id,data.industryId)).limit(1).then(rows=>rows[0]))throw new Error("Resource not found");if(data.regionId&&!await db.select({id:regions.id}).from(regions).where(eq(regions.id,data.regionId)).limit(1).then(rows=>rows[0]))throw new Error("Resource not found");const duplicate=await db.select({id:businesses.id}).from(businesses).where(and(eq(businesses.organizationId,context.organization.id),ne(businesses.id,data.id),sql`lower(${businesses.name}) = lower(${data.name})`,sql`${businesses.deletedAt} is null`)).limit(1);if(duplicate[0])throw new Error("DUPLICATE_BUSINESS");await db.transaction(async tx=>{const [changed]=await tx.update(businesses).set({name:data.name,initials:data.name.split(/\s+/).map(part=>part[0]).join("").slice(0,3).toUpperCase(),category:data.category,industryId:data.industryId,regionId:data.regionId,location:data.location,description:data.description,status:data.status,updatedAt:new Date()}).where(and(eq(businesses.id,data.id),eq(businesses.organizationId,context.organization.id),eq(businesses.updatedAt,new Date(data.expectedUpdatedAt)),sql`${businesses.deletedAt} is null`)).returning({id:businesses.id});if(!changed)throw new Error("STALE_BUSINESS");await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.id,action:"business.profile_updated",component:"profile"})});revalidatePath(`/workspace/businesses/${data.id}`);revalidatePath("/workspace/businesses")})}

const contactSchema=z.object({businessId:uuid,id:uuid.optional(),name:z.string().trim().min(2).max(160),role:z.string().trim().min(2).max(120),email:z.string().trim().toLowerCase().email().max(254)});
export async function saveBusinessContact(input:unknown){return safe(async()=>{const data=contactSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");await database().transaction(async tx=>{await ownedBusiness(tx,context.organization.id,data.businessId);const record=data.id?(await tx.update(businessContacts).set({name:data.name,role:data.role,email:data.email,updatedAt:new Date()}).where(and(eq(businessContacts.id,data.id),eq(businessContacts.businessId,data.businessId),eq(businessContacts.organizationId,context.organization.id))).returning({id:businessContacts.id}))[0]:(await tx.insert(businessContacts).values({organizationId:context.organization.id,businessId:data.businessId,name:data.name,role:data.role,email:data.email}).returning({id:businessContacts.id}))[0];if(!record)throw new Error("Resource not found");await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.businessId,action:data.id?"business.contact_updated":"business.contact_created",component:"contact",recordId:record.id})});revalidatePath(`/workspace/businesses/${data.businessId}`)})}
export async function removeBusinessContact(input:unknown){return removeNetworkRecord(input,"contact")}

const serviceSchema=z.object({businessId:uuid,id:uuid.optional(),kind:z.enum(["SERVICE","PRODUCT"]),name:z.string().trim().min(2).max(160)});
export async function saveBusinessService(input:unknown){return safe(async()=>{const data=serviceSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");await database().transaction(async tx=>{await ownedBusiness(tx,context.organization.id,data.businessId);const record=data.id?(await tx.update(businessServices).set({kind:data.kind,name:data.name}).where(and(eq(businessServices.id,data.id),eq(businessServices.businessId,data.businessId))).returning({id:businessServices.id}))[0]:(await tx.insert(businessServices).values({businessId:data.businessId,kind:data.kind,name:data.name}).returning({id:businessServices.id}))[0];if(!record)throw new Error("Resource not found");await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.businessId,action:data.id?"business.service_updated":"business.service_created",component:data.kind.toLowerCase(),recordId:record.id})});revalidatePath(`/workspace/businesses/${data.businessId}`)})}
export async function removeBusinessService(input:unknown){return removeNetworkRecord(input,"service")}

const tagSchema=z.object({businessId:uuid,tag:z.string().trim().min(2).max(80)});
export async function addBusinessTag(input:unknown){return safe(async()=>{const data=tagSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");await database().transaction(async tx=>{await ownedBusiness(tx,context.organization.id,data.businessId);await tx.insert(businessTags).values(data).onConflictDoNothing();await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.businessId,action:"business.tag_created",component:"tag"})});revalidatePath(`/workspace/businesses/${data.businessId}`)})}
export async function removeBusinessTag(input:unknown){return safe(async()=>{const data=tagSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");await database().transaction(async tx=>{await ownedBusiness(tx,context.organization.id,data.businessId);const removed=await tx.delete(businessTags).where(and(eq(businessTags.businessId,data.businessId),eq(businessTags.tag,data.tag))).returning({businessId:businessTags.businessId});if(!removed[0])throw new Error("Resource not found");await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.businessId,action:"business.tag_removed",component:"tag"})});revalidatePath(`/workspace/businesses/${data.businessId}`)})}

const relationshipSchema=z.object({businessId:uuid,id:uuid.optional(),relatedBusinessId:uuid,relationship:z.string().trim().min(2).max(160),status:z.enum(["ACTIVE","PENDING","PAUSED","DRAFT","COMPLETED"]),since:z.union([z.iso.date(),z.literal("")])});
export async function saveBusinessRelationship(input:unknown){return safe(async()=>{const data=relationshipSchema.parse(input);if(data.businessId===data.relatedBusinessId)throw new z.ZodError([{code:"custom",path:["relatedBusinessId"],message:"Choose another business.",input:data.relatedBusinessId}]);const context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");await database().transaction(async tx=>{await ownedBusiness(tx,context.organization.id,data.businessId);await ownedBusiness(tx,context.organization.id,data.relatedBusinessId);const record=data.id?(await tx.update(businessRelationships).set({toBusinessId:data.relatedBusinessId,relationship:data.relationship,status:data.status,since:data.since||null,updatedAt:new Date()}).where(and(eq(businessRelationships.id,data.id),eq(businessRelationships.organizationId,context.organization.id),eq(businessRelationships.fromBusinessId,data.businessId))).returning({id:businessRelationships.id}))[0]:(await tx.insert(businessRelationships).values({organizationId:context.organization.id,fromBusinessId:data.businessId,toBusinessId:data.relatedBusinessId,relationship:data.relationship,status:data.status,since:data.since||null}).returning({id:businessRelationships.id}))[0];if(!record)throw new Error("Resource not found");await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.businessId,action:data.id?"business.relationship_updated":"business.relationship_created",component:"relationship",recordId:record.id})});revalidatePath(`/workspace/businesses/${data.businessId}`)})}
export async function removeBusinessRelationship(input:unknown){return removeNetworkRecord(input,"relationship")}

async function removeNetworkRecord(input:unknown,kind:"contact"|"service"|"relationship"){return safe(async()=>{const data=z.object({businessId:uuid,id:uuid,confirmed:z.literal(true)}).parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");await database().transaction(async tx=>{await ownedBusiness(tx,context.organization.id,data.businessId);const removed=kind==="contact"?await tx.delete(businessContacts).where(and(eq(businessContacts.id,data.id),eq(businessContacts.businessId,data.businessId),eq(businessContacts.organizationId,context.organization.id))).returning({id:businessContacts.id}):kind==="service"?await tx.delete(businessServices).where(and(eq(businessServices.id,data.id),eq(businessServices.businessId,data.businessId))).returning({id:businessServices.id}):await tx.delete(businessRelationships).where(and(eq(businessRelationships.id,data.id),eq(businessRelationships.organizationId,context.organization.id),eq(businessRelationships.fromBusinessId,data.businessId))).returning({id:businessRelationships.id});if(!removed[0])throw new Error("Resource not found");await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,businessId:data.businessId,action:`business.${kind}_removed`,component:kind,recordId:data.id})});revalidatePath(`/workspace/businesses/${data.businessId}`)})}
