"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {requirePermission} from "@/app/lib/auth/permissions";
import {collaborationEntityTypes} from "@/app/lib/collaboration/domain-events";
import {approvalModes,decisionPriorities,decisionStatuses,responseStates,DecisionPolicyError} from "@/app/lib/decisions/policy";
import {decisionRepository} from "@/app/lib/data/decision-repository";

export type DecisionActionResult={ok:true;decisionId?:string}|{ok:false;error:string;code?:string};
const id=z.string().uuid(),version=z.number().int().positive();
const entity=z.object({entityType:z.enum(collaborationEntityTypes),entityId:id});
const draft=entity.extend({title:z.string().trim().min(3).max(180),statement:z.string().trim().min(10).max(5000),rationale:z.string().trim().min(10).max(5000),requestedOutcome:z.string().trim().min(3).max(2000),priority:z.enum(decisionPriorities),approvalMode:z.enum(approvalModes),ownerId:id,dueAt:z.coerce.date().nullable()});
const safe=async(operation:()=>Promise<{id?:string}|void>):Promise<DecisionActionResult>=>{try{const result=await operation();return {ok:true,decisionId:result?.id}}catch(error){if(error instanceof z.ZodError)return {ok:false,error:"Review the submitted decision details.",code:"VALIDATION_ERROR"};if(error instanceof DecisionPolicyError)return {ok:false,error:error.message,code:error.code};if(error instanceof Error&&error.name==="AuthorizationError")return {ok:false,error:error.message,code:"FORBIDDEN"};return {ok:false,error:"The decision change could not be saved.",code:"UNEXPECTED_ERROR"}}};
const refresh=(decisionId?:string)=>{revalidatePath("/workspace/decisions");revalidatePath("/workspace");if(decisionId)revalidatePath(`/workspace/decisions/${decisionId}`)};
async function repo(permission:"decision.create"|"decision.submit"|"decision.review"|"decision.approve"|"decision.admin"){const context=await requireWorkspaceContext();requirePermission(context.membership.role,permission);return decisionRepository(context)}

export async function createDecisionDraft(input:unknown){return safe(async()=>{const data=draft.parse(input),created=await (await repo("decision.create")).createDraft(data);refresh(created.id);return {id:created.id}})}
export async function updateDecisionDraft(input:unknown){return safe(async()=>{const data=draft.omit({entityType:true,entityId:true}).extend({decisionId:id,expectedVersion:version}).parse(input),{decisionId,expectedVersion,...changes}=data;const updated=await (await repo("decision.create")).updateDraft(decisionId,expectedVersion,changes);refresh(updated.id);return {id:updated.id}})}
export async function addDecisionParticipant(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,userId:id,role:z.enum(["approver","reviewer"]),order:z.number().int().positive().nullable()}).parse(input);await (await repo("decision.submit")).addParticipant(data.decisionId,data.userId,data.role,data.order);refresh(data.decisionId);return {id:data.decisionId}})}
export async function removeDecisionParticipant(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,userId:id,role:z.enum(["approver","reviewer"])}).parse(input);await (await repo("decision.submit")).removeParticipant(data.decisionId,data.userId,data.role);refresh(data.decisionId);return {id:data.decisionId}})}
export async function reorderDecisionApprovers(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,userIds:z.array(id).min(1).max(50)}).parse(input);await (await repo("decision.submit")).reorderApprovers(data.decisionId,data.userIds);refresh(data.decisionId);return {id:data.decisionId}})}
export async function submitDecision(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,target:z.enum(["pending_review","pending_approval"]),expectedVersion:version}).parse(input);await (await repo("decision.submit")).submit(data.decisionId,data.target,data.expectedVersion);refresh(data.decisionId);return {id:data.decisionId}})}
export async function respondToDecision(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,state:z.enum(responseStates),comment:z.string().trim().max(2000).nullable(),idempotencyKey:z.string().uuid(),expectedVersion:version}).parse(input);await (await repo("decision.approve")).respond(data.decisionId,data.state,data.comment,data.idempotencyKey,data.expectedVersion);refresh(data.decisionId);return {id:data.decisionId}})}
export async function addDecisionReviewComment(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,comment:z.string().trim().min(1).max(2000)}).parse(input);await (await repo("decision.review")).addReviewComment(data.decisionId,data.comment);refresh(data.decisionId);return {id:data.decisionId}})}
export async function cancelDecision(input:unknown){return lifecycle(input,"cancelled")}
export async function reopenDecision(input:unknown){return lifecycle(input,"draft")}
export async function expireDecision(input:unknown){return lifecycle(input,"expired")}
async function lifecycle(input:unknown,target:"cancelled"|"draft"|"expired"){return safe(async()=>{const data=z.object({decisionId:id,expectedVersion:version}).parse(input);await (await repo("decision.admin")).lifecycle(data.decisionId,target,data.expectedVersion);refresh(data.decisionId);return {id:data.decisionId}})}
export async function finalizeDecision(input:unknown){return safe(async()=>{const data=z.object({decisionId:id,expectedVersion:version,summary:z.string().trim().min(3).max(5000)}).parse(input);await (await repo("decision.admin")).finalize(data.decisionId,data.expectedVersion,data.summary);refresh(data.decisionId);return {id:data.decisionId}})}
export async function listEntityDecisions(input:unknown){const data=entity.safeParse(input);if(!data.success)return {ok:false as const,error:"Review the decision request."};const context=await requireWorkspaceContext();requirePermission(context.membership.role,"decision.read");return {ok:true as const,decisions:await decisionRepository(context).byEntity(data.data)}}
export async function listWorkspaceDecisions(input:unknown){const filters=z.object({status:z.enum(decisionStatuses).optional(),priority:z.enum(decisionPriorities).optional(),entityType:z.enum(collaborationEntityTypes).optional(),ownerId:id.optional(),approverId:id.optional(),dueBefore:z.coerce.date().optional(),page:z.number().int().positive().optional()}).safeParse(input);if(!filters.success)return {ok:false as const,error:"Review the decision filters."};const context=await requireWorkspaceContext();requirePermission(context.membership.role,"decision.read");return {ok:true as const,decisions:await decisionRepository(context).workspace(filters.data)}}
export async function listMyPendingDecisions(){const context=await requireWorkspaceContext();requirePermission(context.membership.role,"decision.read");return {ok:true as const,decisions:await decisionRepository(context).requiringMyAction()}}
export async function readDecisionHistory(input:unknown){const data=z.object({decisionId:id}).safeParse(input);if(!data.success)return {ok:false as const,error:"Review the decision request."};const context=await requireWorkspaceContext();requirePermission(context.membership.role,"decision.read");return {ok:true as const,detail:await decisionRepository(context).byId(data.data.decisionId)}}
