"use server";
import {revalidatePath} from "next/cache";
import {and,eq,inArray,isNull} from "drizzle-orm";
import {z} from "zod";
import {database} from "@/db/client";
import {auditLogs,businesses,collaborationActivityEvents,opportunities,opportunityParticipants,opportunityStatusHistory,organizationMembers,users} from "@/db/schema";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {requirePermission} from "@/app/lib/auth/permissions";
import {activityEvent} from "@/app/lib/collaboration/domain-events";
import {OPPORTUNITY_STAGES} from "@/app/lib/opportunity/opportunity-policy";
import {logServerFailure} from "@/app/lib/observability/server-log";

type Result={ok:true;updatedAt:string}|{ok:false;error:string};
const uuid=z.string().uuid(),stage=z.enum(OPPORTUNITY_STAGES);
async function safe(action:()=>Promise<Date>):Promise<Result>{try{const updatedAt=await action();return {ok:true,updatedAt:updatedAt.toISOString()}}catch(error){if(error instanceof z.ZodError)return {ok:false,error:error.issues[0]?.message??"Review the submitted opportunity fields."};if(error instanceof Error&&error.name==="AuthorizationError")return {ok:false,error:error.message};if(error instanceof Error&&error.message==="STALE_OPPORTUNITY")return {ok:false,error:"This opportunity changed after you opened it. Refresh and try again."};logServerFailure({event:"opportunity.mutation_failed",category:error instanceof Error?error.message.slice(0,80):"unknown"});return {ok:false,error:"The opportunity could not be updated."}}}
type Tx=Parameters<Parameters<ReturnType<typeof database>["transaction"]>[0]>[0];
async function validateOwnerAndParticipants(tx:Tx,organizationId:string,ownerId:string|null,businessIds:string[]){const unique=[...new Set(businessIds)];const [ownedBusinesses,owner]=await Promise.all([tx.select({id:businesses.id}).from(businesses).where(and(eq(businesses.organizationId,organizationId),inArray(businesses.id,unique),isNull(businesses.deletedAt))),ownerId?tx.select({id:users.id}).from(organizationMembers).innerJoin(users,eq(users.id,organizationMembers.userId)).where(and(eq(organizationMembers.organizationId,organizationId),eq(organizationMembers.userId,ownerId),eq(organizationMembers.status,"ACTIVE"),isNull(users.disabledAt))).limit(1):Promise.resolve([])]);if(ownedBusinesses.length!==unique.length||ownerId&&!owner[0])throw new Error("Resource not found");return unique}
async function evidence(tx:Tx,input:{organizationId:string;actorId:string;opportunityId:string;action:string;eventType:"opportunity.updated"|"opportunity.status_changed";metadata:Record<string,unknown>}){const event=activityEvent(input.eventType,"opportunity",input.opportunityId,input.metadata);await tx.insert(auditLogs).values({organizationId:input.organizationId,actorId:input.actorId,action:input.action,entityType:"opportunity",entityId:input.opportunityId,metadata:input.metadata});await tx.insert(collaborationActivityEvents).values({organizationId:input.organizationId,actorId:input.actorId,...event})}

const updateSchema=z.object({id:uuid,title:z.string().trim().min(3).max(180),summary:z.string().trim().min(10).max(600),commercialReasoning:z.string().trim().min(10).max(1200),journeyImpact:z.string().trim().min(10).max(800),stage,priority:z.enum(["HIGH","MEDIUM","LOW"]),modeledValue:z.coerce.number().nonnegative().max(999999999999.99),ownerId:uuid.nullable(),businessIds:z.array(uuid).min(1,"Select at least one participating business.").max(100),expectedUpdatedAt:z.iso.datetime()});
export async function updateOpportunityProfile(input:unknown){return safe(async()=>{const data=updateSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"opportunity.update");const updatedAt=new Date();await database().transaction(async tx=>{const [current]=await tx.select({stage:opportunities.stage}).from(opportunities).where(and(eq(opportunities.id,data.id),eq(opportunities.organizationId,context.organization.id))).limit(1);if(!current)throw new Error("Resource not found");const businessIds=await validateOwnerAndParticipants(tx,context.organization.id,data.ownerId,data.businessIds);const [changed]=await tx.update(opportunities).set({title:data.title,summary:data.summary,commercialReasoning:data.commercialReasoning,journeyImpact:data.journeyImpact,stage:data.stage,priority:data.priority,modeledValue:String(data.modeledValue),ownerId:data.ownerId,updatedAt}).where(and(eq(opportunities.id,data.id),eq(opportunities.organizationId,context.organization.id),eq(opportunities.updatedAt,new Date(data.expectedUpdatedAt)))).returning({id:opportunities.id});if(!changed)throw new Error("STALE_OPPORTUNITY");await tx.delete(opportunityParticipants).where(and(eq(opportunityParticipants.organizationId,context.organization.id),eq(opportunityParticipants.opportunityId,data.id)));await tx.insert(opportunityParticipants).values(businessIds.map(businessId=>({organizationId:context.organization.id,opportunityId:data.id,businessId})));if(current.stage!==data.stage)await tx.insert(opportunityStatusHistory).values({organizationId:context.organization.id,opportunityId:data.id,label:data.stage,detail:"Stage changed while the opportunity profile was updated.",occurredAt:updatedAt,actorId:context.user.id});await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,opportunityId:data.id,action:"opportunity.updated",eventType:current.stage===data.stage?"opportunity.updated":"opportunity.status_changed",metadata:{component:"profile",stage:data.stage,participantCount:businessIds.length}})});revalidatePath("/workspace/opportunities");revalidatePath(`/workspace/opportunities/${data.id}`);return updatedAt})}

const stageSchema=z.object({id:uuid,stage,expectedUpdatedAt:z.iso.datetime()});
export async function moveOpportunityStage(input:unknown){return safe(async()=>{const data=stageSchema.parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"opportunity.update");const updatedAt=new Date();await database().transaction(async tx=>{const [changed]=await tx.update(opportunities).set({stage:data.stage,updatedAt}).where(and(eq(opportunities.id,data.id),eq(opportunities.organizationId,context.organization.id),eq(opportunities.updatedAt,new Date(data.expectedUpdatedAt)))).returning({id:opportunities.id});if(!changed)throw new Error("STALE_OPPORTUNITY");await tx.insert(opportunityStatusHistory).values({organizationId:context.organization.id,opportunityId:data.id,label:data.stage,detail:"Stage changed through the opportunity pipeline.",occurredAt:updatedAt,actorId:context.user.id});await evidence(tx,{organizationId:context.organization.id,actorId:context.user.id,opportunityId:data.id,action:"opportunity.stage_changed",eventType:"opportunity.status_changed",metadata:{component:"pipeline",stage:data.stage}})});revalidatePath("/workspace/opportunities");revalidatePath(`/workspace/opportunities/${data.id}`);return updatedAt})}
