"use server";
import {revalidatePath} from "next/cache";
import {and,count,eq} from "drizzle-orm";
import {z} from "zod";
import {database} from "@/db/client";
import {organizationMembers,organizations,workspacePreferences} from "@/db/schema";
import {canChangeRole,protectsFinalOwner,requirePermission} from "@/app/lib/auth/permissions";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {appendAuditLog} from "@/app/lib/data/audit";
const role=z.enum(["OWNER","ADMINISTRATOR","MANAGER","ANALYST","CONTRIBUTOR","VIEWER"]);
export async function updateMemberRole(input:unknown){const data=z.object({memberId:z.string().uuid(),role}).safeParse(input);if(!data.success)return {ok:false,error:"Invalid member role."} as const;const context=await requireWorkspaceContext();requirePermission(context.membership.role,"team.manage");const db=database();const [target]=await db.select({id:organizationMembers.id,userId:organizationMembers.userId,role:organizationMembers.role}).from(organizationMembers).where(and(eq(organizationMembers.id,data.data.memberId),eq(organizationMembers.organizationId,context.organization.id))).limit(1);if(!target)return {ok:false,error:"Member not found."} as const;if(!canChangeRole(context.membership.role,target.role,data.data.role,target.userId===context.user.id))return {ok:false,error:"This role change is not permitted."} as const;const [owners]=await db.select({value:count()}).from(organizationMembers).where(and(eq(organizationMembers.organizationId,context.organization.id),eq(organizationMembers.role,"OWNER"),eq(organizationMembers.status,"ACTIVE")));if(!protectsFinalOwner(owners.value,target.role,data.data.role))return {ok:false,error:"The final Owner cannot be demoted."} as const;await db.update(organizationMembers).set({role:data.data.role,updatedAt:new Date()}).where(eq(organizationMembers.id,target.id));await appendAuditLog({organizationId:context.organization.id,actorId:context.user.id,action:"member.role_changed",entityType:"organization_member",entityId:target.id,metadata:{from:target.role,to:data.data.role}});revalidatePath("/workspace/settings");return {ok:true} as const}
export async function updateWorkspaceSettings(input:unknown){const data=z.object({name:z.string().trim().min(2).max(120),timezone:z.string().trim().min(3).max(80),appearance:z.enum(["LIGHT","DARK","SYSTEM"])}).safeParse(input);if(!data.success)return {ok:false,error:"Review the workspace settings."} as const;const context=await requireWorkspaceContext();requirePermission(context.membership.role,"workspace.settings");const db=database();await db.update(organizations).set({workspaceName:data.data.name,timezone:data.data.timezone,updatedAt:new Date()}).where(eq(organizations.id,context.organization.id));await db.insert(workspacePreferences).values({organizationId:context.organization.id,userId:context.user.id,appearance:data.data.appearance,activeOrganizationId:context.organization.id}).onConflictDoUpdate({target:[workspacePreferences.organizationId,workspacePreferences.userId],set:{appearance:data.data.appearance,updatedAt:new Date()}});await appendAuditLog({organizationId:context.organization.id,actorId:context.user.id,action:"workspace.settings_changed",entityType:"organization",entityId:context.organization.id,metadata:{timezone:data.data.timezone,appearance:data.data.appearance}});revalidatePath("/workspace/settings");return {ok:true} as const}
