"use server";
import {revalidatePath} from "next/cache";
import {and,eq,inArray,sql} from "drizzle-orm";
import {z} from "zod";
import {database} from "@/db/client";
import {businesses,campaignParticipants,campaigns,journeyStages,journeys,opportunities,opportunityParticipants,opportunityStatusHistory,organizationMembers} from "@/db/schema";
import {requireWorkspaceContext} from "@/app/lib/auth/workspace-context";
import {requirePermission} from "@/app/lib/auth/permissions";
import {appendAuditLog} from "@/app/lib/data/audit";
import {collaborationRepository,deterministicActivity} from "@/app/lib/data/collaboration-repository";

type Result={ok:true;id:string}|{ok:false;error:string};const uuid=z.string().uuid();
async function safe(action:()=>Promise<string>):Promise<Result>{try{return {ok:true,id:await action()}}catch(error){if(error instanceof z.ZodError)return {ok:false,error:error.issues[0]?.message??"Review the submitted values."};if(error instanceof Error&&error.name==="AuthorizationError")return {ok:false,error:error.message};if(error instanceof Error&&error.message==="DUPLICATE_BUSINESS")return {ok:false,error:"A business with this name already exists in the workspace."};return {ok:false,error:"The record could not be created."}}}
async function validateBusinesses(organizationId:string,ids:string[]){const unique=[...new Set(ids)];if(!unique.length)return [];const owned=await database().select({id:businesses.id}).from(businesses).where(and(eq(businesses.organizationId,organizationId),inArray(businesses.id,unique)));if(owned.length!==unique.length)throw new Error("Resource not found");return unique}

export async function createBusinessV2(input:unknown){return safe(async()=>{const data=z.object({name:z.string().trim().min(2).max(160),category:z.string().trim().min(2).max(120),location:z.string().trim().min(2).max(400),description:z.string().trim().min(20).max(600),industryId:uuid.nullable(),regionId:uuid.nullable()}).parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");const db=database(),duplicate=await db.select({id:businesses.id}).from(businesses).where(and(eq(businesses.organizationId,context.organization.id),sql`lower(${businesses.name}) = lower(${data.name})`,sql`${businesses.deletedAt} is null`)).limit(1);if(duplicate[0])throw new Error("DUPLICATE_BUSINESS");const [record]=await db.insert(businesses).values({organizationId:context.organization.id,name:data.name,initials:data.name.split(/\s+/).map(part=>part[0]).join("").slice(0,3).toUpperCase(),location:data.location,category:data.category,description:data.description,industryId:data.industryId,regionId:data.regionId,status:"PENDING",verification:"In review",partnerScore:50,opportunityScore:50}).returning({id:businesses.id});await appendAuditLog({organizationId:context.organization.id,actorId:context.user.id,action:"business.created",entityType:"business",entityId:record.id});await collaborationRepository(context).activity.append(deterministicActivity("business.created","business",record.id));revalidatePath("/workspace");return record.id})}

export async function createOpportunityV2(input:unknown){return safe(async()=>{const data=z.object({title:z.string().trim().min(3).max(180),summary:z.string().trim().min(10).max(600),commercialReasoning:z.string().trim().min(10).max(1200),journeyImpact:z.string().trim().min(10).max(800),priority:z.enum(["HIGH","MEDIUM","LOW"]),stage:z.enum(["IDENTIFIED","QUALIFIED"]),ownerId:uuid.nullable(),modeledValue:z.coerce.number().nonnegative().default(0),businessIds:z.array(uuid).min(1,"Select at least one connected business.").max(100)}).parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"opportunity.update");const ids=await validateBusinesses(context.organization.id,data.businessIds),db=database();if(data.ownerId){const owner=await db.select({id:organizationMembers.id}).from(organizationMembers).where(and(eq(organizationMembers.organizationId,context.organization.id),eq(organizationMembers.userId,data.ownerId),eq(organizationMembers.status,"ACTIVE"))).limit(1);if(!owner[0])throw new Error("Resource not found")}const id=await db.transaction(async tx=>{const [record]=await tx.insert(opportunities).values({organizationId:context.organization.id,title:data.title,summary:data.summary,commercialReasoning:data.commercialReasoning,journeyImpact:data.journeyImpact,status:"PENDING",stage:data.stage,priority:data.priority,ownerId:data.ownerId,modeledValue:String(data.modeledValue)}).returning({id:opportunities.id});await tx.insert(opportunityParticipants).values(ids.map(businessId=>({organizationId:context.organization.id,opportunityId:record.id,businessId})));await tx.insert(opportunityStatusHistory).values({organizationId:context.organization.id,opportunityId:record.id,label:data.stage,detail:"Opportunity created in the workspace.",occurredAt:new Date(),actorId:context.user.id});return record.id});await appendAuditLog({organizationId:context.organization.id,actorId:context.user.id,action:"opportunity.created",entityType:"opportunity",entityId:id});await collaborationRepository(context).activity.append(deterministicActivity("opportunity.created","opportunity",id));revalidatePath("/workspace");return id})}

export async function createCampaignV2(input:unknown){return safe(async()=>{const data=z.object({title:z.string().trim().min(3).max(180),objective:z.string().trim().min(10).max(800),status:z.enum(["DRAFT","PENDING"]),budget:z.coerce.number().nonnegative(),modeledValue:z.coerce.number().nonnegative(),startDate:z.union([z.iso.date(),z.literal("")]),endDate:z.union([z.iso.date(),z.literal("")]),businessIds:z.array(uuid).max(100)}).refine(value=>!value.startDate||!value.endDate||value.endDate>=value.startDate,{message:"End date must follow start date."}).parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");const ids=await validateBusinesses(context.organization.id,data.businessIds),db=database();const id=await db.transaction(async tx=>{const [record]=await tx.insert(campaigns).values({organizationId:context.organization.id,title:data.title,objective:data.objective,status:data.status,budget:String(data.budget),modeledValue:String(data.modeledValue),startDate:data.startDate||null,endDate:data.endDate||null}).returning({id:campaigns.id});if(ids.length)await tx.insert(campaignParticipants).values(ids.map(businessId=>({organizationId:context.organization.id,campaignId:record.id,businessId})));return record.id});await appendAuditLog({organizationId:context.organization.id,actorId:context.user.id,action:"campaign.created",entityType:"campaign",entityId:id});await collaborationRepository(context).activity.append(deterministicActivity("campaign.created","campaign",id));revalidatePath("/workspace");return id})}

export async function createJourneyV2(input:unknown){return safe(async()=>{const data=z.object({name:z.string().trim().min(3).max(180),journeyType:z.string().trim().min(2).max(80),objective:z.string().trim().min(10).max(600),target:z.string().trim().min(2).max(240),outcome:z.string().trim().min(10).max(600),businessIds:z.array(uuid).max(100)}).parse(input),context=await requireWorkspaceContext();requirePermission(context.membership.role,"business.manage");const ids=await validateBusinesses(context.organization.id,data.businessIds),id=await database().transaction(async tx=>{const [record]=await tx.insert(journeys).values({organizationId:context.organization.id,name:data.name,coverage:0,completion:0}).returning({id:journeys.id});await tx.insert(journeyStages).values({organizationId:context.organization.id,journeyId:record.id,businessId:ids[0]??null,position:0,title:data.journeyType,touchpoint:`${data.objective} Target: ${data.target}. Intended outcome: ${data.outcome}`,status:"GAP"});return record.id});await appendAuditLog({organizationId:context.organization.id,actorId:context.user.id,action:"journey.created",entityType:"journey",entityId:id});revalidatePath("/workspace");return id})}
