import "server-only";
import {randomUUID} from "node:crypto";
import {and,desc,eq,gt,isNull,lt,ne} from "drizzle-orm";
import {database} from "@/db/client";
import {auditLogs,authSessionRegistry} from "@/db/schema";
import type {WorkspaceContext} from "./types";
import {describeClient,REMEMBERED_SESSION_SECONDS,STANDARD_SESSION_SECONDS} from "./session-duration-policy";
export async function registerAuthenticationSession(input:{userId:string;rememberMe:boolean;userAgent?:string|null;location?:string|null}){const id=randomUUID(),now=new Date(),maxAge=input.rememberMe?REMEMBERED_SESSION_SECONDS:STANDARD_SESSION_SECONDS,{browser,platform}=describeClient(input.userAgent??"");await database().insert(authSessionRegistry).values({id,userId:input.userId,userAgent:(input.userAgent??"").slice(0,500)||null,browser,platform,approximateLocation:(input.location??"").slice(0,160)||null,lastActivityAt:now,expiresAt:new Date(now.getTime()+maxAge*1000)});return {id,expiresAt:new Date(now.getTime()+maxAge*1000).getTime()}}
export async function lookupAuthenticationSession(id:string,userId:string){const now=new Date();const [session]=await database().select({id:authSessionRegistry.id,revokedAt:authSessionRegistry.revokedAt,expiresAt:authSessionRegistry.expiresAt,lastActivityAt:authSessionRegistry.lastActivityAt}).from(authSessionRegistry).where(and(eq(authSessionRegistry.id,id),eq(authSessionRegistry.userId,userId))).limit(1);if(!session||session.revokedAt||session.expiresAt<=now)return null;if(session.lastActivityAt.getTime()<now.getTime()-5*60_000)await database().update(authSessionRegistry).set({lastActivityAt:now}).where(and(eq(authSessionRegistry.id,id),lt(authSessionRegistry.lastActivityAt,new Date(now.getTime()-5*60_000))));return session}
export async function listAuthenticationSessions(userId:string){return database().select({id:authSessionRegistry.id,browser:authSessionRegistry.browser,platform:authSessionRegistry.platform,approximateLocation:authSessionRegistry.approximateLocation,lastActivityAt:authSessionRegistry.lastActivityAt,createdAt:authSessionRegistry.createdAt,expiresAt:authSessionRegistry.expiresAt}).from(authSessionRegistry).where(and(eq(authSessionRegistry.userId,userId),isNull(authSessionRegistry.revokedAt),gt(authSessionRegistry.expiresAt,new Date()))).orderBy(desc(authSessionRegistry.lastActivityAt)).limit(50)}
export async function revokeAuthenticationSession(context:WorkspaceContext,sessionId:string,currentSessionId:string){if(sessionId===currentSessionId)throw new Error("CURRENT_SESSION");const now=new Date();return database().transaction(async tx=>{const [updated]=await tx.update(authSessionRegistry).set({revokedAt:now}).where(and(eq(authSessionRegistry.id,sessionId),eq(authSessionRegistry.userId,context.user.id),isNull(authSessionRegistry.revokedAt))).returning({id:authSessionRegistry.id});if(updated)await tx.insert(auditLogs).values({organizationId:context.organization.id,actorId:context.user.id,action:"session.revoked",entityType:"authentication",entityId:updated.id,metadata:{target:"other_session"}});return updated??null})}
export async function revokeOtherAuthenticationSessions(context:WorkspaceContext,currentSessionId:string){const now=new Date();return database().transaction(async tx=>{const revoked=await tx.update(authSessionRegistry).set({revokedAt:now}).where(and(eq(authSessionRegistry.userId,context.user.id),ne(authSessionRegistry.id,currentSessionId),isNull(authSessionRegistry.revokedAt))).returning({id:authSessionRegistry.id});await tx.insert(auditLogs).values({organizationId:context.organization.id,actorId:context.user.id,action:"session.others_invalidated",entityType:"authentication",entityId:context.user.id,metadata:{count:revoked.length}});return revoked.length})}
export async function revokeCurrentAuthenticationSession(context:WorkspaceContext,currentSessionId:string){const now=new Date();return database().transaction(async tx=>{const [revoked]=await tx.update(authSessionRegistry).set({revokedAt:now}).where(and(eq(authSessionRegistry.id,currentSessionId),eq(authSessionRegistry.userId,context.user.id),isNull(authSessionRegistry.revokedAt))).returning({id:authSessionRegistry.id});if(revoked)await tx.insert(auditLogs).values({organizationId:context.organization.id,actorId:context.user.id,action:"session.current_signed_out",entityType:"authentication",entityId:currentSessionId,metadata:{}});return revoked??null})}
