import "server-only";
import {cache} from "react";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {and,eq,isNull} from "drizzle-orm";
import {auth} from "@/auth";
import {database} from "@/db/client";
import {organizationMembers,organizations,users} from "@/db/schema";
import type {AppRole,WorkspaceContext} from "./types";
export const getWorkspaceContext=cache(async():Promise<WorkspaceContext|null>=>{const session=await auth();if(!session?.user?.id||!session.user.email)return null;const developmentDemo=process.env.NODE_ENV!=="production"&&process.env.NEFE_DEMO_AUTH_ENABLED==="true"&&!process.env.DATABASE_URL;if(developmentDemo)return {user:{id:session.user.id,name:session.user.name??"Demo Owner",email:session.user.email},organization:{id:"00000000-0000-4000-8000-000000000010",name:"NEFE RAK Demonstration",workspaceName:"RAK Connected Destination Pilot"},membership:{id:"00000000-0000-4000-8000-000000000020",role:"OWNER",status:"ACTIVE"}};if(!process.env.DATABASE_URL)return null;const requested=(await cookies()).get("nefe-active-organization")?.value;const db=database();const rows=await db.select({userId:users.id,userName:users.name,userEmail:users.email,memberId:organizationMembers.id,role:organizationMembers.role,status:organizationMembers.status,organizationId:organizations.id,organizationName:organizations.name,workspaceName:organizations.workspaceName}).from(organizationMembers).innerJoin(users,eq(users.id,organizationMembers.userId)).innerJoin(organizations,eq(organizations.id,organizationMembers.organizationId)).where(and(eq(organizationMembers.userId,session.user.id),eq(organizationMembers.status,"ACTIVE")));const selected=rows.find(row=>row.organizationId===requested)??rows[0];if(!selected)return null;return {user:{id:selected.userId,name:selected.userName??selected.userEmail,email:selected.userEmail},organization:{id:selected.organizationId,name:selected.organizationName,workspaceName:selected.workspaceName},membership:{id:selected.memberId,role:selected.role as AppRole,status:selected.status}}});
export async function requireWorkspaceContext(){const session=await auth();if(!session?.user)redirect(`/sign-in?returnTo=${encodeURIComponent("/workspace/dashboard")}`);const context=await getWorkspaceContext();if(!context)redirect("/onboarding/organization");if(context.membership.status!=="ACTIVE")redirect("/access-denied");return context}
export async function requireTenantResource<T extends {organizationId:string}|undefined>(resource:T,organizationId:string){if(!resource||resource.organizationId!==organizationId)return null;return resource}
export async function getAvailableWorkspaces(){const session=await auth();if(!session?.user?.id||!process.env.DATABASE_URL)return [];return database().select({id:organizations.id,name:organizations.name,workspaceName:organizations.workspaceName}).from(organizationMembers).innerJoin(organizations,eq(organizations.id,organizationMembers.organizationId)).where(and(eq(organizationMembers.userId,session.user.id),eq(organizationMembers.status,"ACTIVE"),isNull(organizations.deletedAt))).orderBy(organizations.workspaceName)}
