"use client";

import { motion } from "framer-motion";
import FinancialSubnav from "../components/financial-subnav";

const utilities=[
  ["Rewards","Recognize valuable customer and merchant activity across the ecosystem."],
  ["Access","Unlock premium experiences, partner opportunities and member-only benefits."],
  ["Membership","Support tiered participation for customers and verified businesses."],
  ["Incentives","Align merchants, partners and customers around measurable commercial outcomes."],
  ["Merchant Fee Discounts","Reduce selected platform fees when utility participation is used."],
  ["Campaign Credits","Apply utility credits toward premium campaigns and growth tools."],
  ["Partner Rewards","Reward businesses that generate verified network value and referrals."],
  ["Future Payments","Enable optional future transaction utility without changing current merchant workflows."],
];
const flywheel=["Business activity grows","More referrals convert","Rewards are issued","Members return","Partners gain value","New merchants join"];

export default function TokenUtilityEconomics(){
  return <main className="min-h-screen bg-[#F7F5F9] text-[#1B1725]"><FinancialSubnav/><section className="botchain-hero relative overflow-hidden px-5 py-20"><div className="engine-grid absolute inset-0"/><div className="relative mx-auto max-w-[1180px]"><span className="inline-flex rounded-full border border-[#DCCF9E] bg-[#FFF9E9]/80 px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#8B651E]">Leadership utility brief</span><h1 className="mt-7 max-w-5xl text-5xl font-semibold tracking-[-.06em] sm:text-7xl">Utility that grows with real commercial activity.</h1><p className="mt-6 max-w-2xl text-[12px] leading-6 text-[#746D7A]">NEFE remains a business platform first. Utility supports rewards, access and incentives quietly—without asking merchants or customers to think like crypto users.</p></div></section><div className="page-shell py-14">
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[28px] border border-[#E3DEE7] bg-white p-7"><p className="engine-eyebrow">Standard commerce</p><h2 className="mt-3 text-3xl font-semibold">Merchants continue operating in AED.</h2><p className="mt-4 text-[10px] leading-5 text-[#7C7581]">Subscriptions, campaigns and customer journeys work through familiar commercial workflows. No token knowledge is required.</p><div className="mt-7 space-y-3">{["Transparent AED pricing","Normal merchant dashboards","Familiar customer rewards","Optional utility participation"].map(item=><p key={item} className="flex gap-3 text-[9px]"><span className="text-[#5E3BEE]">✓</span>{item}</p>)}</div></div><div className="rounded-[28px] bg-gradient-to-br from-[#171120] via-[#2B1B50] to-[#5D38C8] p-7 text-white"><p className="text-[8px] font-bold uppercase tracking-[.14em] text-[#DDBD68]">NEFE utility layer</p><h2 className="mt-3 text-3xl font-semibold">Benefits appear when activity creates value.</h2><p className="mt-4 text-[10px] leading-5 text-white/45">Utility participation can improve fees, access, rewards and discovery while staying invisible inside the customer and merchant experience.</p><div className="mt-7 grid grid-cols-2 gap-3">{["Lower fees","Campaign credits","Premium placement","Partner rewards","Loyalty bonuses","Priority discovery"].map(item=><p key={item} className="rounded-xl bg-white/[.07] p-3 text-[8px]"><span className="mr-2 text-[#DDBD68]">✦</span>{item}</p>)}</div></div></section>
    <section className="mt-20"><p className="engine-eyebrow">Utility architecture</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Eight practical roles. One connected ecosystem.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{utilities.map(([name,description],index)=><motion.article whileHover={{y:-4}} key={name} className="finance-card p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl text-[8px] font-bold ${index>3?"bg-[#FFF4D9] text-[#956B1C]":"bg-[#F0ECFF] text-[#5E3BEE]"}`}>0{index+1}</span><h3 className="mt-5 text-[12px] font-semibold">{name}</h3><p className="mt-2 text-[8px] leading-4 text-[#89828E]">{description}</p></motion.article>)}</div></section>
    <section className="mt-20 overflow-hidden rounded-[30px] bg-[#120D1A] p-7 text-white sm:p-10"><p className="text-[8px] font-bold uppercase tracking-[.15em] text-[#BDA8F0]">Utility flywheel</p><h2 className="mt-3 text-3xl font-semibold">Platform activity strengthens utility—and utility strengthens activity.</h2><div className="mt-10 grid gap-3 lg:grid-cols-6">{flywheel.map((item,index)=><div key={item} className="relative flex items-center"><motion.div initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} transition={{delay:index*.08}} className={`w-full rounded-[18px] border p-5 ${index===5?"border-[#D3AA51]/35 bg-[#D3AA51]/10":"border-white/10 bg-white/[.05]"}`}><span className={`text-[7px] font-bold ${index===5?"text-[#E1C16C]":"text-[#A98DEB]"}`}>0{index+1}</span><p className="mt-4 text-[9px] font-semibold">{item}</p></motion.div>{index<5&&<span className="absolute -right-2 z-10 hidden text-[#8B69E8] lg:block">→</span>}</div>)}</div><div className="mt-8 rounded-[18px] border border-white/10 bg-white/[.04] p-5"><p className="text-[9px] leading-5 text-white/55">Utility demand is tied to participation: campaigns launched, referrals converted, memberships used and rewards redeemed. The commercial platform creates the activity first.</p></div></section>
    <section className="mt-20 grid gap-4 lg:grid-cols-3"><div className="finance-card p-6"><p className="engine-eyebrow">Activity-linked</p><p className="mt-4 text-2xl font-semibold">Utility follows verified use.</p><p className="mt-3 text-[8px] leading-4 text-[#89828E]">The model emphasizes actual merchant and customer participation rather than speculative narratives.</p></div><div className="finance-card p-6"><p className="engine-eyebrow">Commercially optional</p><p className="mt-4 text-2xl font-semibold">AED remains first-class.</p><p className="mt-3 text-[8px] leading-4 text-[#89828E]">Businesses can access NEFE’s core commercial services without using utility features.</p></div><div className="finance-card p-6"><p className="engine-eyebrow">Ecosystem aligned</p><p className="mt-4 text-2xl font-semibold">Value returns to participants.</p><p className="mt-3 text-[8px] leading-4 text-[#89828E]">Rewards and incentives recognize merchants and customers who increase network value.</p></div></section>
    <section className="mt-20 rounded-[30px] bg-gradient-to-r from-[#F0ECFF] to-[#FFF6DF] p-8"><p className="engine-eyebrow">The strategic role</p><h2 className="mt-3 max-w-4xl text-3xl font-semibold tracking-[-.045em]">NEFE utility is not the product. It is the incentive and access layer that can make a successful commercial network more valuable.</h2><p className="mt-5 max-w-3xl text-[10px] leading-5 text-[#756D7A]">As more businesses collaborate, more customers participate and more commercial activity becomes measurable, utility can support lower fees, stronger loyalty, premium access and future transaction services.</p></section>
  </div></main>
}

