"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { useState } from "react";
import FinancialSubnav from "../components/financial-subnav";

const plans=[
  {name:"Starter",price:"AED 299",best:"Independent businesses testing their first partner referrals.",features:["Business listing","Basic analytics","Referral participation","Merchant dashboard"],tone:"light"},
  {name:"Growth",price:"AED 999",best:"Growing businesses ready to launch repeatable partner campaigns.",features:["Everything in Starter","AI recommendations","Campaign Builder","Referral Intelligence","Commercial dashboard","Partner discovery"],tone:"purple",popular:true},
  {name:"Enterprise",price:"Custom Pricing",best:"Groups, destinations and multi-location commercial ecosystems.",features:["Unlimited locations","API access","White-label platform","Dedicated support","Commercial AI","Custom integrations","Priority onboarding"],tone:"dark"},
];
const comparison=[
  ["Verified business listing",true,true,true],["Referral participation",true,true,true],["Merchant dashboard",true,true,true],["AI recommendations",false,true,true],["Campaign Builder",false,true,true],["Partner discovery","Limited",true,true],["Advanced analytics",false,true,true],["API access",false,false,true],["White-label platform",false,false,true],["Dedicated commercial support",false,false,true],
];
const faqs=[
  ["Is there a setup fee?","Starter and Growth are designed without a mandatory setup fee for pilot merchants. Enterprise implementation is scoped separately."],
  ["Can I change plans?","Yes. Businesses can upgrade as partner activity, campaigns and intelligence requirements grow."],
  ["Does NEFE process customer payments?","Not in the current pilot. NEFE coordinates discovery, referrals, campaigns and commercial intelligence."],
  ["How are referral fees handled?","Referral economics are agreed transparently by participating businesses before a campaign launches."],
  ["Is blockchain knowledge required?","No. Merchant workflows remain familiar and utility infrastructure stays invisible unless explicitly used."],
];

export default function PricingPage(){
  const [open,setOpen]=useState(0);
  return <main className="min-h-screen bg-[#F7F5F9] text-[#1B1725]"><FinancialSubnav/><section className="financial-hero relative overflow-hidden px-5 py-20 text-center"><div className="engine-grid absolute inset-0"/><div className="relative mx-auto max-w-4xl"><span className="inline-flex rounded-full border border-[#DDD3F8] bg-white/70 px-3 py-2 text-[8px] font-bold uppercase tracking-[.15em] text-[#5E3BEE]">Merchant pricing</span><h1 className="mt-7 text-5xl font-semibold tracking-[-.06em] sm:text-7xl">Start simply. Grow through the network.</h1><p className="mx-auto mt-6 max-w-2xl text-[12px] leading-6 text-[#746D7A]">Clear commercial plans for businesses that want more referrals, stronger partnerships and measurable shared revenue.</p></div></section><div className="page-shell py-14">
    <section className="grid gap-4 lg:grid-cols-3">{plans.map(plan=><motion.article whileHover={{y:-7}} key={plan.name} className={`relative overflow-hidden rounded-[28px] border p-7 ${plan.tone==="purple"?"border-[#7657D8] bg-gradient-to-br from-[#5E3BEE] to-[#2D1B60] text-white shadow-[0_25px_65px_rgba(75,43,158,.2)]":plan.tone==="dark"?"border-[#30273B] bg-[#19131F] text-white":"border-[#E3DEE7] bg-white"}`}>{plan.popular&&<span className="absolute right-5 top-5 rounded-full bg-[#D8B55D] px-3 py-1.5 text-[6px] font-bold text-[#3B2A0D]">MOST POPULAR</span>}<p className={`text-[8px] font-bold uppercase tracking-[.14em] ${plan.tone==="light"?"text-[#6F53D0]":"text-white/45"}`}>{plan.name}</p><h2 className="mt-5 text-3xl font-semibold">{plan.price}</h2><p className={`mt-2 text-[7px] ${plan.tone==="light"?"text-[#98919D]":"text-white/35"}`}>{plan.name==="Enterprise"?"Tailored annual agreement":"per month"}</p><div className={`my-6 h-px ${plan.tone==="light"?"bg-[#EEEAF1]":"bg-white/10"}`}/><div className="space-y-3">{plan.features.map(feature=><p key={feature} className={`flex gap-3 text-[9px] ${plan.tone==="light"?"text-[#5D5663]":"text-white/65"}`}><span className={plan.tone==="purple"?"text-[#E3C36D]":"text-[#6848D4]"}>✓</span>{feature}</p>)}</div><div className={`mt-7 rounded-[15px] p-4 ${plan.tone==="light"?"bg-[#F8F6FA]":"bg-white/[.06]"}`}><p className={`text-[6px] font-bold uppercase ${plan.tone==="light"?"text-[#8E8793]":"text-white/35"}`}>Best for</p><p className={`mt-2 text-[8px] leading-4 ${plan.tone==="light"?"text-[#5D5663]":"text-white/60"}`}>{plan.best}</p></div><Link href="/onboarding" className={`mt-6 flex justify-center rounded-xl py-3 text-[8px] font-bold ${plan.tone==="purple"?"bg-white text-[#5032C4]":plan.tone==="dark"?"bg-[#6845D9] text-white":"bg-[#F0ECFF] text-[#5E3BEE]"}`}>Join Pilot</Link></motion.article>)}</section>
    <section className="mt-20"><p className="engine-eyebrow">Feature comparison</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Choose the right commercial depth.</h2><div className="mt-7 overflow-hidden rounded-[24px] border border-[#E3DEE7] bg-white"><div className="grid grid-cols-[1.5fr_repeat(3,1fr)] bg-[#171120] px-5 py-4 text-[8px] font-bold text-white"><span>Capability</span><span>Starter</span><span className="text-[#CDBAFF]">Growth</span><span className="text-[#E0BF68]">Enterprise</span></div>{comparison.map(([feature,...values],index)=><div key={String(feature)} className={`grid grid-cols-[1.5fr_repeat(3,1fr)] px-5 py-4 text-[8px] ${index%2?"bg-[#FAF9FB]":"bg-white"}`}><b>{feature}</b>{values.map((value,i)=><span key={i} className={value===true?"font-bold text-[#29916E]":value===false?"text-[#C0BAC4]":"font-semibold text-[#5E3BEE]"}>{value===true?"✓ Included":value===false?"—":String(value)}</span>)}</div>)}</div></section>
    <section className="mt-20 grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="engine-eyebrow">Questions</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Merchant pricing FAQ.</h2><p className="mt-4 text-[10px] leading-5 text-[#7F7884]">Everything a pilot partner needs to understand before joining the network.</p></div><div className="space-y-2">{faqs.map(([question,answer],index)=><button key={question} onClick={()=>setOpen(open===index?-1:index)} className="w-full rounded-[17px] border border-[#E4DFE8] bg-white p-5 text-left"><div className="flex items-center justify-between"><b className="text-[10px]">{question}</b><span className="text-[#5E3BEE]">{open===index?"−":"+"}</span></div>{open===index&&<motion.p initial={{opacity:0,y:-4}} animate={{opacity:1,y:0}} className="mt-3 text-[8px] leading-5 text-[#7E7783]">{answer}</motion.p>}</button>)}</div></section>
    <section className="mt-20 rounded-[30px] bg-gradient-to-br from-[#5E3BEE] to-[#2D1A60] p-9 text-center text-white"><p className="text-[8px] font-bold uppercase tracking-[.15em] text-[#D7C9FA]">UAE pilot</p><h2 className="mt-4 text-3xl font-semibold">Build your first NEFE partnership.</h2><p className="mx-auto mt-3 max-w-xl text-[9px] leading-5 text-white/50">Join a controlled merchant pilot and validate referrals, bundled experiences and repeat customer growth.</p><Link href="/onboarding" className="mt-7 inline-flex rounded-xl bg-white px-6 py-3 text-[9px] font-bold text-[#5032C4]">Join Pilot →</Link></section>
  </div></main>
}

