"use client";

import Link from "next/link";
import { useState } from "react";
import BrandLogo from "../components/brand-logo";
import Image from "next/image";

const phases = [
  { phase:"Phase 1", label:"Foundation", period:"Now — 2026", thesis:"Prove partner-led commerce in one premium market.", items:["Business Platform","Consumer App","Experience Builder","Commerce Graph"], color:"#7D5AF0" },
  { phase:"Phase 2", label:"Intelligence", period:"2027", thesis:"Turn network behavior into an autonomous growth engine.", items:["AI Growth Engine","Merchant Intelligence","Premium Membership","Rewards Layer"], color:"#C89A41" },
  { phase:"Phase 3", label:"Infrastructure", period:"2028", thesis:"Become embedded infrastructure for enterprise commerce.", items:["Enterprise APIs","Payment Infrastructure","Cross-border Commerce"], color:"#4FA58B" },
  { phase:"Phase 4", label:"Network", period:"2029+", thesis:"Connect businesses and customer value across global markets.", items:["Global Commerce Network"], color:"#557BD1" },
];

const revenueLayers = [
  { name:"Business Subscription", detail:"Recurring SaaS access for every business", value:"AED 14.4M ARR", color:"#8060ED" },
  { name:"Premium Partner Membership", detail:"Advanced visibility, intelligence and privileges", value:"AED 9.8M ARR", color:"#9A72DD" },
  { name:"Campaign Marketplace", detail:"Promoted collaborations and performance tools", value:"AED 8.2M ARR", color:"#BA8C9A" },
  { name:"Business Intelligence", detail:"Premium data products and decision support", value:"AED 6.7M ARR", color:"#C99C52" },
  { name:"Enterprise Services", detail:"Custom orchestration for groups and destinations", value:"AED 5.4M ARR", color:"#71A792" },
  { name:"Future Transaction Infrastructure", detail:"Quiet infrastructure for multi-merchant transactions", value:"AED 3.5M ARR", color:"#5579C5" },
];

function Logo({ light = false }: { light?:boolean }) {
  return <BrandLogo variant={light ? "white" : "purple"} priority />;
}

function SectionLabel({ number, children, dark = false }: { number:string; children:React.ReactNode; dark?:boolean }) {
  return <div className={`flex items-center gap-3 text-[9px] font-bold uppercase tracking-[.18em] ${dark?"text-[#B8A4FA]":"text-[#6F50DA]"}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-[7px] ${dark?"bg-white/10":"bg-[#EEE9FF]"}`}>{number}</span>{children}</div>;
}

export default function FounderRoom() {
  const [activePhase,setActivePhase] = useState(0);

  return <main className="founder-room-page overflow-hidden bg-[#FAF9FB] text-[#171322]">
    <section className="founder-hero relative grid min-h-[92vh] place-items-center px-5 pb-20 pt-32 text-center">
      <div className="founder-grid absolute inset-0"/><div className="founder-glow one"/><div className="founder-glow two"/>
      <div className="relative z-10 mx-auto max-w-[1050px]"><div className="mx-auto flex w-fit items-center gap-2 rounded-full border border-[#DED5F8] bg-white/65 px-3 py-2 text-[9px] font-bold uppercase tracking-[.17em] text-[#5E3BEE] shadow-sm backdrop-blur"><span className="text-[#C0963F]">✦</span>The Founder Room</div><h1 className="mt-8 text-[45px] font-semibold leading-[1.04] tracking-[-.06em] sm:text-[68px] lg:text-[86px]">Building the Commercial Layer for <span className="gradient-text">Connected Businesses</span></h1><p className="mx-auto mt-8 max-w-[690px] text-base leading-8 text-[#6D6674] sm:text-lg">Businesses already serve the same customers.<br/><b className="font-medium text-[#383141]">NEFE helps them grow together instead of growing alone.</b></p><div className="mt-12 flex flex-col items-center justify-center gap-3 sm:flex-row"><Link href="#opportunity" className="inline-flex h-13 items-center gap-2 rounded-xl bg-[#5E3BEE] px-6 text-[11px] font-semibold text-white shadow-[0_15px_35px_rgba(94,59,238,.25)] transition hover:-translate-y-1">Explore the thesis <span>↓</span></Link><Link href="/executive-insights" className="inline-flex h-13 items-center rounded-xl border border-[#DED8E4] bg-white/75 px-6 text-[11px] font-semibold text-[#4D4655] shadow-sm backdrop-blur transition hover:-translate-y-1">View executive insights</Link></div></div>
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 text-[7px] font-bold uppercase tracking-[.2em] text-[#A19AA7]"><span className="mx-auto mb-2 block h-10 w-px bg-gradient-to-b from-transparent to-[#8F7FC1]"/>The strategic thesis</div>
    </section>

    <section className="border-y border-[#E9E4EC] bg-white/70 px-5 py-5 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-[1240px] flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[7px] font-bold uppercase tracking-[.14em] text-[#8D8692]">Financial architecture</p><p className="mt-1 text-[10px] font-semibold">Explore NEFE’s commercial model by audience.</p></div><div className="flex flex-wrap gap-2"><Link href="/pricing" className="rounded-xl bg-[#F8F6FA] px-4 py-3 text-[8px] font-semibold">Merchant Pricing</Link><Link href="/business-model" className="rounded-xl bg-[#F0ECFF] px-4 py-3 text-[8px] font-semibold text-[#5E3BEE]">Business Model</Link><Link href="/financial-model" className="rounded-xl bg-[#20172E] px-4 py-3 text-[8px] font-semibold text-white">Financial Model</Link><Link href="/token-utility-economics" className="rounded-xl bg-[#FFF5DD] px-4 py-3 text-[8px] font-semibold text-[#8D671D]">Token Utility</Link></div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-28 sm:px-8 sm:py-36">
      <SectionLabel number="01">The Problem</SectionLabel><div className="mt-5 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-2xl text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Business software optimizes the company.<br/><span className="text-[#9A93A1]">It ignores the ecosystem.</span></h2><p className="max-w-sm text-[12px] leading-6 text-[#7C7582]">The customer journey crosses businesses. The systems managing that journey do not.</p></div>
      <div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
        ["01","Businesses operate in isolation.","Data, customers and commercial momentum remain trapped inside individual companies."],
        ["02","Customer relationships end after one purchase.","The next relevant business has no intelligent way to continue the relationship."],
        ["03","Cross-business opportunities are lost.","Partnerships happen manually, without infrastructure to scale or measure them."],
        ["04","Loyalty is fragmented.","Customers collect disconnected accounts, offers and benefits that never compound."],
      ].map(([n,title,detail])=><article key={n} className="group min-h-64 rounded-[24px] border border-[#E8E3EB] bg-white p-6 shadow-[0_6px_24px_rgba(43,30,66,.03)] transition hover:-translate-y-2 hover:border-[#D3C7F8] hover:shadow-[0_22px_50px_rgba(53,36,96,.09)]"><span className="text-[9px] font-bold text-[#B3ACB8]">{n}</span><div className="mt-12 h-px w-10 bg-gradient-to-r from-[#5E3BEE] to-[#D1A646] transition-all group-hover:w-20"/><h3 className="mt-6 text-[17px] font-semibold leading-6 tracking-[-.025em]">{title}</h3><p className="mt-3 text-[10px] leading-5 text-[#88818D]">{detail}</p></article>)}</div>
    </section>

    <section id="opportunity" className="relative overflow-hidden bg-[#110D1A] py-28 text-white sm:py-36">
      <div className="founder-dark-grid absolute inset-0"/><div className="mx-auto grid max-w-[1240px] items-center gap-16 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr]">
        <div className="relative z-10"><SectionLabel number="02" dark>The Opportunity</SectionLabel><h2 className="mt-6 text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Instead of competing for customers...</h2><p className="mt-7 text-2xl leading-tight tracking-[-.035em] text-[#C8BAF9]">Businesses multiply customer value together.</p><p className="mt-6 max-w-md text-[12px] leading-6 text-white/45">NEFE turns every completed transaction into the beginning of a relevant next experience—creating a network that becomes more valuable with every participating business.</p><div className="mt-9 grid grid-cols-3 gap-3">{[["2.8×","Customer value"],["22%","Revenue lift"],["42.8%","Repeat rate"]].map(([v,l])=><div key={l} className="rounded-xl border border-white/8 bg-white/[.04] p-3"><p className="text-lg font-semibold">{v}</p><p className="mt-1 text-[7px] text-white/35">{l}</p></div>)}</div></div>
        <div className="founder-ecosystem relative mx-auto h-[510px] w-full max-w-[650px]">
          <svg viewBox="0 0 650 510" className="absolute inset-0 h-full w-full"><defs><filter id="founderGlow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{[[325,255,110,90],[325,255,530,90],[325,255,570,320],[325,255,325,445],[325,255,80,320],[110,90,530,90],[530,90,570,320],[570,320,325,445],[325,445,80,320],[80,320,110,90]].map((p,i)=><g key={i}><path d={`M${p[0]} ${p[1]} Q325 255 ${p[2]} ${p[3]}`} fill="none" stroke="rgba(151,123,235,.24)" strokeWidth="1" strokeDasharray={i<5?"5 7":"0"} className="commerce-dash"/><circle r="3" fill={i%3===0?"#E3C26D":i%2===0?"#53C99C":"#B39CFC"} filter="url(#founderGlow)"><animateMotion dur={`${4+i*.35}s`} repeatCount="indefinite" begin={`${i*-.5}s`} path={`M${p[0]} ${p[1]} Q325 255 ${p[2]} ${p[3]}`}/></circle></g>)}</svg>
          <div className="founder-core absolute left-1/2 top-1/2 grid h-32 w-32 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-[#9275ED]/30 bg-gradient-to-br from-[#6642DE] to-[#2B1B58] text-center shadow-[0_0_90px_rgba(103,65,223,.35)]"><div><Image src="/nefe-logo-white.png" alt="" width={200} height={200} className="mx-auto h-12 w-12 object-contain" /><span className="mt-1 block text-[6px] uppercase tracking-[.15em] text-[#C9B9FB]">Connected commerce</span></div></div>
          {[["Hotel","CH","17%","left-[8%] top-[12%]"],["Restaurant","MD","14%","right-[8%] top-[12%]"],["Beach Club","AB","16%","right-[2%] top-[58%]"],["Experience","TF","12%","left-1/2 bottom-0 -translate-x-1/2"],["Wellness","SW","13%","left-0 top-[58%]"]].map(([name,id,lift,pos])=><div key={name} className={`absolute ${pos} w-28 rounded-[16px] border border-white/10 bg-white/[.07] p-3 text-center backdrop-blur-xl`}><span className="mx-auto grid h-8 w-8 place-items-center rounded-[10px] bg-gradient-to-br from-[#7754E6] to-[#C29651] text-[7px] font-bold">{id}</span><p className="mt-2 text-[8px] font-semibold">{name}</p><p className="mt-1 text-[6px] text-[#54CCA0]">+{lift} referrals</p></div>)}
        </div>
      </div>
    </section>

    <section className="mx-auto max-w-[1240px] px-5 py-28 sm:px-8 sm:py-36">
      <SectionLabel number="03">Why Existing Software Falls Short</SectionLabel><div className="mt-5 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-2xl text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Every tool sees one business.<br/><span className="gradient-text">NEFE sees the relationship.</span></h2><p className="max-w-sm text-[11px] leading-6 text-[#817A87]">Existing platforms are excellent systems of record. NEFE becomes the system of connection.</p></div>
      <div className="mt-14 grid gap-4 lg:grid-cols-[1fr_1fr_1fr_1fr_1.25fr]">{[
        ["POS","Processes one transaction","Receipts & inventory","Local"],
        ["CRM","Manages one customer list","Leads & outreach","Local"],
        ["Booking Platforms","Fills one business's capacity","Reservations","Local"],
        ["Payment Systems","Moves money for one merchant","Payments","Local"],
        ["NEFE","Connects many businesses together","Growth, intelligence & value","Network"],
      ].map(([name,desc,data,scope],i)=><article key={name} className={`relative overflow-hidden rounded-[22px] border p-5 ${i===4?"border-[#8264E9] bg-gradient-to-br from-[#241844] to-[#5634C6] text-white shadow-[0_20px_50px_rgba(69,42,153,.2)]":"border-[#E7E2EA] bg-white"}`}>{i===4&&<div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-[#E5C16A]/10 blur-xl"/>}<span className={`text-[8px] font-bold uppercase tracking-[.14em] ${i===4?"text-[#D8CBFF]":"text-[#A39CA8]"}`}>{scope} system</span><h3 className="mt-8 text-lg font-semibold">{name}</h3><p className={`mt-3 min-h-16 text-[10px] leading-5 ${i===4?"text-white/60":"text-[#7E7784]"}`}>{desc}</p><div className={`mt-5 border-t pt-4 ${i===4?"border-white/10":"border-[#EEEAF0]"}`}><p className={`text-[7px] ${i===4?"text-white/30":"text-[#A39CA8]"}`}>PRIMARY VALUE</p><p className="mt-1 text-[9px] font-semibold">{data}</p></div></article>)}</div>
    </section>

    <section className="bg-[#F2EFF5] py-28 sm:py-36">
      <div className="mx-auto max-w-[1240px] px-5 sm:px-8"><SectionLabel number="04">How NEFE Creates Revenue</SectionLabel><div className="mt-5 grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><h2 className="text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">A compounding commercial model.</h2><p className="mt-5 max-w-md text-[11px] leading-6 text-[#7A7380]">Revenue expands as businesses join, partnerships deepen, customers move across the network and the infrastructure becomes embedded.</p><div className="mt-9 rounded-[22px] bg-[#1D152B] p-6 text-white shadow-[0_18px_45px_rgba(29,21,43,.18)]"><p className="text-[8px] font-bold uppercase tracking-[.15em] text-[#BBA9F8]">Illustrative annual recurring revenue</p><p className="mt-3 text-4xl font-semibold tracking-[-.04em]">AED 48.0M</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="founder-revenue-progress h-full rounded-full bg-gradient-to-r from-[#7653E8] via-[#C39452] to-[#53A78E]"/></div><div className="mt-3 flex justify-between text-[7px] text-white/35"><span>Software</span><span>Intelligence</span><span>Infrastructure</span></div></div></div>
        <div className="space-y-2">{revenueLayers.map((layer,i)=><div key={layer.name}><article className="group flex items-center gap-4 rounded-[18px] border border-[#E2DCE6] bg-white p-4 transition hover:-translate-x-1 hover:border-[#CDBFF7] hover:shadow-[0_12px_30px_rgba(47,32,80,.07)]"><div className="min-w-0 flex-1"><h3 className="text-[11px] font-semibold">{layer.name}</h3><p className="mt-1 text-[8px] text-[#918A96]">{layer.detail}</p></div><span className="rounded-full bg-[#F2EEFA] px-3 py-2 text-[8px] font-bold text-[#5E3BEE]">{layer.value}</span></article>{i<revenueLayers.length-1&&<div className="ml-9 h-4 w-px bg-gradient-to-b from-[#B6A7E5] to-[#D9D1DE]"/>}</div>)}</div></div></div>
    </section>

    <section className="mx-auto max-w-[1240px] px-5 py-28 sm:px-8 sm:py-36">
      <SectionLabel number="05">Roadmap</SectionLabel><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">From a premium market wedge<br/>to global commerce infrastructure.</h2>
      <div className="mt-14 grid gap-6 lg:grid-cols-[360px_1fr]"><div className="space-y-2">{phases.map((phase,i)=><button key={phase.phase} onClick={()=>setActivePhase(i)} className={`flex w-full items-center gap-4 rounded-[18px] border p-4 text-left transition ${activePhase===i?"border-[#C5B6F5] bg-[#F6F2FF] shadow-[0_10px_28px_rgba(57,38,103,.08)]":"border-[#E8E3EB] bg-white hover:border-[#D5CBE0]"}`}><span className="grid h-10 w-10 place-items-center rounded-xl text-[9px] font-bold text-white" style={{background:phase.color}}>0{i+1}</span><div><p className="text-[10px] font-semibold">{phase.phase} · {phase.label}</p><p className="mt-1 text-[8px] text-[#96909C]">{phase.period}</p></div><span className={`ml-auto text-sm ${activePhase===i?"text-[#5E3BEE]":"text-[#B5AEB9]"}`}>→</span></button>)}</div>
        <div className="prototype-modal overflow-hidden rounded-[26px] bg-gradient-to-br from-[#1E152F] to-[#3E277D] p-7 text-white sm:p-9"><div className="flex items-start justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.15em] text-[#BBA9F9]">{phases[activePhase].phase} · {phases[activePhase].period}</p><h3 className="mt-3 text-3xl font-semibold tracking-[-.04em]">{phases[activePhase].label}</h3></div><span className="text-3xl text-[#E1C16B]">✦</span></div><p className="mt-5 max-w-lg text-[12px] leading-6 text-white/55">{phases[activePhase].thesis}</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{phases[activePhase].items.map((item,i)=><div key={item} className="flex items-center gap-3 rounded-[14px] border border-white/10 bg-white/[.055] p-4"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/10 text-[8px] font-bold text-[#CFBFFF]">{i+1}</span><span className="text-[10px] font-medium">{item}</span><span className="ml-auto text-[8px] text-[#5ACB9F]">●</span></div>)}</div><div className="mt-9 flex items-center gap-3 border-t border-white/10 pt-5"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#7856EB] to-[#E0BD68]" style={{width:`${(activePhase+1)*25}%`}}/></div><span className="text-[8px] text-white/35">{(activePhase+1)*25}% horizon</span></div></div>
      </div>
    </section>

    <section className="border-y border-[#E8E3EB] bg-white py-28 sm:py-36"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="text-center"><div className="mx-auto w-fit"><SectionLabel number="06">Why Now</SectionLabel></div><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Five forces are converging.<br/><span className="gradient-text">NEFE sits at the intersection.</span></h2></div><div className="mt-16 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[
      ["AI","Makes partnership discovery, campaign design and retention intelligence autonomous.","01"],
      ["Digital Commerce","Customers expect fluid journeys across brands, channels and moments.","02"],
      ["Business Partnerships","Acquisition costs make shared audiences commercially inevitable.","03"],
      ["Loyalty","Static points are giving way to connected access, status and experiences.","04"],
      ["Digital Infrastructure","Digital rails can now operate quietly beneath valuable customer interactions.","05"],
    ].map(([title,detail,n])=><article key={title} className="founder-now-card relative min-h-64 overflow-hidden rounded-[22px] border border-[#E8E3EB] bg-[#FBFAFC] p-5 transition hover:-translate-y-2 hover:border-[#CFC2F6] hover:bg-white hover:shadow-[0_20px_45px_rgba(52,35,95,.08)]"><span className="text-[9px] font-bold text-[#B0A9B5]">{n}</span><div className="mt-10 grid h-10 w-10 place-items-center rounded-[13px] bg-gradient-to-br from-[#EEE9FF] to-[#FFF4DB] text-[#5E3BEE]">✦</div><h3 className="mt-5 text-[15px] font-semibold">{title}</h3><p className="mt-3 text-[9px] leading-5 text-[#827B87]">{detail}</p></article>)}</div><div className="mx-auto mt-12 flex max-w-2xl items-center gap-3"><span className="h-px flex-1 bg-gradient-to-r from-transparent to-[#B9ABE6]"/><span className="rounded-full border border-[#DDD4F7] bg-[#F7F3FF] px-4 py-2 text-[8px] font-bold uppercase tracking-[.14em] text-[#6548CF]">All converging now</span><span className="h-px flex-1 bg-gradient-to-l from-transparent to-[#B9ABE6]"/></div></div></section>

    <section className="founder-vision relative grid min-h-[92vh] place-items-center overflow-hidden bg-[#0B0811] px-5 py-32 text-center text-white">
      <div className="founder-dark-grid absolute inset-0 opacity-50"/><div className="founder-vision-orb"/><div className="relative z-10 mx-auto max-w-[1050px]"><span className="text-2xl text-[#E2C36C]">✦</span><p className="mt-7 text-[9px] font-bold uppercase tracking-[.22em] text-[#A991F4]">The Vision</p><h2 className="mt-8 text-[38px] font-semibold leading-[1.15] tracking-[-.05em] sm:text-[58px] lg:text-[70px]">NEFE is not building another technical infrastructure product.</h2><p className="mx-auto mt-9 max-w-[880px] text-xl leading-relaxed tracking-[-.02em] text-white/50 sm:text-2xl">NEFE is building the operating system where <span className="text-white">businesses collaborate</span>, <span className="text-[#E1C36F]">customers benefit</span>, and digital infrastructure quietly powers every interaction.</p><div className="mx-auto mt-14 h-px w-40 bg-gradient-to-r from-transparent via-[#8464E7] to-transparent"/><div className="mt-10 flex items-center justify-center gap-3"><Logo light/><span className="text-[8px] uppercase tracking-[.18em] text-white/25">Better business, together.</span></div></div><div className="founder-fade absolute inset-x-0 bottom-0 h-40"/></section>
  </main>;
}
